### ISSUE TITLE
提示新版本可用，点击更新按钮，无反应

### ISSUE THREAD

**Issue by yangchen158158** [josStorer/RWKV-Runner#1]
新版本可用：v1.0.1
更新   但是点击更新按钮，无反应！

**Comment by yangchen158158** [comment]
![image](https://github.com/josStorer/RWKV-Runner/assets/62718910/ba35c288-b778-409b-8c64-3fac1b550714)

**Comment by josStorer** [comment]
手动从gitee下载覆盖，1.0.1配置了gitee下载源
https://gitee.com/josc146/RWKV-Runner/releases/tag/v1.0.1

1.0.0配置的更新源是github，国内网络容易抽风
