### ISSUE TITLE
能否远程使用

### ISSUE THREAD

**Issue by kylincaster** [josStorer/RWKV-Runner#102]
如题，远程服务器是linux，如何才能在本地用windows的机器调用远程算力。

**Comment by josStorer** [comment]
参考 https://github.com/josStorer/RWKV-Runner/tree/master/deploy-examples/ChatGPT-Next-Web
有API

**Comment by josStorer** [comment]
https://github.com/josStorer/RWKV-Runner/blob/master/README_ZH.md#小贴士你可以在服务器部署backend-python然后将此程序仅用作客户端在设置的api-url中填入你的服务器地址
