### ISSUE TITLE
请问关于服务器响应的问题

### ISSUE THREAD

**Issue by shaoshu98** [josStorer/RWKV-Runner#104]
我在本地搭建了一套，用的服务器部署例子里的[ChatGPT-Next-Web]，跑的7Bworld，cpu fp32，跑起来以后可以使用，但是当我用不同浏览器给服务器发请求的时候，每次就只有一个响应，另一个明显是在排队，等第一个回复完，才会回复第二个响应。是因为用CPU跑的原因吗？谢谢。

**Comment by josStorer** [comment]
默认就是逐个响应的，同时响应则所有人都会减速，目前如果希望响应多个用户，我更倾向于增加设备，负载均衡，单机受限于计算机性能，同时响应可能反而体验不好，还会引入更复杂的配置

**Comment by josStorer** [comment]
可以在配置页面, 将Strategy切换到WebGPU, 支持并行响应
