### ISSUE TITLE
win的exe显示有病素

### ISSUE THREAD

**Issue by heiqilin1985** [josStorer/RWKV-Runner#106]
![image](https://github.com/josStorer/RWKV-Runner/assets/38761143/c266c65b-0c1a-4dc9-bb92-1f2328f2f8e7)
Trojan:Win32/Wacatac.H!ml

**Comment by cheng31869** [comment]
我也是，不知是不是真的有病毒

**Comment by win10ogod** [comment]
要如何自行編譯呢?

**Comment by win10ogod** [comment]
> 安装go wails 和 c++14 环境,然后 wails build -upx -ldflags "-s -w" -platform windows/amd64 ,在 build/bin 文件夹里

謝謝回復

**Comment by wolixixi** [comment]
windows 报严重病毒
![image](https://github.com/josStorer/RWKV-Runner/assets/138568011/a4be1034-16d6-4679-baa5-c2f4e671a806)

**Comment by josStorer** [comment]
报毒的添加信任，或者自己编译
编译流程参考 https://github.com/josStorer/RWKV-Runner/blob/master/.github/workflows/release.yml

**Comment by josStorer** [comment]
可尝试这个版本：https://github.com/josStorer/RWKV-Runner/releases/download/v1.3.6/RWKV-Runner_win.zip
移除了运行释放功能
