### ISSUE TITLE
使用langchain 过程中，报错，prompt 没有正确的格式化，但是用chatpgt的openai就可以正常使用，请问是我使用的问题，还是本身模型不支持langchain调用

### ISSUE THREAD

**Issue by gsk147** [josStorer/RWKV-Runner#107]
报错信息：openai.error.APIError: Invalid response object from API: '{"detail":[{"loc":["body","input"],"msg":"str type expected","type":"type_error.str"}]}' (HTTP response code was 422)

**Comment by gsk147** [comment]
![image](https://github.com/josStorer/RWKV-Runner/assets/23092007/7db366e7-20cc-4199-8984-303eeaf7e191)

**Comment by josStorer** [comment]
晚点修复, 同#96

**Comment by josStorer** [comment]
https://github.com/josStorer/RWKV-Runner/releases/tag/v1.3.7

**Comment by josStorer** [comment]
v1.3.9: https://github.com/josStorer/RWKV-Runner/releases/tag/v1.3.9
