### ISSUE TITLE
训练报错：wsl not running

### ISSUE THREAD

**Issue by Mochigomedango** [josStorer/RWKV-Runner#109]
训练报错：wsl not running

**Comment by josStorer** [comment]
#115

**Comment by josStorer** [comment]
执行`wsl --update`

**Comment by Azusa-Lover** [comment]
我的cmd里根本运行不了wsl --update怎么办
cmd内内容如下：
C:\Users\Administrator>wsl --update
命令行选项无效: --update
版权所有 (c) Microsoft Corporation。保留所有权利。

用法: wsl.exe [参数] [选项...] [命令行]

用于运行 Linux 二进制文件的参数:

    如果未提供命令行，wsl.exe 将启动默认的 shell。

    --exec, -e <命令行>
        执行指定的命令而不使用默认的 Linux shell。

    --
        按原样传递剩余的命令行。

选项:
    --distribution, -d <分发版>
        运行指定的分发。

    --user, -u <用户名>
        以指定用户身份运行。

用于管理适用于 Linux 的 Windows 子系统的参数:

    --export <分发版> <文件名>
        将分发导出到 tar 文件。
        对于标准输出，文件名可以是 -。

    --import <分发版> <安装位置> <文件名> [选项]
        将指定的 tar 文件作为新分发进行导入。
        对于标准输入，文件名可以是 -。

        选项:
            --version <版本>
                指定用于新分发的版本。

    --list, -l [选项]
        列出分发。

        选项:
            --all
                列出所有分发，包括当前正在
                安装或卸载的分发。

            --running
                只列出当前正在运行的分发。

            --quiet, -q
                只显示分发名称。

            --verbose, -v
                显示有关所有分发的详细信息。

    --set-default, -s <分发版>
        将分发设置为默认值。

    --set-default-version <版本>
        更改新分发的默认安装版本。

    --set-version <分发版> <版本>
        更改指定分发的版本。

    --shutdown
        立即终止所有正在运行的分发和 WSL 2 轻型工具虚拟机。

    --terminate, -t <分发版>
        终止指定的分发。

    --unregister <分发版>
        注销分发。

    --help
        显示用法信息。

**Comment by josStorer** [comment]
@Azusa-Lover 这说明你的wsl太老, 恐怕要更新windows版本
