### ISSUE TITLE
1.3.4版本点击训练没反应

### ISSUE THREAD

**Issue by zhuaiwhh** [josStorer/RWKV-Runner#110]
版本1.3.4转换默认的数据示例后，其他选项默认，点击训练没有反应，也没有进度
![屏幕截图 2023-07-05 095746](https://github.com/josStorer/RWKV-Runner/assets/36222175/7fded63d-79b2-47ab-9cc3-a69399f9852d)

**Comment by josStorer** [comment]
对于windows系统，确保你安装有Microsoft Store，服务器版本的系统无法正确调用

**Comment by zhuaiwhh** [comment]
> 对于windows系统，确保你安装有Microsoft Store，服务器版本的系统无法正确调用

谢谢 已安装，wsl2更新后，运行训练提示 wsl not running 请问是什么情况

**Comment by zhuaiwhh** [comment]
> 输入wsl看能否进入ubuntu系统，如果初次安装，需要进行初始设置
输入wsl 可以正常进去ubuntu系统

**Comment by josStorer** [comment]
wsl -l -v确认是wsl2版本吗
关闭程序重启，再点击训练

**Comment by zhuaiwhh** [comment]
> 输入wsl看能否进入ubuntu系统，如果初次安装，需要进行初始设置
![WechatIMG7](https://github.com/josStorer/RWKV-Runner/assets/36222175/86018999-d5fd-4ea5-956b-38373f1851c5)
这样

**Comment by zhuaiwhh** [comment]
> wsl -l -v确认是wsl2版本吗 关闭程序重启，再点击训练

![WechatIMG8](https://github.com/josStorer/RWKV-Runner/assets/36222175/c8b2c3ab-786e-451a-9456-4e5325987f20)
wsl2 版本

**Comment by josStorer** [comment]
继续点击训练仍无反应？

**Comment by zhuaiwhh** [comment]
> 继续点击训练仍无反应？
重启电脑后点击 训练 仍然提示 wsl not running

**Comment by zhuaiwhh** [comment]
> 继续点击训练仍无反应？

![WechatIMG9](https://github.com/josStorer/RWKV-Runner/assets/36222175/d494e865-90f1-4e58-a0e4-b2bcccf9149b)
跳出窗口后 无反应 提示  wsl not running

**Comment by josStorer** [comment]
![G ERB1M)LHY7HPSLY%_AJI](https://github.com/josStorer/RWKV-Runner/assets/13366013/3dd84044-4c6e-424d-a7ff-42033459e3c7)
难搞，这个错误意味着wsl确实不在运行中

**Comment by zhuaiwhh** [comment]
> ![G ERB1M)LHY7HPSLY%_AJI](https://user-images.githubusercontent.com/13366013/251184837-3dd84044-4c6e-424d-a7ff-42033459e3c7.jpg) 难搞，这个错误意味着wsl确实不在运行中


![WX20230705-224148@2x](https://github.com/josStorer/RWKV-Runner/assets/36222175/6ad9b228-9173-49db-af41-3ec96d62a8ec)
我再尝试尝试

**Comment by zhuaiwhh** [comment]
已解决，在Microsoft Store 重新安装wsl  或者 直接命令行窗口运行 wsl.exe --update 把wsl更新到最新版就可以运行

**Comment by josStorer** [comment]
ok
