### ISSUE TITLE
1.3.4python依赖缺失

### ISSUE THREAD

**Issue by 39499740** [josStorer/RWKV-Runner#111]
点击运行时候提示依赖缺失，提示ImportError: DLL load failed while importing ujson: 找不到指定的模块。点安装后黑框闪过，仍然是这个错误。
我更换过版本，包括1.0.8，1.1.0等，依然无效

**Comment by gtayne** [comment]
一样的问题，m1 mac，提示依赖包的问题

**Comment by yingwei13mei** [comment]
win11 上面也是这个问题

**Comment by josStorer** [comment]
试试这个 https://stackoverflow.com/questions/20201868/importerror-dll-load-failed-the-specified-module-could-not-be-found

**Comment by josStorer** [comment]
装vc库 https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by 39499740** [comment]
![image](https://github.com/josStorer/RWKV-Runner/assets/29425312/ad331c4c-6b90-4759-8367-1f395e4999af)


> 装vc库 https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by 39499740** [comment]
> 装vc库 https://aka.ms/vs/16/release/vc_redist.x64.exe

升级到1.3.6好了

**Comment by nonotouchtouch** [comment]
缺少依赖的问题可以使用以下解决方法：
先运行命令 which python3，复制输出结果，粘贴到程序左下角设置--高级--自定义python路径
重新安装依赖即可
