### ISSUE TITLE
训练到这一步就停止没反应了不知道什么情况，如图

### ISSUE THREAD

**Issue by zhuaiwhh** [josStorer/RWKV-Runner#113]
![WechatIMG10](https://github.com/josStorer/RWKV-Runner/assets/36222175/ea27e036-f9d6-4b86-9fa3-8af1384acae7)

**Comment by zhuaiwhh** [comment]
![屏幕截图 2023-07-06 115327](https://github.com/josStorer/RWKV-Runner/assets/36222175/584ffb59-ee40-4d1f-98bf-ff3437240a06)

**Comment by josStorer** [comment]
内存不足，先用0.1B测试

**Comment by zhuaiwhh** [comment]
换成0.1B测试训练又出问题了 太难了
![屏幕截图 2023-07-06 154659](https://github.com/josStorer/RWKV-Runner/assets/36222175/333dcffd-46dd-430f-a578-f47a8026b501)

**Comment by josStorer** [comment]
你是不是用了自定义数据
数据量如果太少，上下文长度要降低

**Comment by zhuaiwhh** [comment]
是的自定义数据，问答模式，上下文长度是不是调整为0

**Comment by zhuaiwhh** [comment]
> 你是不是用了自定义数据 数据量如果太少，上下文长度要降低

{"text": "Question: 问题内容\n问题内容\n\nAnswer: 问题回答\n问题回答\n\n"}  这种格式的

**Comment by josStorer** [comment]
不是调整为0，其实正经训练1024是合适的，你的实际问题是给的数据太少，这样模型很容易炼坏

**Comment by zhuaiwhh** [comment]
> 不是调整为0，其实正经训练1024是合适的，你的实际问题是给的数据太少，这样模型很容易炼坏

一般数据量 建议最少使用多少比较合适

**Comment by josStorer** [comment]
多多益善

**Comment by zhuaiwhh** [comment]
> 多多益善

我就根据示例数据搞了7条，继续增加我再试试  感谢
