### ISSUE TITLE
训练出现wsl not running提示

### ISSUE THREAD

**Issue by xiexidong** [josStorer/RWKV-Runner#115]
1.Ubuntu安装版本为22.04，Ubuntu内可以使用命令nvcc -V
2.c:/windows/system32下直接点击wsl.exe可以正常打开窗口并显示Ubuntu命令
3.wsl -l -v命令显示wsl版本为2
4.操作系统为win11，新安装的
![image](https://github.com/josStorer/RWKV-Runner/assets/19529227/e89dea77-435e-4cad-b8bb-3c6b597cb449)

直接点击wsl.exe如下：
![image](https://github.com/josStorer/RWKV-Runner/assets/19529227/1eda7fbb-1007-4e9c-9825-da2a09f6f1ac)

![image](https://github.com/josStorer/RWKV-Runner/assets/19529227/a271596f-2e45-44af-b94d-f2644af1d011)

![image](https://github.com/josStorer/RWKV-Runner/assets/19529227/1e7c5be3-39b6-4544-a035-6f2fce3fa453)

请您知道一下会是哪里出了问题

**Comment by xiexidong** [comment]
字打错了，请您指导一下哪里出了问题，谢谢

**Comment by xiexidong** [comment]
补充一下，点击训练按钮唤起的wsl窗口路径，和我直接点击wsl.exe显示的不一样，不知道有没有关系，如图
![image](https://github.com/josStorer/RWKV-Runner/assets/19529227/e751faae-72af-46ec-b32a-d48e25f19eb6)

**Comment by jinbingzhi0931** [comment]
我的解决了，wls安装配置完之后，C:\Windows\system32\wsl.exe打开后不会秒退，然后在cmd运行wsl.exe --update，训练就不会报错了

**Comment by josStorer** [comment]
目前常见的两个问题，一个是提示wsl not running，执行wsl --update可解决
另一个问题是，启动后出现
```
+= '+PTX'
IndexError: list index out of range
```
使用`wsl --set-version Ubuntu-22.04 2` 升级解决

**Comment by xiexidong** [comment]
提交issues之前已经执行过wsl --update了，更新完后，重启了电脑，再次执行提示已经是最新版本。

**Comment by xiexidong** [comment]
> 我的解决了，wls安装配置完之后，C:\Windows\system32\wsl.exe打开后不会秒退，然后在cmd运行wsl.exe --update，训练就不会报错了

我的也已经更新过了wsl，并没有解决这个问题

**Comment by jinbingzhi0931** [comment]
> > 我的解决了，wls安装配置完成之后，C:\Windows\system32\wsl.exe打开后不会秒退，然后在cmd运行wsl.exe --update，训练就不会报错了
> 
> 我的也已经更新了wsl，并没有解决这个问题

C:\Windows\system32\wsl.exe文件打开后可以正常运行吗

**Comment by xiexidong** [comment]
> C:\Windows\system32\wsl.exe文件打开后可以正常运行吗

是的，直接运行wsl.exe可以正常运行，里面的命令也可以正确运行，包括我还尝试了使用管理员权限打开runner.exe，问题依旧

**Comment by jinbingzhi0931** [comment]
> 是的，直接运行wsl.exe可以正常运行，里面的命令也可以正确运行，包括我还尝试了使用管理员权限打开runner.exe，问题依旧

https://learn.microsoft.com/zh-cn/windows/wsl/basic-commands，建议卸载后重新安装吧，从runner.exe运行训练的提示框中进入安装，首次打开wsl.exe后设置用户密码，也设置一下root用户的密码 sudo passwd root，最后再更新一下

**Comment by xiexidong** [comment]
> > 是的，直接运行wsl.exe可以正常运行，里面的命令也可以正确运行，包括我还尝试了使用管理员权限打开runner.exe，问题依旧
> 
> [https://learn.microsoft.com/zh-cn/windows/wsl/basic-commands，建议卸载后重新安装吧，从runner.exe运行训练的提示框中进入安装，首次打开wsl.exe后设置用户密码，也设置一下root用户的密码](https://learn.microsoft.com/zh-cn/windows/wsl/basic-commands%EF%BC%8C%E5%BB%BA%E8%AE%AE%E5%8D%B8%E8%BD%BD%E5%90%8E%E9%87%8D%E6%96%B0%E5%AE%89%E8%A3%85%E5%90%A7%EF%BC%8C%E4%BB%8Erunner.exe%E8%BF%90%E8%A1%8C%E8%AE%AD%E7%BB%83%E7%9A%84%E6%8F%90%E7%A4%BA%E6%A1%86%E4%B8%AD%E8%BF%9B%E5%85%A5%E5%AE%89%E8%A3%85%EF%BC%8C%E9%A6%96%E6%AC%A1%E6%89%93%E5%BC%80wsl.exe%E5%90%8E%E8%AE%BE%E7%BD%AE%E7%94%A8%E6%88%B7%E5%AF%86%E7%A0%81%EF%BC%8C%E4%B9%9F%E8%AE%BE%E7%BD%AE%E4%B8%80%E4%B8%8Broot%E7%94%A8%E6%88%B7%E7%9A%84%E5%AF%86%E7%A0%81) sudo passwd root，最后再更新一下

好的，我再尝试一下，感谢你的回复

**Comment by SetoKaiba** [comment]
@xiexidong 你后来解决了吗？我跟你一模一样，cmd运行wsl可以运行，然后从RWKV-Runner拉起就说不行。
