### ISSUE TITLE
api /reset-state error

### ISSUE THREAD

**Issue by R2100** [josStorer/RWKV-Runner#116]
### /reset-state api Error. " NameError: name 'cyac' is not defined  "
> File "....\backend-python\routes\state_cache.py", line 88, in reset_state
>     trie = cyac.Trie()
> NameError: name 'cyac' is not defined

I'm using W10, allways the same error from curl, fetch...
The same issue from 

- http://127.0.0.1:8000/docs
- curl -X 'POST'   'http://127.0.0.1:8000/reset-state'  -H 'accept: application/json'   -d ''
- chrome:  fetch("http://127.0.0.1:8000/reset-state", { 	  method: "POST",	  headers: { "Content-Type": "application/json" }	}) 

I try to remove cyac python.exe -m pip uninstall cyac but not working
There are a file requirements_without_cyac.txt in /backend-python  ¿how can i run it without cyac?

**Comment by josStorer** [comment]
The state-related APIs is currently not complete and is only used internally.

**Comment by josStorer** [comment]
just uninstall cyac, it will run without cyac, and the state cache will be disabled
