### ISSUE TITLE
除了对接chatgptbox还能对接别处吗

### ISSUE THREAD

**Issue by Kiritor729** [josStorer/RWKV-Runner#117]
像需要api key，甚至token、cookie的，我去查询了下我自己设置的api key的余额，显示账号被封233

**Comment by josStorer** [comment]
大部分chatgpt应用都能直接使用，没有实现余额查询接口所以会被部分客户端认为账号被封

**Comment by Kiritor729** [comment]
害，有些应用默认api.openai.com不能改，不过已经能运用到一些了，看到你的回复之后重新去试出来的，感谢！

**Comment by Kiritor729** [comment]
> 大部分chatgpt应用都能直接使用，没有实现余额查询接口所以会被部分客户端认为账号被封

**Comment by Kiritor729** [comment]
> 大部分chatgpt应用都能直接使用，没有实现余额查询接口所以会被部分客户端认为账号被封

害，有些应用默认api.openai.com不能改，不过已经能运用到一些了，看到你的回复之后重新去试出来的，感谢！
