### ISSUE TITLE
咨询一下可不可以本地部署,利用动态解析外网使用.

### ISSUE THREAD

**Issue by taurusduan** [josStorer/RWKV-Runner#118]
本地部署没有问题,但是利用ip访问却无法连接,不知道是不是需要给127.0.0.1:8000设置本机ip啊.求助

**Comment by josStorer** [comment]
![image](https://github.com/josStorer/RWKV-Runner/assets/13366013/8c0ad92b-3cdf-4150-be7d-6c1f7f5765d2)
