### ISSUE TITLE
找不到自定义cuda文件

### ISSUE THREAD

**Issue by xiaocod** [josStorer/RWKV-Runner#12]
开启使用自定义cuda算子加速选项后运行，提示找不到支持的自定义cuda文件，这个怎么解决啊？

**Comment by xiaocod** [comment]
哦，我的是1660ti

**Comment by josStorer** [comment]
我下版本推送一下看16系能不能跑，理论上没问题，到时候你可以试试

**Comment by xiaocod** [comment]
好的

**Comment by josStorer** [comment]
使用最新版1.0.7试试

**Comment by josStorer** [comment]
@luzamm 我没这个卡，没法测试，你要是能编译源码，在这一行，可以把你的显卡型号加上测试下
https://github.com/josStorer/RWKV-Runner/blob/master/frontend/src/utils/index.tsx#L287
