### ISSUE TITLE
训练报错“RuntimeError: Error building extension 'wkv_1024_bf16'”

### ISSUE THREAD

**Issue by xq2hz** [josStorer/RWKV-Runner#121]
apt cnMirror already set
gcc installed
pip installed
ninja installed
cuda 12 installed
requirements satisfied
loading models/RWKV-4-World-CHNtuned-3B-v1-20230625-ctx4096.pth
--n_layer 32 --n_embd 2560
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
warnings.warn(
########## work in progress ##########
[2023-07-09 19:34:05,543] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
############################################################################
#
# RWKV-4 BF16 on 1x1 GPU, bsz 1x1x1=1, deepspeed_stage_2
#
# Data = ./finetune/json2binidx_tool/data/train_text_document (binidx), ProjDir = lora-models
#
# Epoch = 0 to 19 (will continue afterwards), save every 5 epoch
#
# Each "epoch" = 1000 steps, 1000 samples, 1024000 tokens
#
# Model = 32 n_layer, 2560 n_embd, 1024 ctx_len
# LoRA = enabled, 8 r, 32.0 alpha, 0.01 dropout, on att,ffn,time,ln
#
# Adam = lr 5e-05 to 5e-05, warmup 0 steps, beta (0.9, 0.999), eps 1e-08
#
# Found torch 1.13.1+cu117, recommend 1.13.1+cu117 or newer
# Found deepspeed 0.9.5, recommend 0.7.0 (faster than newer versions)
# Found pytorch_lightning 1.9.5, recommend 1.9.1 or newer
#
############################################################################
{'load_model': 'models/RWKV-4-World-CHNtuned-3B-v1-20230625-ctx4096.pth', 'wandb': '', 'proj_dir': 'lora-models', 'random_seed': -1, 'data_file': './finetune/json2binidx_tool/data/train_text_document', 'data_type': 'binidx', 'vocab_size': 65536, 'ctx_len': 1024, 'epoch_steps': 1000, 'epoch_count': 20, 'epoch_begin': 0, 'epoch_save': 5, 'micro_bsz': 1, 'n_layer': 32, 'n_embd': 2560, 'dim_att': 2560, 'dim_ffn': 10240, 'pre_ffn': 0, 'head_qk': 0, 'tiny_att_dim': 0, 'tiny_att_layer': -999, 'lr_init': 5e-05, 'lr_final': 5e-05, 'warmup_steps': 0, 'beta1': 0.9, 'beta2': 0.999, 'adam_eps': 1e-08, 'grad_cp': 0, 'my_pile_stage': 0, 'my_pile_shift': -1, 'my_pile_edecay': 0, 'layerwise_lr': 1, 'ds_bucket_mb': 200, 'my_img_version': 0, 'my_img_size': 0, 'my_img_bit': 0, 'my_img_clip': 'x', 'my_img_clip_scale': 1, 'my_img_l1_scale': 0, 'my_img_encoder': 'x', 'my_sample_len': 0, 'my_ffn_shift': 1, 'my_att_shift': 1, 'my_pos_emb': 0, 'load_partial': 0, 'magic_prime': 0, 'my_qa_mask': 0, 'my_testing': '', 'lora': True, 'lora_load': '', 'lora_r': 8, 'lora_alpha': 32.0, 'lora_dropout': 0.01, 'lora_parts': 'att,ffn,time,ln', 'logger': False, 'enable_checkpointing': False, 'default_root_dir': None, 'gradient_clip_val': 1.0, 'gradient_clip_algorithm': None, 'num_nodes': 1, 'num_processes': None, 'devices': '1', 'gpus': None, 'auto_select_gpus': None, 'tpu_cores': None, 'ipus': None, 'enable_progress_bar': True, 'overfit_batches': 0.0, 'track_grad_norm': -1, 'check_val_every_n_epoch': 100000000000000000000, 'fast_dev_run': False, 'accumulate_grad_batches': 8, 'max_epochs': -1, 'min_epochs': None, 'max_steps': -1, 'min_steps': None, 'max_time': None, 'limit_train_batches': None, 'limit_val_batches': None, 'limit_test_batches': None, 'limit_predict_batches': None, 'val_check_interval': None, 'log_every_n_steps': 100000000000000000000, 'accelerator': 'gpu', 'strategy': 'deepspeed_stage_2', 'sync_batchnorm': False, 'precision': 'bf16', 'enable_model_summary': True, 'num_sanity_val_steps': 0, 'resume_from_checkpoint': None, 'profiler': None, 'benchmark': None, 'reload_dataloaders_every_n_epochs': 0, 'auto_lr_find': False, 'replace_sampler_ddp': False, 'detect_anomaly': False, 'auto_scale_batch_size': False, 'plugins': None, 'amp_backend': None, 'amp_level': None, 'move_metrics_to_cpu': False, 'multiple_trainloader_mode': 'max_size_cycle', 'inference_mode': True, 'my_timestamp': '2023-07-09-19-34-06', 'betas': (0.9, 0.999), 'real_bsz': 1, 'run_name': '65536 ctx1024 L32 D2560'}
Using /root/.cache/torch_extensions/py310_cu117 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/torch_extensions/py310_cu117/wkv_1024_bf16/build.ninja...
Building extension module wkv_1024_bf16...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
RWKV_MY_TESTING
[1/3] c++ -MMD -MF wkv_op_bf16.o.d -DTORCH_EXTENSION_NAME=wkv_1024_bf16 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /usr/local/lib/python3.10/dist-packages/torch/include -isystem /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include -isystem /usr/local/lib/python3.10/dist-packages/torch/include/TH -isystem /usr/local/lib/python3.10/dist-packages/torch/include/THC -isystem /usr/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -c /mnt/d/AI/RWKV-Runner/finetune/lora/cuda/wkv_op_bf16.cpp -o wkv_op_bf16.o
[2/3] /usr/bin/nvcc -DTORCH_EXTENSION_NAME=wkv_1024_bf16 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /usr/local/lib/python3.10/dist-packages/torch/include -isystem /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include -isystem /usr/local/lib/python3.10/dist-packages/torch/include/TH -isystem /usr/local/lib/python3.10/dist-packages/torch/include/THC -isystem /usr/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -t 4 -std=c++17 -res-usage --maxrregcount 60 --use_fast_math -O3 -Xptxas -O3 --extra-device-vectorization -DTmax=1024 -c /mnt/d/AI/RWKV-Runner/finetune/lora/cuda/wkv_cuda_bf16.cu -o wkv_cuda_bf16.cuda.o
FAILED: wkv_cuda_bf16.cuda.o
/usr/bin/nvcc -DTORCH_EXTENSION_NAME=wkv_1024_bf16 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /usr/local/lib/python3.10/dist-packages/torch/include -isystem /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include -isystem /usr/local/lib/python3.10/dist-packages/torch/include/TH -isystem /usr/local/lib/python3.10/dist-packages/torch/include/THC -isystem /usr/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -t 4 -std=c++17 -res-usage --maxrregcount 60 --use_fast_math -O3 -Xptxas -O3 --extra-device-vectorization -DTmax=1024 -c /mnt/d/AI/RWKV-Runner/finetune/lora/cuda/wkv_cuda_bf16.cu -o wkv_cuda_bf16.cuda.o
ptxas info : 1 bytes gmem
ptxas info : Compiling entry function '_Z15kernel_backwardiiiPKfPKN3c108BFloat16ES4_S4_S4_S4_PS2_S5_S5_S5_' for 'sm_86'
ptxas info : Function properties for _Z15kernel_backwardiiiPKfPKN3c108BFloat16ES4_S4_S4_S4_PS2_S5_S5_S5_
8192 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info : Used 51 registers, 448 bytes cmem[0], 8 bytes cmem[2]
ptxas info : Compiling entry function '_Z14kernel_forwardiiiPKfPKN3c108BFloat16ES4_S4_PS2_' for 'sm_86'
ptxas info : Function properties for _Z14kernel_forwardiiiPKfPKN3c108BFloat16ES4_S4_PS2_
0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info : Used 33 registers, 408 bytes cmem[0]
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
435 | function(_Functor&& __f)
| ^
/usr/include/c++/11/bits/std_function.h:435:145: note: ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
530 | operator=(_Functor&& __f)
| ^
/usr/include/c++/11/bits/std_function.h:530:146: note: ‘_ArgTypes’
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 1900, in _run_ninja_build
subprocess.run(
File "/usr/lib/python3.10/subprocess.py", line 524, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/mnt/d/AI/RWKV-Runner/./finetune/lora/train.py", line 339, in <module>
from src.trainer import train_callback, generate_init_weight
File "/mnt/d/AI/RWKV-Runner/finetune/lora/src/trainer.py", line 6, in <module>
from .model import LORA_CONFIG
File "/mnt/d/AI/RWKV-Runner/finetune/lora/src/model.py", line 56, in <module>
wkv_cuda = load(name=f"wkv_{T_MAX}_bf16", sources=["finetune/lora/cuda/wkv_op_bf16.cpp", "finetune/lora/cuda/wkv_cuda_bf16.cu"], verbose=True, extra_cuda_cflags=["-t 4", "-std=c++17", "-res-usage", "--maxrregcount 60", "--use_fast_math", "-O3", "-Xptxas -O3", "--extra-device-vectorization", f"-DTmax={T_MAX}"])
File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 1284, in load
return _jit_compile(
File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 1508, in _jit_compile
_write_ninja_file_and_build_library(
File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 1623, in _write_ninja_file_and_build_library
_run_ninja_build(
File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 1916, in _run_ninja_build
raise RuntimeError(message) from e
RuntimeError: Error building extension 'wkv_1024_bf16'

步骤
1、txt文件改后缀名存为finetune/data/train.jsonl，点击“转换”在finetune\json2binidx_tool\data目录生成了train_text_document.bin（284MB）和train_text_document.idx(862KB)
2、基底模型选RWKV-4-World-CHNtuned-3B-v1-20230625-ctx4096.pth，其他默认点“训练”

**Comment by josStorer** [comment]
精度改为fp16

**Comment by xq2hz** [comment]
<img width="1378" alt="image" src="https://github.com/josStorer/RWKV-Runner/assets/139051478/86f8ad40-020b-40fc-a252-edba9bb37b4b">

{'load_model': 'models/RWKV-4-World-CHNtuned-3B-v1-20230625-ctx4096.pth', 'wandb': '', 'proj_dir': 'lora-models', 'random_seed': -1, 'data_file': './finetune/json2binidx_tool/data/train_text_document', 'data_type': 'binidx', 'vocab_size': 65536, 'ctx_len': 1024, 'epoch_steps': 1000, 'epoch_count': 20, 'epoch_begin': 0, 'epoch_save': 5, 'micro_bsz': 1, 'n_layer': 32, 'n_embd': 2560, 'dim_att': 2560, 'dim_ffn': 10240, 'pre_ffn': 0, 'head_qk': 0, 'tiny_att_dim': 0, 'tiny_att_layer': -999, 'lr_init': 5e-05, 'lr_final': 5e-05, 'warmup_steps': 0, 'beta1': 0.9, 'beta2': 0.999, 'adam_eps': 1e-08, 'grad_cp': 0, 'my_pile_stage': 0, 'my_pile_shift': -1, 'my_pile_edecay': 0, 'layerwise_lr': 1, 'ds_bucket_mb': 200, 'my_img_version': 0, 'my_img_size': 0, 'my_img_bit': 0, 'my_img_clip': 'x', 'my_img_clip_scale': 1, 'my_img_l1_scale': 0, 'my_img_encoder': 'x', 'my_sample_len': 0, 'my_ffn_shift': 1, 'my_att_shift': 1, 'my_pos_emb': 0, 'load_partial': 0, 'magic_prime': 0, 'my_qa_mask': 0, 'my_testing': '', 'lora': True, 'lora_load': '', 'lora_r': 8, 'lora_alpha': 32.0, 'lora_dropout': 0.01, 'lora_parts': 'att,ffn,time,ln', 'logger': False, 'enable_checkpointing': False, 'default_root_dir': None, 'gradient_clip_val': 1.0, 'gradient_clip_algorithm': None, 'num_nodes': 1, 'num_processes': None, 'devices': '1', 'gpus': None, 'auto_select_gpus': None, 'tpu_cores': None, 'ipus': None, 'enable_progress_bar': True, 'overfit_batches': 0.0, 'track_grad_norm': -1, 'check_val_every_n_epoch': 100000000000000000000, 'fast_dev_run': False, 'accumulate_grad_batches': 8, 'max_epochs': -1, 'min_epochs': None, 'max_steps': -1, 'min_steps': None, 'max_time': None, 'limit_train_batches': None, 'limit_val_batches': None, 'limit_test_batches': None, 'limit_predict_batches': None, 'val_check_interval': None, 'log_every_n_steps': 100000000000000000000, 'accelerator': 'gpu', 'strategy': 'deepspeed_stage_2', 'sync_batchnorm': False, 'precision': 'fp16', 'enable_model_summary': True, 'num_sanity_val_steps': 0, 'resume_from_checkpoint': None, 'profiler': None, 'benchmark': None, 'reload_dataloaders_every_n_epochs': 0, 'auto_lr_find': False, 'replace_sampler_ddp': False, 'detect_anomaly': False, 'auto_scale_batch_size': False, 'plugins': None, 'amp_backend': None, 'amp_level': None, 'move_metrics_to_cpu': False, 'multiple_trainloader_mode': 'max_size_cycle', 'inference_mode': True, 'my_timestamp': '2023-07-09-20-22-19', 'betas': (0.9, 0.999), 'real_bsz': 1, 'run_name': '65536 ctx1024 L32 D2560'}
Note: you are using fp16 (might overflow). Try bf16 / tf32 for stable training.
Using /root/.cache/torch_extensions/py310_cu117 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/torch_extensions/py310_cu117/wkv_1024/build.ninja...
RWKV_MY_TESTING
Building extension module wkv_1024...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module wkv_1024...
Current vocab size = 65536 (make sure it's correct)
Data has 74490855 tokens.
./finetune/install-wsl-dep-and-train.sh: line 52: 707 Killed python3 ./finetune/lora/train.py $modelInfo $@ --proj_dir lora-models --data_type binidx --lora --lora_parts=att,ffn,time,ln --strategy deepspeed_stage_2 --accelerator gpu

笔记本：CPU：7840h GPU：4060 8g，内存16g，虚拟内存最小64g

**Comment by josStorer** [comment]
16G内存不够训练3B规模

**Comment by xq2hz** [comment]
请教：虚拟内存设的再大也不行吗？训练3B规模需要多大内存？

**Comment by josStorer** [comment]
大概32G

**Comment by josStorer** [comment]
尝试配置wsl的swap空间

**Comment by josStorer** [comment]
参考 https://gist.github.com/viannaandreBR/fe3f624bd912ec8744a33a5da15e399e

**Comment by xq2hz** [comment]
1、把基底改为0.4B，报错：未安装匹配的CUDA
Installed CUDA version 11.5 does not match the version torch was compiled with 11.7 but since the APIs are compatible, accepting this combination
2、我尝试安装了cuda 11.7，在WSL里配置环境变量显示切换到11.7了，但RWKV-runner里的wsl始终显示11.5

<img width="1009" alt="image" src="https://github.com/josStorer/RWKV-Runner/assets/139051478/03ef6a5c-a543-4898-89cb-ed8c6fc0e7fd">

**Comment by josStorer** [comment]
wsl -l -v看一下，可能调用的不是同一个系统

**Comment by xq2hz** [comment]
虽然乱码，依稀看得出来，是一个系统
<img width="641" alt="image" src="https://github.com/josStorer/RWKV-Runner/assets/139051478/90b9822d-3976-42cd-8eb0-30c459ee2ca8">

**Comment by josStorer** [comment]
退出程序，重新打开，再试试nvcc

**Comment by xq2hz** [comment]
试过了没用，包括重启系统，wsl --shutdown

**Comment by josStorer** [comment]
我觉得调用的不是同一个，你 wsl -d Ubuntu 进去看看

**Comment by xq2hz** [comment]
这种情况还会存在多个吗？
<img width="681" alt="image" src="https://github.com/josStorer/RWKV-Runner/assets/139051478/87a291df-2ff6-4a86-8765-f04fceed19a1">

**Comment by xq2hz** [comment]
这种情况还会存在多个吗？
<img width="681" alt="image" src="https://github.com/josStorer/RWKV-Runner/assets/139051478/87a291df-2ff6-4a86-8765-f04fceed19a1">

**Comment by xq2hz** [comment]
这种情况还会存在多个吗？
<img width="681" alt="image" src="https://github.com/josStorer/RWKV-Runner/assets/139051478/87a291df-2ff6-4a86-8765-f04fceed19a1">

**Comment by josStorer** [comment]
你用sudo权限装一个吧，装在root用户下

**Comment by xq2hz** [comment]
感谢您的帮助，汇报一下进展：
用wsl --unregister 卸载然后重装了ubuntu，一路傻瓜操作，0.1B的基底+精度bf16，GPU占用3.5G
<img width="805" alt="image" src="https://github.com/josStorer/RWKV-Runner/assets/139051478/0cf4891f-1647-4d88-a465-099926d56bcf">
