### ISSUE TITLE
每日新增语料如何训练？

### ISSUE THREAD

**Issue by xq2hz** [josStorer/RWKV-Runner#122]
多数行业每日都会更新少量语料，但训练还是比较耗时的。
如何做到尽快将新语料加入模型，有什么好的建议？

0.1B的基底+300M的新语料，24小时还没跑完，显卡太差了
<img width="1344" alt="image" src="https://github.com/josStorer/RWKV-Runner/assets/139051478/eb45c895-215e-43dc-a876-2f9c910087b7">

**Comment by josStorer** [comment]
你这个训练轮次太多了，目前是要自己手动停止，然后选择一个LoRA合并

**Comment by xq2hz** [comment]
好的，一般训练多少轮次还是只要LOSS低于多少就可以了？

**Comment by josStorer** [comment]
loss降了就行，loss也不要太低，一般0.5以下即可，不同数据情况也会不同
学习率可以加到1e-4
LoRA R适当增加

**Comment by BlinkDL** [comment]
0.1B的lora极限低。可以全量微调。
