### ISSUE TITLE
请问如何在调用接口的时候上下文关联？

### ISSUE THREAD

**Issue by keeepman** [josStorer/RWKV-Runner#126]
你好，本地聊天是上下文关联的，调用swagger中/chat/completions接口时，如何做到上下文关联？

**Comment by josStorer** [comment]
将上下文传入即可，参考chatgpt的api
api内部实现了缓存，只计算增量，你可以直接把历史对话全部传递过去

**Comment by keeepman** [comment]
解决了 谢谢大佬
