### ISSUE TITLE
使用docker搭建的FastGPT调用Rwkv runner 的api接口时报错：”Request failed with status code 422“

### ISSUE THREAD

**Issue by evanstark** [josStorer/RWKV-Runner#127]
FastGPT接口配置：
![image](https://github.com/josStorer/RWKV-Runner/assets/50606674/c0253207-463d-44ee-aae2-55804f053db0)
FastGPT界面报错：
![image](https://github.com/josStorer/RWKV-Runner/assets/50606674/1754c1cc-0b38-4511-8b89-fd00d07e010b)
Rwkv runner命令行窗口报错：
![image](https://github.com/josStorer/RWKV-Runner/assets/50606674/81240554-03be-4360-b59d-18d1f02d0f50)
而且此报错会一直循环往复，直到关闭FastGPT的Docker镜像

**Comment by josStorer** [comment]
本地有`api.log`文件, 给我看一下内容

**Comment by josStorer** [comment]
试试最新版本

**Comment by evanstark** [comment]
感谢大佬！！更新到v1.3.9已经不报422错误了，但是出现了新的问题：
FastGPT在不关联知识库的情况下，仅作为聊天，已经可以跟RWKV进行交互了，但FastGPT主要亮点就是在知识库上。当关联上知识库进行对话时，会报错：different vector dimensions 1536 and 4096
![image](https://github.com/josStorer/RWKV-Runner/assets/50606674/a502924f-c1cb-4f62-90f7-0dda869f787c)
对应api.log文档内容：
![image](https://github.com/josStorer/RWKV-Runner/assets/50606674/659d7cba-c9de-4bd9-bd68-3c8f96b41dc2)
对比不加载知识库时的内容：
![image](https://github.com/josStorer/RWKV-Runner/assets/50606674/d715bb53-3a57-4e25-a2fc-d32a50581196)
不加载知识库时api.log文档对应内容：
![image](https://github.com/josStorer/RWKV-Runner/assets/50606674/c06d4ca3-9a2b-4f51-be85-bfab185fe635)

**Comment by josStorer** [comment]
因为知识库使用了embeddings API，而openai的embeddings API是私有模型，无法与RWKV生成的embeddings匹配使用
建议看一下FastGPT项目是否支持使用使用开源LLM作为embeddings

**Comment by chenbe1990** [comment]
@evanstark 有联系方式吗？我也在研究fastgpt如何对接其他大模型

**Comment by chenbe1990** [comment]
我已经成功实现fastgpt对接RWKV生成的embeddings

**Comment by taurusduan** [comment]
> @evanstark有联系方式吗？我一直在研究fastgpt如何对接其他大模型

你好大哥，可以教教我怎么对接这个模型吗？

**Comment by taurusduan** [comment]
> 我已经成功实现fastgpt活塞RWKV生成的嵌入

大哥可以请教一下fastgpt添加RWKV生成的embeddings
