### ISSUE TITLE
运行后，在聊天界面发送任何回复都是回复你好

### ISSUE THREAD

**Issue by koolou** [josStorer/RWKV-Runner#134]
![log](https://github.com/josStorer/RWKV-Runner/assets/349998/80176557-ea06-41e7-8cb5-7102ca50a723)
![WX20230718-161052](https://github.com/josStorer/RWKV-Runner/assets/349998/4b9490ec-e233-45d8-aac6-fcd5baa22027)
在聊天界面发送任何回复都是回复你好，不过续写功能是可以的，使用了 novel 专业写作模型

**Comment by josStorer** [comment]
写作模型不能聊天

**Comment by koolou** [comment]
感谢 更换后可以了
