### ISSUE TITLE
無法再TavernAI中使用

### ISSUE THREAD

**Issue by win10ogod** [josStorer/RWKV-Runner#136]
如何在[TavernAI](https://github.com/TavernAI/TavernAI) 或 [SillyTavern](https://github.com/SillyTavern/SillyTavern)中使用api?

**Comment by flasewazard** [comment]
相同问题，实际上我看runner的cmd里是报说tavern的api get请求有发送到，但是会因为请求下属的/models文件夹所以runner会404，有结果了踢我一脚

**Comment by flasewazard** [comment]
我从别人那边薅了两个项目，还没试过https://github.com/xiaol/TavernAI-RWKV和https://github.com/xiaol/SillyTavern-RWKV 你逝世看？

**Comment by VonKauland** [comment]
![image](https://github.com/josStorer/RWKV-Runner/assets/54017308/ea8aece0-13eb-4a92-86e2-af264db53c2e)
反向代理中填寫http://127.0.0.1:8000/v1後，按Test Message按鈕可以生成一段對話。但是如果按的是Connect按鈕，會提示Endpoint not found.

**Comment by KaJ1L** [comment]
> 我从别人那边薅了两个项目，还没试过[https://github.com/xiaol/TavernAI-RWKV和https://github.com/xiaol/SillyTavern-RWKV](https://github.com/xiaol/TavernAI-RWKV%E5%92%8Chttps://github.com/xiaol/SillyTavern-RWKV) 你逝世看？

可以用的，反代里填上rwkv runner上的api就行了

**Comment by flasewazard** [comment]
> > 我从别人那边薅了两个项目，还没试过[https://github.com/xiaol/TavernAI-RWKV和https://github.com/xiaol/SillyTavern-RWKV](https://github.com/xiaol/TavernAI-RWKV%E5%92%8Chttps://github.com/xiaol/SillyTavern-RWKV) 你逝世看？
> 
> 可以用的，反代里填上rwkv runner上的api就行了

会报错，类似
![@}O@CA~JFQWHVM~%`BE}5`9](https://github.com/josStorer/RWKV-Runner/assets/112845875/01e4777c-a122-4266-bcdb-9476db91d0e3)
这个样子

**Comment by flasewazard** [comment]
> > 我从别人那边薅了两个项目，还没试过[https://github.com/xiaol/TavernAI-RWKV和https://github.com/xiaol/SillyTavern-RWKV](https://github.com/xiaol/TavernAI-RWKV%E5%92%8Chttps://github.com/xiaol/SillyTavern-RWKV) 你逝世看？
> 
> 可以用的，反代里填上rwkv runner上的api就行了

显而易见的就是，会GET这个models，然后就读不到了，我不知道在哪里改请求，可以的话请大佬指点一下

**Comment by josStorer** [comment]
我下版本加一下假的models API

**Comment by josStorer** [comment]
https://github.com/josStorer/RWKV-Runner/releases/tag/v1.4.4

**Comment by flasewazard** [comment]
> https://github.com/josStorer/RWKV-Runner/releases/tag/v1.4.4

感谢，已经可用了

**Comment by flasewazard** [comment]
> 我下版本加一下models API

反馈一下，不知道是没有确认请求的返回还是什么原因，当runner生成较长回复时tavern可能先报错超时，但是能正常收到回复结果，较短回复则无问题

**Comment by LSXAxeller** [comment]
anyone successfully started it ? I tried to launch TavernAI using RWKV Runner AI
using different api urls but no luck, only receive "200 OK" after removing all the "api/v1" from server.js but still not connected

![image](https://github.com/josStorer/RWKV-Runner/assets/56027532/42123005-cd27-4e27-929f-d4920cf7d6c7)

**Comment by josStorer** [comment]
Use this Settings:

![image](https://github.com/josStorer/RWKV-Runner/assets/13366013/adcdc206-6c2f-437e-a047-29b7b8ac0cad)
