### ISSUE TITLE
在Windows系统运行闪退

### ISSUE THREAD

**Issue by gou-zai** [josStorer/RWKV-Runner#138]
Windows系统版本：
Windows 11 专业版
版本	22H2
安装日期	‎2022/‎10/‎16
操作系统版本	22631.1906
体验	Windows Feature Experience Pack 1000.22646.1000.0

软件版本：
v1.3.9

问题复现：
浏览器下载完成后，双击打开安装包，点击运行按钮会闪退，其他操作也有概率闪退

**Comment by josStorer** [comment]
exe程序本身闪退？直接消失吗？

**Comment by josStorer** [comment]
试试参考 [这个](https://github.com/josStorer/RWKV-Runner/blob/master/README_ZH.md#%E5%A6%82%E6%9E%9Cwindows-defender%E8%AF%B4%E8%BF%99%E6%98%AF%E4%B8%80%E4%B8%AA%E7%97%85%E6%AF%92%E4%BD%A0%E5%8F%AF%E4%BB%A5%E5%B0%9D%E8%AF%95%E4%B8%8B%E8%BD%BDv137_winzip%E7%84%B6%E5%90%8E%E8%AE%A9%E5%85%B6%E8%87%AA%E5%8A%A8%E6%9B%B4%E6%96%B0%E5%88%B0%E6%9C%80%E6%96%B0%E7%89%88%E6%88%96%E6%B7%BB%E5%8A%A0%E4%BF%A1%E4%BB%BB-windows-security---virus--threat-protection---manage-settings---exclusions---add-or-remove-exclusions---add-an-exclusion---folder---rwkv-runner)

添加到信任

**Comment by gou-zai** [comment]
是的

**Comment by gou-zai** [comment]
我默认并未使用Windows自带的防护程序，采用的是火绒和360，两个软件均已设置软件所在文件夹和文件信任，但问题依然存在

**Comment by josStorer** [comment]
加下qq: guaiwolou
远程看一下

**Comment by gou-zai** [comment]
qq好像只能查找qq号，搜索guaiwolou无结果

**Comment by josStorer** [comment]
1466587594

**Comment by Dhj653** [comment]
你好，我点击安装python依赖弹出窗口后就闪退了，再点击运行也是这样。
