### ISSUE TITLE
macos intel芯片 运行报错关于fastapi

### ISSUE THREAD

**Issue by ruolan** [josStorer/RWKV-Runner#140]
macos 13.4.1 (c) (22F770820d)
懒人包首次安装，解决了python路径问题之后，

点击运行报错

界面报错内容
<img width="1024" alt="image" src="https://github.com/josStorer/RWKV-Runner/assets/7134844/0d68dc01-2b13-47ee-8e9d-5a32a53a6896">

DepCheck Error: Traceback (most recent call last): File "/Users/ruolan/Downloads/RMKV/RWKV-Runner.app/Contents/MacOS/../../.././backend-python/dep_check.py", line 11, in <module> import fastapi File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fastapi/__init__.py", line 7, in <module> from .applications import FastAPI as FastAPI File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fastapi/applications.py", line 4, in <module> from fastapi import routing File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fastapi/routing.py", line 23, in <module> from fastapi.dependencies.models import Dependant File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fastapi/dependencies/models.py", line 3, in <module> from fastapi.security.base import SecurityBase File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fastapi/security/__init__.py", line 1, in <module> from .api_key import APIKeyCookie as APIKeyCookie File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fastapi/security/api_key.py", line 3, in <module> from fastapi.openapi.models import APIKey, APIKeyIn File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fastapi/openapi/models.py", line 103, in <module> class Schema(BaseModel): File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/main.py", line 292, in __new__ cls.__signature__ = ClassAttribute('__signature__', generate_model_signature(cls.__init__, fields, config)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/utils.py", line 258, in generate_model_signature merged_params[param_name] = Parameter( ^^^^^^^^^^ File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/inspect.py", line 2725, in __init__ raise ValueError('{!r} is not a valid parameter name'.format(name)) ValueError: 'not' is not a valid parameter name

点击安装后，终端显示内容
Last login: Sat Jul 29 12:58:26 on ttys004
cd /Users/ruolan/Downloads/RMKV/RWKV-Runner.app/Contents/MacOS/../../../ && /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 -m pip install -r ./backend-python/requirements_without_cyac.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
➜  ~ cd /Users/ruolan/Downloads/RMKV/RWKV-Runner.app/Contents/MacOS/../../../ && /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 -m pip install -r ./backend-python/requirements_without_cyac.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: torch in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 1)) (2.0.1)
Requirement already satisfied: torchvision in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 2)) (0.15.2)
Requirement already satisfied: torchaudio in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 3)) (2.0.2)
Requirement already satisfied: rwkv in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 4)) (0.8.0)
Requirement already satisfied: langchain in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 5)) (0.0.234)
Requirement already satisfied: fastapi in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 6)) (0.75.2)
Requirement already satisfied: uvicorn in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 7)) (0.19.0)
Requirement already satisfied: sse-starlette in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 8)) (1.6.1)
Requirement already satisfied: pydantic in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 9)) (1.9.2)
Requirement already satisfied: psutil in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 10)) (5.9.5)
Requirement already satisfied: gputil in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 11)) (1.4.0)
Requirement already satisfied: tiktoken in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 12)) (0.4.0)
Requirement already satisfied: ftfy in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 13)) (6.1.1)
Requirement already satisfied: lm-dataformat in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 14)) (0.0.20)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 15)) (1.25.1)
Requirement already satisfied: tokenizers in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 16)) (0.13.3)
Requirement already satisfied: tqdm in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 17)) (4.65.0)
Requirement already satisfied: filelock in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from torch->-r ./backend-python/requirements_without_cyac.txt (line 1)) (3.12.2)
Requirement already satisfied: typing-extensions in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from torch->-r ./backend-python/requirements_without_cyac.txt (line 1)) (4.5.0)
Requirement already satisfied: sympy in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from torch->-r ./backend-python/requirements_without_cyac.txt (line 1)) (1.12)
Requirement already satisfied: networkx in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from torch->-r ./backend-python/requirements_without_cyac.txt (line 1)) (3.1)
Requirement already satisfied: jinja2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from torch->-r ./backend-python/requirements_without_cyac.txt (line 1)) (3.1.2)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from torchvision->-r ./backend-python/requirements_without_cyac.txt (line 2)) (2.29.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from torchvision->-r ./backend-python/requirements_without_cyac.txt (line 2)) (10.0.0)
Requirement already satisfied: PyYAML>=5.4.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from langchain->-r ./backend-python/requirements_without_cyac.txt (line 5)) (6.0)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from langchain->-r ./backend-python/requirements_without_cyac.txt (line 5)) (1.4.49)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from langchain->-r ./backend-python/requirements_without_cyac.txt (line 5)) (3.8.4)
Requirement already satisfied: dataclasses-json<0.6.0,>=0.5.7 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from langchain->-r ./backend-python/requirements_without_cyac.txt (line 5)) (0.5.9)
Requirement already satisfied: langsmith<0.0.6,>=0.0.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from langchain->-r ./backend-python/requirements_without_cyac.txt (line 5)) (0.0.5)
Requirement already satisfied: numexpr<3.0.0,>=2.8.4 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from langchain->-r ./backend-python/requirements_without_cyac.txt (line 5)) (2.8.4)
Requirement already satisfied: openapi-schema-pydantic<2.0,>=1.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from langchain->-r ./backend-python/requirements_without_cyac.txt (line 5)) (1.2.4)
Requirement already satisfied: tenacity<9.0.0,>=8.1.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from langchain->-r ./backend-python/requirements_without_cyac.txt (line 5)) (8.2.2)
Requirement already satisfied: starlette==0.17.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from fastapi->-r ./backend-python/requirements_without_cyac.txt (line 6)) (0.17.1)
Requirement already satisfied: anyio<4,>=3.0.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from starlette==0.17.1->fastapi->-r ./backend-python/requirements_without_cyac.txt (line 6)) (3.7.1)
Requirement already satisfied: click>=7.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from uvicorn->-r ./backend-python/requirements_without_cyac.txt (line 7)) (8.1.5)
Requirement already satisfied: h11>=0.8 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from uvicorn->-r ./backend-python/requirements_without_cyac.txt (line 7)) (0.14.0)
Requirement already satisfied: regex>=2022.1.18 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from tiktoken->-r ./backend-python/requirements_without_cyac.txt (line 12)) (2023.6.3)
Requirement already satisfied: wcwidth>=0.2.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from ftfy->-r ./backend-python/requirements_without_cyac.txt (line 13)) (0.2.6)
Requirement already satisfied: jsonlines in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from lm-dataformat->-r ./backend-python/requirements_without_cyac.txt (line 14)) (3.1.0)
Requirement already satisfied: ujson in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from lm-dataformat->-r ./backend-python/requirements_without_cyac.txt (line 14)) (5.8.0)
Requirement already satisfied: zstandard in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from lm-dataformat->-r ./backend-python/requirements_without_cyac.txt (line 14)) (0.21.0)
Requirement already satisfied: attrs>=17.3.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain->-r ./backend-python/requirements_without_cyac.txt (line 5)) (23.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain->-r ./backend-python/requirements_without_cyac.txt (line 5)) (3.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain->-r ./backend-python/requirements_without_cyac.txt (line 5)) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain->-r ./backend-python/requirements_without_cyac.txt (line 5)) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain->-r ./backend-python/requirements_without_cyac.txt (line 5)) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain->-r ./backend-python/requirements_without_cyac.txt (line 5)) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain->-r ./backend-python/requirements_without_cyac.txt (line 5)) (1.3.1)
Requirement already satisfied: marshmallow<4.0.0,>=3.3.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from dataclasses-json<0.6.0,>=0.5.7->langchain->-r ./backend-python/requirements_without_cyac.txt (line 5)) (3.19.0)
Requirement already satisfied: marshmallow-enum<2.0.0,>=1.5.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from dataclasses-json<0.6.0,>=0.5.7->langchain->-r ./backend-python/requirements_without_cyac.txt (line 5)) (1.5.1)
Requirement already satisfied: typing-inspect>=0.4.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from dataclasses-json<0.6.0,>=0.5.7->langchain->-r ./backend-python/requirements_without_cyac.txt (line 5)) (0.8.0)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->torchvision->-r ./backend-python/requirements_without_cyac.txt (line 2)) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->torchvision->-r ./backend-python/requirements_without_cyac.txt (line 2)) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->torchvision->-r ./backend-python/requirements_without_cyac.txt (line 2)) (2023.5.7)
Requirement already satisfied: greenlet!=0.4.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from SQLAlchemy<3,>=1.4->langchain->-r ./backend-python/requirements_without_cyac.txt (line 5)) (2.0.2)
Requirement already satisfied: MarkupSafe>=2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from jinja2->torch->-r ./backend-python/requirements_without_cyac.txt (line 1)) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from sympy->torch->-r ./backend-python/requirements_without_cyac.txt (line 1)) (1.3.0)
Requirement already satisfied: sniffio>=1.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from anyio<4,>=3.0.0->starlette==0.17.1->fastapi->-r ./backend-python/requirements_without_cyac.txt (line 6)) (1.3.0)
Requirement already satisfied: packaging>=17.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from marshmallow<4.0.0,>=3.3.0->dataclasses-json<0.6.0,>=0.5.7->langchain->-r ./backend-python/requirements_without_cyac.txt (line 5)) (23.1)
Requirement already satisfied: mypy-extensions>=0.3.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from typing-inspect>=0.4.0->dataclasses-json<0.6.0,>=0.5.7->langchain->-r ./backend-python/requirements_without_cyac.txt (line 5)) (1.0.0)
➜  RMKV

**Comment by josStorer** [comment]
https://github.com/tiangolo/fastapi/issues/5048

检查下pydantic版本，尝试手动升级到新版

**Comment by ruolan** [comment]
已更新到最新版本，pydantic版本1.9.2，报错仍存在

**Comment by josStorer** [comment]
那试试也升级fastapi版本

**Comment by josStorer** [comment]
最新版已调整代码适配最新的包
