### ISSUE TITLE
Macos Intel平台一直卡在Could not build wheels for cyac, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by duxsheng** [josStorer/RWKV-Runner#143]
Building wheels for collected packages: cyac
  Building wheel for cyac (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for cyac (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [49 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-cpython-311
      creating build/lib.macosx-10.9-universal2-cpython-311/cyac
      copying lib/cyac/version.py -> build/lib.macosx-10.9-universal2-cpython-311/cyac
      copying lib/cyac/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/cyac
      running egg_info
      writing cyac.egg-info/PKG-INFO
      writing dependency_links to cyac.egg-info/dependency_links.txt
      writing requirements to cyac.egg-info/requires.txt
      writing top-level names to cyac.egg-info/top_level.txt
      reading manifest file 'cyac.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '__pycache__' found anywhere in distribution
      writing manifest file 'cyac.egg-info/SOURCES.txt'
      copying lib/cyac/ac.pxd -> build/lib.macosx-10.9-universal2-cpython-311/cyac
      copying lib/cyac/ac.pyx -> build/lib.macosx-10.9-universal2-cpython-311/cyac
      copying lib/cyac/trie.pxd -> build/lib.macosx-10.9-universal2-cpython-311/cyac
      copying lib/cyac/trie.pyx -> build/lib.macosx-10.9-universal2-cpython-311/cyac
      copying lib/cyac/unicode_portability.cpp -> build/lib.macosx-10.9-universal2-cpython-311/cyac
      copying lib/cyac/utf8.pxd -> build/lib.macosx-10.9-universal2-cpython-311/cyac
      copying lib/cyac/utf8.pyx -> build/lib.macosx-10.9-universal2-cpython-311/cyac
      copying lib/cyac/util.c -> build/lib.macosx-10.9-universal2-cpython-311/cyac
      copying lib/cyac/util.pxd -> build/lib.macosx-10.9-universal2-cpython-311/cyac
      copying lib/cyac/util.pyx -> build/lib.macosx-10.9-universal2-cpython-311/cyac
      copying lib/cyac/xstring.pxd -> build/lib.macosx-10.9-universal2-cpython-311/cyac
      copying lib/cyac/xstring.pyx -> build/lib.macosx-10.9-universal2-cpython-311/cyac
      running build_ext
      building 'cyac.util' extension
      creating build/temp.macosx-10.9-universal2-cpython-311
      creating build/temp.macosx-10.9-universal2-cpython-311/lib
      creating build/temp.macosx-10.9-universal2-cpython-311/lib/cyac
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c lib/cyac/util.c -o build/temp.macosx-10.9-universal2-cpython-311/lib/cyac/util.o
      clang -bundle -undefined dynamic_lookup -arch arm64 -arch x86_64 -g build/temp.macosx-10.9-universal2-cpython-311/lib/cyac/util.o -o build/lib.macosx-10.9-universal2-cpython-311/cyac/util.cpython-311-darwin.so
      building 'cyac.utf8' extension
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c lib/cyac/utf8.cpp -o build/temp.macosx-10.9-universal2-cpython-311/lib/cyac/utf8.o
      clang++ -bundle -undefined dynamic_lookup -arch arm64 -arch x86_64 -g build/temp.macosx-10.9-universal2-cpython-311/lib/cyac/utf8.o -o build/lib.macosx-10.9-universal2-cpython-311/cyac/utf8.cpython-311-darwin.so
      building 'cyac.xstring' extension
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Ilib/cyac -I/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c lib/cyac/xstring.cpp -o build/temp.macosx-10.9-universal2-cpython-311/lib/cyac/xstring.o
      lib/cyac/xstring.cpp:2043:31: error: declaration of '_PyUnicode_ToLowerFull' has a different language linkage
      __PYX_EXTERN_C DL_IMPORT(int) _PyUnicode_ToLowerFull(Py_UCS4, Py_UCS4 *); /*proto*/
                                    ^
      /Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/cpython/unicodeobject.h:1078:17: note: previous declaration is here
      PyAPI_FUNC(int) _PyUnicode_ToLowerFull(
                      ^
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cyac
Failed to build cyac
ERROR: Could not build wheels for cyac, which is required to install pyproject.toml-based projects
➜  RWKV-Runner

Python版本：
![image](https://github.com/josStorer/RWKV-Runner/assets/52036609/93e4d0ac-c408-4670-991c-15bcb040dc1a)

**Comment by josStorer** [comment]
cyac需要你安装了python-dev包才能正常编译

见linux安装示例：https://github.com/josStorer/RWKV-Runner/blob/master/build/linux/Readme_Install.txt#L13

你可以选择安装这个requirements：https://github.com/josStorer/RWKV-Runner/blob/master/backend-python/requirements_without_cyac.txt

这个不安装cyac，是mac下的默认安装方式

**Comment by hrzhu** [comment]
他已经有 python 的头文件了。
这个似乎是 cyac 的问题 
https://github.com/nppoly/cyac/issues/19
把 requirements.txt 里面的 cyac 从 1.7 改成 1.9 之后能编译安装成功

**Comment by josStorer** [comment]
最新版已将cyac升级到1.9
