### ISSUE TITLE
可以实现多个人同时调用同一个RWKV-Runner的API吗

### ISSUE THREAD

**Issue by mcpanl** [josStorer/RWKV-Runner#146]
可以实现多个人同时调用同一个RWKV-Runner的API吗，内部机制是可以同时进行的，还是内部有一个队列按照顺序给用户返回内容的呢

**Comment by josStorer** [comment]
可以同时调用，逐个处理，但不保证处理顺序

**Comment by josStorer** [comment]
可以试试配置页面切换到WebGPU策略, 支持并行
