### ISSUE TITLE
训练提示内存不足的问题

### ISSUE THREAD

**Issue by wumeng874** [josStorer/RWKV-Runner#149]
![QQ截图20230803235816](https://github.com/josStorer/RWKV-Runner/assets/141240820/ec769286-571e-4b5a-8a98-97b8b32623b9)
![QQ截图20230804000109](https://github.com/josStorer/RWKV-Runner/assets/141240820/aaaa4446-f461-4f17-999e-69c49325a705)

请问如何解决？

**Comment by josStorer** [comment]
.wslconfig配置了吗，分配给虚拟机的增加一下，以及swap空间也增加
