### ISSUE TITLE
自定義CUDA算子錯誤

### ISSUE THREAD

**Issue by win10ogod** [josStorer/RWKV-Runner#152]
您好,這要怎麼解決?

```
ninja: build stopped: subcommand failed.
Error building extension 'wkv_cuda_v1'
```

**Comment by josStorer** [comment]
如果是linux，需要安装好c++编译器，ninja，python相关依赖，以及cuda驱动和库

如果windows，需要安装好vc++编译器，ninja, python相关依赖，cuda驱动和cuda库，并为相关cuda库和编译器，正确配置好环境变量
