### ISSUE TITLE
MetaGPT使用api时报错422

### ISSUE THREAD

**Issue by lujunjiehhh** [josStorer/RWKV-Runner#153]
报错
![image](https://github.com/josStorer/RWKV-Runner/assets/49628289/1bd43dce-552f-4d39-8a4d-507ed2be2db9)
抓包提示如下
![image](https://github.com/josStorer/RWKV-Runner/assets/49628289/7b6e1486-2a0a-494e-99ac-9ec410d359f8)
报错信息如下
![image](https://github.com/josStorer/RWKV-Runner/assets/49628289/a8db9d2f-df58-4861-a8d0-af00aec2d76a)

**Comment by josStorer** [comment]
目前版本stop不能传null，下版本会支持
