### ISSUE TITLE
linux上wails build失败

### ISSUE THREAD

**Issue by elven2016** [josStorer/RWKV-Runner#158]
按照知道安装了go和wails。执行wails build报错，无法构建
 wails build
Wails CLI v2.5.1

# Build Options

Platform(s)        | linux/amd64
Compiler           | /usr/local/go/bin/go
Skip Bindings      | false
Build Mode         | production
Frontend Directory | /home/elven/RWKV-Next-Web/RWKV-Runner/frontend
Obfuscated         | false
Skip Frontend      | false
Compress           | false
Package            | true
Clean Bin Dir      | false
LDFlags            |
Tags               | []
Race Detector      | false

# Building target: linux/amd64

  • Generating bindings:
Done.
  • Installing frontend dependencies:
Done.
  • Compiling frontend:

    > frontend@0.0.0 build
    > tsc && vite build

    src/pages/Train.tsx(10,3): error TS2305: Module '"../../wailsjs/go/backend_golang/App"' has no exported member 'WslCommand'.
    src/pages/Train.tsx(11,3): error TS2305: Module '"../../wailsjs/go/backend_golang/App"' has no exported member 'WslEnable'.
    src/pages/Train.tsx(12,3): error TS2305: Module '"../../wailsjs/go/backend_golang/App"' has no exported member 'WslInstallUbuntu'.
    src/pages/Train.tsx(13,3): error TS2305: Module '"../../wailsjs/go/backend_golang/App"' has no exported member 'WslIsEnabled'.
    src/pages/Train.tsx(14,3): error TS2305: Module '"../../wailsjs/go/backend_golang/App"' has no exported member 'WslStart'.
    src/pages/Train.tsx(15,3): error TS2305: Module '"../../wailsjs/go/backend_golang/App"' has no exported member 'WslStop'.
    src/pages/Train.tsx(333,16): error TS7006: Parameter 'e' implicitly has an 'any' type.
    src/pages/Train.tsx(348,14): error TS7006: Parameter 'e' implicitly has an 'any' type.

  ERROR   exit status 2

  ERROR   exit status 2
 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony

**Comment by josStorer** [comment]
执行这三行命令
https://github.com/josStorer/RWKV-Runner/blob/master/.github/workflows/release.yml#L86-L88

**Comment by elven2016** [comment]
> 执行这三行命令，再编译 https://github.com/josStorer/RWKV-Runner/blob/master/.github/workflows/release.yml#L86-L88

感谢已经可以正常运行编译了
wails build
Wails CLI v2.5.1


# Build Options

Platform(s)        | linux/amd64
Compiler           | /usr/local/go/bin/go
Skip Bindings      | false
Build Mode         | production
Frontend Directory | /home/elven/RWKV-Next-Web/RWKV-Runner/frontend
Obfuscated         | false
Skip Frontend      | false
Compress           | false
Package            | true
Clean Bin Dir      | false
LDFlags            |
Tags               | []
Race Detector      | false

# Building target: linux/amd64

  • Generating bindings:
Done.
  • Installing frontend dependencies:
Done.
  • Compiling frontend:
Done.
  • Compiling application:
Done.
  • Packaging application:
Done.
Built '/home/elven/RWKV-Next-Web/RWKV-Runner/build/bin/RWKV-Runner' in 25.789s.
