### ISSUE TITLE
运行模型提示需要python依赖，点击下载弹几个黑窗口后就没反应了，再点还是提示要下载依赖，目录没有中文

### ISSUE THREAD

**Issue by Juniy** [josStorer/RWKV-Runner#16]

**Comment by josStorer** [comment]
黑窗有内容吗，提供截图，截不了的话录个屏

**Comment by Juniy** [comment]
在系统path中添加python脚本目录后这个问题解决了，接着又出现错误：
![image](https://github.com/josStorer/RWKV-Runner/assets/11728986/7ca04354-8e86-41fa-8841-e6236c7d40bd)

**Comment by josStorer** [comment]
往上滚动给完整截图

**Comment by Juniy** [comment]
![image](https://github.com/josStorer/RWKV-Runner/assets/11728986/b649de6e-e0e4-476f-babc-b20174b38049)

**Comment by josStorer** [comment]
#4 #17 #9
参考这三个，同样的问题

**Comment by Juniy** [comment]
![image](https://github.com/josStorer/RWKV-Runner/assets/11728986/929702e4-41fc-4957-bc45-af0e0d1e15f8)
没有要求torch版本，默认装的是2的

**Comment by Juniy** [comment]
torch删了重装好了
![image](https://github.com/josStorer/RWKV-Runner/assets/11728986/58c07b1c-161f-4fb7-9e35-6ebbc5e98cc8)

**Comment by Juniy** [comment]
感谢指导！
