### ISSUE TITLE
【功能】增加 AI00 RWKV Server 支持

### ISSUE THREAD

**Issue by PJ-568** [josStorer/RWKV-Runner#160]
[`AI00 RWKV Server`](https://github.com/cgisky1980/ai00_rwkv_server)是一个基于[`RWKV`模型](https://github.com/BlinkDL/ChatRWKV)的推理API服务器。

支持`VULKAN`推理加速，可以在所有支持`VULKAN`的GPU上运行。不用N卡，A卡甚至集成显卡都可加速。

无需臃肿的`pytorch`、`CUDA`等运行环境，小巧身材，开箱即用！

---

[AI00 RWKV Server](https://github.com/cgisky1980/ai00_rwkv_server) 提供了预编译程序，这应该能降低集成难度。

**Comment by josStorer** [comment]
在做，今天会发

**Comment by josStorer** [comment]
https://github.com/josStorer/RWKV-Runner/releases/tag/v1.4.4
