### ISSUE TITLE
 mac 点运行，只有按钮显示启动中，然后就又回到“运行”，没有命令窗口可以看哪里出问题？

### ISSUE THREAD

**Issue by lecykx** [josStorer/RWKV-Runner#161]
您好， mac 点运行，只有按钮显示启动中，然后就又回到“运行”，没有命令窗口可以看哪里出问题？

**Comment by josStorer** [comment]
在终端执行一下`which python3`，将路径填到设置里的自定义python路径，然后再试试

**Comment by dorisDC** [comment]
有相同的問題，已經用自訂義了，但還是沒有成功⋯⋯
看終端機是說

cd: too many arguments

**Comment by josStorer** [comment]
那估计是路径有空格, 不要有空格, 或者配置页面切到WebGPU模式, 这个模式下不需要用python
