### ISSUE TITLE
Windows下怎么从源码编译并运行

### ISSUE THREAD

**Issue by longzou** [josStorer/RWKV-Runner#162]
下载的Exe预制包总是提示有病毒，而且在实际过程中，也需要从源码中进行运行，如何运行？

**Comment by longzou** [comment]
编译好了，，需要先安装wails，但在运行过程，点某几个菜单或功能时，会出现一片都是白色的界面，，，如点配置时，然后就没有办法进行后续操作了。。

**Comment by josStorer** [comment]
可以参考此说明添加目录到信任，避免提示病毒

https://github.com/josStorer/RWKV-Runner/issues/69#issuecomment-1639202830

**Comment by longzou** [comment]
这个自己编译出来的与你编译出来的有什么区别吗？？还是说有哪些参数需要配置的？

**Comment by josStorer** [comment]
没区别

**Comment by longzou** [comment]
所以，有什么办法让它们编译出来是一样的效果呢，，我编译出来后，EXE文件有22.5 MB (23,615,488 字节)，，下载下来的却只有11M左右，，

**Comment by josStorer** [comment]
github上的版本使用了upx压缩

**Comment by linkerlin** [comment]
既然mcafee都说有病毒，那就是有。还是请重新制作下win下的可执行文件吧。

**Comment by josStorer** [comment]
@linkerlin 

> 既然mcafee都说有病毒，那就是有。

mcafee是业界知名垃圾杀毒软件，本软件并没有病毒。

本软件以MIT协议开源，且使用github workflow编译，代码与编译流程均完全公开，不存在由我添加后门的风险。

你可以上传 www.virscan.org，用多种杀毒引擎检测，确认无毒。

此外本项目readme说明部分也给出了一个，在报毒情况下，可以尝试使用的版本，如有顾虑请尝试此版本：
![image](https://github.com/josStorer/RWKV-Runner/assets/13366013/1fa2196e-86bc-4b12-ae66-c4c9978ec3df)

**Comment by linkerlin** [comment]
> @linkerlin
> 
> > 既然mcafee都说有病毒，那就是有。
> 
> mcafee是业界知名垃圾杀毒软件，本软件并没有病毒。
> 
> 本软件以MIT协议开源，且使用github workflow编译，代码与编译流程均完全公开，不存在由我添加后门的风险。
> 
> 你可以上传 [www.virscan.org](http://www.virscan.org), 用多种杀毒引擎检测，确认无毒。
> 
> 此外本项目readme说明部分也给出了一个，在报毒情况下，可以尝试使用的版本，如有顾虑请尝试此版本： ![image](https://user-images.githubusercontent.com/13366013/262071559-1fa2196e-86bc-4b12-ae66-c4c9978ec3df.png)

抱歉我没表达清楚，我的意思是如果知名杀毒软件说有病毒，还是要重视下。
