### ISSUE TITLE
Failed to switch model - Failed to enable custom CUDA kernel, ninja is required to load C++ extensions.

### ISSUE THREAD

**Issue by LSXAxeller** [josStorer/RWKV-Runner#166]
I receive this error whenever I try to load model using the new strategy CUDA-Beta in version 1.4.4

"Failed to switch model - Failed to enable custom CUDA kernel, ninja is required to load C++ extensions. You may be using the CPU version of PyTorch, please reinstall PyTorch with CUDA. Or if you are using a custom Python interpreter, you must compile the CUDA kernel by yourself or disable Custom CUDA kernel acceleration."

and In console:

`--- 0.5215103626251221 seconds ---
←[32mINFO←[0m:     Started server process [←[36m10124←[0m]
←[32mINFO←[0m:     Waiting for application startup.
torch found: E:\Others\Native\TextGeneration\RWKV Runner\py310\Lib\site-packages\torch\lib
torch set
←[32mINFO←[0m:     Application startup complete.
←[32mINFO←[0m:     Uvicorn running on ←[1mhttp://0.0.0.0:8000←[0m (Press CTRL+C to quit)
←[32mINFO←[0m:     127.0.0.1:53592 - "←[1mOPTIONS /update-config HTTP/1.1←[0m" ←[32m200 OK←[0m
max_tokens=4100 temperature=1.0 top_p=0.3 presence_penalty=0.0 frequency_penalty=1.0
←[32mINFO←[0m:     127.0.0.1:53592 - "←[1mPOST /update-config HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     127.0.0.1:53592 - "←[1mGET / HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     127.0.0.1:53592 - "←[1mGET /status HTTP/1.1←[0m" ←[32m200 OK←[0m
max_tokens=4100 temperature=1.0 top_p=0.3 presence_penalty=0.0 frequency_penalty=1.0
←[32mINFO←[0m:     127.0.0.1:53592 - "←[1mPOST /update-config HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     127.0.0.1:53592 - "←[1mOPTIONS /switch-model HTTP/1.1←[0m" ←[32m200 OK←[0m
E:\Others\Native\TextGeneration\RWKV Runner\py310\Lib\site-packages\_distutils_hack\__init__.py:18: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
  warnings.warn(
E:\Others\Native\TextGeneration\RWKV Runner\py310\Lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Using E:\Others\Native\TextGeneration\RWKV Runner\backend-python as PyTorch extensions root...
Ninja is required to load C++ extensions
INFO:     127.0.0.1:53592 - "POST /switch-model HTTP/1.1" 500 Internal Server Error`

I have installed PyTorch 1.13.1+cu117 and ninja and VS2022 and C++ Build Tools
the GPU is RTX 3060 12GB

![image_2023-08-19_134320824](https://github.com/josStorer/RWKV-Runner/assets/56027532/27d1eef9-4322-48cd-9626-41a741e6ee54)

**Comment by josStorer** [comment]
Currently, you need to compile CUDA-Beta yourself. I haven't included the compilation files as it's only successfully compiled on linux.

**Comment by LSXAxeller** [comment]
So it's not tested yet on windows ? is there's any tutorial I can follow to compile ? didn't interacted with CUDA yet

**Comment by LXY1226** [comment]
https://github.com/BlinkDL/RWKV-CUDA 👀

**Comment by LXY1226** [comment]
I compiled it for windows. It works (without many boost?) and I'll put it into another issue.  
It may a good option for embed that kernel into windows binary?

**Comment by josStorer** [comment]
The latest version has resolved this issue.
