### ISSUE TITLE
AMD显卡仍存在乱码问题

### ISSUE THREAD

**Issue by huimou9** [josStorer/RWKV-Runner#167]
![Snipaste_2023-08-20_01-06-52](https://github.com/josStorer/RWKV-Runner/assets/64821389/63280844-40d6-4578-914e-d08d422995df)
使用的是7b小说模型，专业和均衡都是显示乱码

**Comment by huimou9** [comment]
使用的驱动是最新版

**Comment by josStorer** [comment]
只支持world模型
