### ISSUE TITLE
【咨询】求ebeddings的维度是多少啊？

### ISSUE THREAD

**Issue by taurusduan** [josStorer/RWKV-Runner#169]
ebeddings的维度不一样，导致生成的知识库卡住，默认openAI的text-embedding-ada-002，维度是1536，不知道ebeddings的纬度是？

**Comment by josStorer** [comment]
不同的模型维度不一样，同一embedding应用场景要保证使用同一个模型

**Comment by taurusduan** [comment]
> 不同的模型维度不一样，同一embedding应用场景要保证使用同一个模型，例如用同一个模型生成知识库，并继续用此模型进行知识库查询
> 
> 此外，RWKV目前暂未提供专用的embedding模型，目前的embedding API使用RWKV推理的隐藏状态参数，目前中文较好的专用embedding模型推荐m3e

好的，谢谢啊
