### ISSUE TITLE
Unexpected Behavior: Training Continues Beyond Specified Epochs

### ISSUE THREAD

**Issue by xAlpacas** [josStorer/RWKV-Runner#170]
I am encountering an unexpected behavior while training the RWKV 14B language model using the provided `train.py` script. The training process continues beyond the specified number of epochs, even though I've set `--epoch_count` to 8 and `--epoch_steps` to 1000. The training process is currently at epoch 1009.

**Code Context:**

I'm using the following command to initiate the training:

```py
import os


def run_training():
    load_model = "/home/dev/Workspaces/runner/models/RWKV-4-Raven-14B-v12-Eng98%-Other2%-20230523-ctx8192.pth"
    proj_dir = "out"
    data_file = (
        "/home/dev/Workspaces/runner/finetune/data/notes/101_Formulaic_Alphas_2015.txt"
    )
    data_type = "utf-8"
    micro_bsz = 11
    epoch_count = 8
    epoch_steps = 1000
    devices = "1"
    strategy = "deepspeed_stage_2_offload"
    grad_cp = 1

    command = (
        f'python train.py --load_model "{load_model}" --wandb "" --proj_dir "{proj_dir}" '
        f'--data_file "{data_file}" --data_type "{data_type}" --vocab_size 0 '
        f"--ctx_len 128 --epoch_steps {epoch_steps} --epoch_count {epoch_count} --epoch_begin 0 --epoch_save 10 "
        f"--micro_bsz {micro_bsz} --n_layer 12 --n_embd 768 --pre_ffn 0 --head_qk 0 "
        f"--lr_init 1e-4 --lr_final 1e-4 --warmup_steps 0 --beta1 0.9 --beta2 0.99 --adam_eps 1e-8 "
        f'--accelerator gpu --devices "{devices}" --precision bf16 --strategy "{strategy}" --grad_cp {grad_cp}'
    )

    os.system(command)


if __name__ == "__main__":
    run_training()
```

**Expected Behavior:**

I expected the training process to stop after completing 8 epochs, with each epoch consisting of 1000 steps. However, the training process is continuing beyond this point, and I'm unsure why.

**Troubleshooting Steps Taken:**

1. I reviewed the provided `train.py` script, and I couldn't identify any specific issues that might be causing this behavior.
2. I verified the data loader's behavior and ensured that it's aligned with the expected number of steps per epoch.
3. I double-checked the checkpoint loading process, and it appears to be functioning correctly.
4. I confirmed that there are no early stopping criteria implemented in the codebase.

**Environment:**

- Python version: 3.10.12
- PyTorch version: 1.13.1
- PyTorch Lightning version: 1.9.5
- GPU: NVIDIA GeForce RTX 3060 12GB
- CPU: AMD Ryzen 7 3700X 8-Core Processor

**Additional Context:**

I'm training the model using a TXT file a,d I'm unsure if that affects the training process. I also had a lot of remarks about the ridiculous lose rate the model is training at, I'm new to all this so I don't fully comprehend the details

**Current Output**
```shell
  | Name   | Type       | Params
--------------------------------------
0 | emb    | Embedding  | 96.0 K
1 | blocks | ModuleList | 92.1 M
2 | ln_out | LayerNorm  | 1.5 K 
3 | head   | Linear     | 96.0 K
--------------------------------------
92.3 M    Trainable params
0         Non-trainable params
92.3 M    Total params
369.236   Total estimated model params size (MB)
Epoch 0:   0%|                                         | 0/1000 [00:00<?, ?it/s]
{'zero_allow_untested_optimizer': True, 'zero_optimization': {'stage': 2, 'contiguous_gradients': True, 'overlap_comm': True, 'allgather_partitions': True, 'reduce_scatter': True, 'allgather_bucket_size': 200000000, 'reduce_bucket_size': 200000000, 'sub_group_size': 1000000000000, 'offload_optimizer': {'device': 'cpu', 'nvme_path': '/local_nvme', 'buffer_count': 4, 'pin_memory': False}}, 'activation_checkpointing': {'partition_activations': False, 'cpu_checkpointing': False, 'contiguous_memory_optimization': False, 'synchronize_checkpoint_boundary': False}, 'aio': {'block_size': 1048576, 'queue_depth': 8, 'single_submit': False, 'overlap_events': True, 'thread_count': 1}, 'gradient_accumulation_steps': 1, 'train_micro_batch_size_per_gpu': 8, 'gradient_clipping': 1.0, 'bf16': {'enabled': True}}

Epoch 590:  44%|████████▎          | 438/1000 [02:18<02:57,  3.17it/s, loss=0.058, lr=0.0001, REAL it/s=3.200, Kt/s=3.280]
Epoch 1013:  94%|███████████████▉ | 935/1000 [05:11<00:21,  3.00it/s, loss=0.0574, lr=0.0001, REAL it/s=2.980, Kt/s=3.050]
```

**Comment by josStorer** [comment]
yes, it's a bug

**Comment by xAlpacas** [comment]
Thank you for your quick response! I appreciate your confirmation that this is indeed a bug. Could you please provide some additional details about the nature of the bug and whether there's a plan to address it?

We're kinda playing on time right now so that'll be greatly appreciated

**Comment by josStorer** [comment]
change https://github.com/josStorer/RWKV-Runner/blob/master/finetune/lora/train.py#L187
`args.max_epochs = -1` to `args.max_epochs = args.epoch_count`

**Comment by josStorer** [comment]
https://github.com/josStorer/RWKV-Runner/releases/tag/v1.4.5
