### ISSUE TITLE
API Completion JSON Response

### ISSUE THREAD

**Issue by LSXAxeller** [josStorer/RWKV-Runner#171]
I am using requests library to send a prompt using requests.post but the response can't be parsed using JSON library like in cmd window
But when I comment the JSON parse and save the response to file as text it success but I need it to be resolved as proper response to the prompt ![Capture9.PNG](https://github.com/josStorer/RWKV-Runner/assets/56027532/c8506c17-29fb-4e61-9d5d-c071911fea74)

**Comment by josStorer** [comment]
use `stream: False`

`stream: True` is used for sse: https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events

**Comment by LSXAxeller** [comment]
> use `stream: False`
> 
> `stream: True` is used for sse: https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events

Now it works, thanks
