### ISSUE TITLE
  "detail": "model not loaded"

### ISSUE THREAD

**Issue by qweronly** [josStorer/RWKV-Runner#172]
"detail": "model not loaded"
![image](https://github.com/josStorer/RWKV-Runner/assets/141225454/029e406b-d0c7-4082-b2b5-0a83010311dc)
![image](https://github.com/josStorer/RWKV-Runner/assets/141225454/348b94c1-3f53-47ad-b8c9-b636f73d62e0)

**Comment by josStorer** [comment]
post /switch-model API to load the model: https://github.com/josStorer/RWKV-Runner/blob/master/deploy-examples/ChatGPT-Next-Web/setup.sh#L27

**Comment by qweronly** [comment]
谢谢
