### ISSUE TITLE
小说模式本地部署不能生成

### ISSUE THREAD

**Issue by qweronly** [josStorer/RWKV-Runner#174]
![image](https://github.com/josStorer/RWKV-Runner/assets/141225454/5f5b7ac5-a0b4-4849-9dd1-5a9bfbb5c9f3)
![image](https://github.com/josStorer/RWKV-Runner/assets/141225454/8a27fde6-422c-4df0-b008-047a7d2fca49)
 要怎么调整？

**Comment by josStorer** [comment]
目前似乎没有好用的续写webui
你可以在用户侧, 使用RWKV-Runner作为客户端, 在设置的API URL中填写服务器地址, 然后使用续写功能
