### ISSUE TITLE
safetensors安装问题

### ISSUE THREAD

**Issue by QinCaii** [josStorer/RWKV-Runner#175]
版本: 1.4.4
操作系统: Windows 10
我从Releases下载了最新版安装程序
安装依赖到safetensors报错
![tmp4986](https://github.com/josStorer/RWKV-Runner/assets/49438338/d82ccd8e-7a53-4c38-ab68-a097559789cd)
试着安装了缺少的模块
![tmpA93B](https://github.com/josStorer/RWKV-Runner/assets/49438338/4ce1b47e-27e0-4189-bbe1-00063c5b24d4)
仍然无法安装safetensors

**Comment by josStorer** [comment]
设置，关闭清华大学pip源，然后再安装试试

**Comment by QinCaii** [comment]
> 设置，关闭清华大学pip源，然后再安装试试

有用

**Comment by jwc19890114** [comment]
关闭之后还是报错，应该怎么解决呀，之前运行都是正常的，一个月没有用，今天打开就有问题了
