### ISSUE TITLE
CHANGE colour of model thats downloaded to RED on all the lists ,  so we know which ones we have, thanks

### ISSUE THREAD

**Issue by 2blackbar** [josStorer/RWKV-Runner#176]
yeah, now its kinda insane to browse through models

**Comment by josStorer** [comment]
The downloaded models will display "Open Folder" in the column on the right labeled "Actions". For models that haven't been downloaded yet, you will see a "Download" button. Clicking on "Actions" will sort them based on whether they have been downloaded or not.

![image](https://github.com/josStorer/RWKV-Runner/assets/13366013/4bf68307-9a66-420d-ae3c-bc4ef7717324)

**Comment by 2blackbar** [comment]
Oh, i didnt noticed what it means , thanks , can we download from huggingface somehow ?
Want to run this https://huggingface.co/TheBloke/WizardCoder-Python-13B-V1.0-GPTQ/tree/main

**Comment by josStorer** [comment]
Currently, huggingface models are not supported.
The issue has been resolved and is now closed.
Huggingface models may be supported in the future.
