### ISSUE TITLE
自定义字体，功能请求

### ISSUE THREAD

**Issue by culapyro** [josStorer/RWKV-Runner#177]
大佬 ，能否增加一项自定义字体 ， 更换软件的字体

**Comment by josStorer** [comment]
麻烦不太想做, 有需求的建议自己编译个, 以下是群友的自定义字体截图

![c45aaefa93c05624d1669492f79c8f6d](https://github.com/josStorer/RWKV-Runner/assets/13366013/80db2c61-a07f-43fc-a60f-1b02c2ffe231)

![d406b4e94d5e524ec767bf37f4cffb75](https://github.com/josStorer/RWKV-Runner/assets/13366013/d6c152c1-7ba9-409e-bda4-18c41bb62bfe)
