### ISSUE TITLE
怎么以服务方式运行

### ISSUE THREAD

**Issue by wushig** [josStorer/RWKV-Runner#179]
我这里有个问题，如果用GUI方式启动，就能正常加载模型，也可以正常调用接口，但是直接python3 main.py启动，使用switchModel切换模型，接口返回200，但是，请求补全接口和chat接口会报错，InternelError
![image](https://github.com/josStorer/RWKV-Runner/assets/29161527/1ef3dda1-ef5a-44a2-af0f-25fde876bca0)
有没有那种完整的命令，可以解决这样的问题，或者我想要加载某个配置文件，该怎么办？

**Comment by josStorer** [comment]
可能是你的strategy填错了，你使用的是什么模型，显存是多少，/switch-model API的strategy参考GUI界面的`当前Strategy`填写
