### ISSUE TITLE
请问python依赖无法下载，可不可以手动下载~

### ISSUE THREAD

**Issue by jiaowoxiaobai** [josStorer/RWKV-Runner#18]
wkv_cuda40.pyd
wkv_cuda10_30.pyd
torch.py
config.py
rwkv.py
global_var.py
convert_model.py
wkv_cuda_model.py
ngrok.py
dep_check.py
requirements_versions.txt
main.py
completion.py
requirements.txt
上面的这些全部都无法下载，好像是jsdelivr的问题，我这边无法连接到cdn网络，请问能手动下载嘛？

**Comment by josStorer** [comment]
github这个目录，下载了放进文件夹就好https://github.com/josStorer/RWKV-Runner/tree/master/backend-python

**Comment by josStorer** [comment]
然后下一个get-pip.py  https://cdn.jsdelivr.net/gh/pypa/get-pip/public/get-pip.py , 也放进backend-python目录

**Comment by jiaowoxiaobai** [comment]
> 然后下一个get-pip.py https://cdn.jsdelivr.net/gh/pypa/get-pip/public/get-pip.py , 也放进backend-python目录

谢谢，已经可以了~~

**Comment by TOLQY** [comment]
阿里云挂掉了，改软件源的文件在哪。。。有没有大佬指点一下，谢谢。
