### ISSUE TITLE
cyac是什么鬼东西

### ISSUE THREAD

**Issue by lampcccc** [josStorer/RWKV-Runner#182]
RWKV-Runner_windows_x64\backend-python\requirements.txt
pip install -r requirements.txt

 error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cyac
Failed to build cyac
ERROR: Could not build wheels for cyac, which is required to install pyproject.toml-based projects

47kb 的东西也太难装了吧
pip install cyac

Collecting cyac
  Using cached cyac-1.9.tar.gz (47 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting cython>=0.29.0 (from cyac)
  Obtaining dependency information for cython>=0.29.0 from https://files.pythonhosted.org/packages/ea/8f/216de5d7bede3e26a7131b427a8aadade032f03f9c8ee88792def02e2cf4/Cython-3.0.2-cp311-cp311-win_amd64.whl.metadata
  Using cached Cython-3.0.2-cp311-cp311-win_amd64.whl.metadata (3.2 kB)
Using cached Cython-3.0.2-cp311-cp311-win_amd64.whl (2.8 MB)
Building wheels for collected packages: cyac
  Building wheel for cyac (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for cyac (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [37 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\cyac
      copying lib\cyac\version.py -> build\lib.win-amd64-cpython-311\cyac
      copying lib\cyac\__init__.py -> build\lib.win-amd64-cpython-311\cyac
      running egg_info
      writing cyac.egg-info\PKG-INFO
      writing dependency_links to cyac.egg-info\dependency_links.txt
      writing requirements to cyac.egg-info\requires.txt
      writing top-level names to cyac.egg-info\top_level.txt
      reading manifest file 'cyac.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching 'ac.cpp' found anywhere in distribution
      warning: no previously-included files matching 'trie.cpp' found anywhere in distribution
      warning: no previously-included files matching 'utf8.cpp' found anywhere in distribution
      warning: no previously-included files matching 'xstring.cpp' found anywhere in distribution
      warning: no previously-included files matching '__pycache__' found anywhere in distribution
      adding license file 'LICENSE'
      writing manifest file 'cyac.egg-info\SOURCES.txt'
      copying lib\cyac\ac.pxd -> build\lib.win-amd64-cpython-311\cyac
      copying lib\cyac\ac.pyx -> build\lib.win-amd64-cpython-311\cyac
      copying lib\cyac\trie.pxd -> build\lib.win-amd64-cpython-311\cyac
      copying lib\cyac\trie.pyx -> build\lib.win-amd64-cpython-311\cyac
      copying lib\cyac\unicode_portability.c -> build\lib.win-amd64-cpython-311\cyac
      copying lib\cyac\utf8.pxd -> build\lib.win-amd64-cpython-311\cyac
      copying lib\cyac\utf8.pyx -> build\lib.win-amd64-cpython-311\cyac
      copying lib\cyac\util.c -> build\lib.win-amd64-cpython-311\cyac
      copying lib\cyac\util.pxd -> build\lib.win-amd64-cpython-311\cyac
      copying lib\cyac\util.pyx -> build\lib.win-amd64-cpython-311\cyac
      copying lib\cyac\xstring.pxd -> build\lib.win-amd64-cpython-311\cyac
      copying lib\cyac\xstring.pyx -> build\lib.win-amd64-cpython-311\cyac
      running build_ext
      building 'cyac.util' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cyac
Failed to build cyac
ERROR: Could not build wheels for cyac, which is required to install pyproject.toml-based projects

**Comment by josStorer** [comment]
我打包的二进制里面自带了，你也可以不装，不装时缓存会被禁用

**Comment by lampcccc** [comment]
我现在连运行都运行不了，影响本地服务吗？

**Comment by Aknifejackzhmolong** [comment]
昨天刚遇到这个问题，你先安装旁边的pip install requirements_without_cyac.xtx那个咯，然后pip install cyac就行了
