### ISSUE TITLE
OOM异常，自动kill程序了

### ISSUE THREAD

**Issue by wushig** [josStorer/RWKV-Runner#185]
显卡时英伟达的6G内存，加载3B模型的时候可以正常调用显卡，加载完成，功能没问题，但是加载7B模型的时候，系统会OOM，并且一开始加载，CPU直接跑满，GPU完全不工作是什么情况？
![image](https://github.com/josStorer/RWKV-Runner/assets/29161527/528cec78-9a4a-4030-b389-3bd193987add)

**Comment by josStorer** [comment]
内存不足, 模型会先载入内存, 增加虚拟内存可解决
