### ISSUE TITLE
WEBGPU/ai00 load a model to a discrete GPU

### ISSUE THREAD

**Issue by chymian** [josStorer/RWKV-Runner#187]
I open this ticket here to follow a ticket on ai_server [#35](https://github.com/cgisky1980/ai00_rwkv_server/issues/35) to load a model on a discrete GPU. 
as follow up of the problem described there, RWKV-Runner also does not load  a 7B model to discrete GPU, when vulkan reports the integrated CPU as GPU0.

**Comment by josStorer** [comment]
fixed in v0.2.2 https://github.com/cgisky1980/ai00_rwkv_server/issues/35
