### ISSUE TITLE
训练报错：OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

### ISSUE THREAD

**Issue by Yuerchu** [josStorer/RWKV-Runner#188]
训练时报错：OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
希望可以加一个自动安装CUDA的功能吧

**Comment by josStorer** [comment]
有自动安装功能

这个问题通常是WSL的cuda驱动下载由于未知原因意外终止，且没能成功断点续传，导致最终文件不完整，安装驱动失败，导致的CUDA_HOME environment variable is not set

解决方法：
删掉Runner目录下的cuda-repo-wsl-ubuntu-12-2-local_12.2.0-1_amd64.deb文件，再次点击训练，会重新下载
