### ISSUE TITLE
【咨询】请问一下服务器上可以部署本项目吗？

### ISSUE THREAD

**Issue by taurusduan** [josStorer/RWKV-Runner#189]

**Comment by PJ-568** [comment]
怎么不行呢，当然可以。详见 [Server-Deploy-Examples](https://github.com/josStorer/RWKV-Runner/tree/master/deploy-examples) 。

**Comment by PJ-568** [comment]
显然是可行的。

**Comment by josStorer** [comment]
这里有服务器上部署的示例命令可供参考: https://github.com/josStorer/RWKV-Runner/blob/master/deploy-examples/ChatGPT-Next-Web/setup.sh
