### ISSUE TITLE
提示缺少config.py

### ISSUE THREAD

**Issue by maye174** [josStorer/RWKV-Runner#19]
![图片](https://github.com/josStorer/RWKV-Runner/assets/96584640/474bb61f-0f16-47db-a1ea-22dcbae669de)

手动复制仓库文件中的config.py到backend-python\routes后运行正常

**Comment by josStorer** [comment]
看下下载列表，一般是没下载完成，所以要手动下，国内网络问题

**Comment by maye174** [comment]
> 看下下载列表，一般是没下载完成，所以要手动下，国内网络问题

应该是这个问题，软件已经关了，下载列表找不到了。希望作者能在运行前检测一下文件完整性

**Comment by josStorer** [comment]
每次启动如果发现文件不存在，都会自动加入下载列表，下载列表没有，就说明文件齐全了，因为你手动复制了，所以没有再下载
