### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'EventsOnMultiple')

### ISSUE THREAD

**Issue by 997172286** [josStorer/RWKV-Runner#195]
我在启动frontend的时候会报错,
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'EventsOnMultiple')
    at EventsOnMultiple (runtime.js:40:27)
    at EventsOn (runtime.js:44:12)
    at startup (startup.ts:14:3)
    at main.tsx:12:1
![image](https://github.com/josStorer/RWKV-Runner/assets/30894750/1a639b9e-9c29-4211-98ff-755eb423f43f)
在linux上用npm build dev 启动的
我以为是wails没有,用go安装过了,但是还是不行,如果有遇到相同问题的朋友请帮帮我,感谢好人一百万次!!!
如果需要别的信息,请告诉我吼,非常感谢

**Comment by josStorer** [comment]
使用wails构建，执行`make dev`
npm仅构建前端，但是软件启动依赖部分go本地的函数调用，而npm构建时，go后端部分未导出，不可用
