### ISSUE TITLE
frontend on linux

### ISSUE THREAD

**Issue by TeaCult** [josStorer/RWKV-Runner#197]
Python backend works nicely on an archlinux kvm with rtx 3060. But for frontend i have insatlled typescript and vite, ran nmp run dev -- --host 

Web page returns this as body. Empty white screen ... 

```
<body>
<div id="root"></div>
<script src="./src/main.tsx" type="module"></script>



<webchatgpt-custom-element-8bd0b55a-77da-477c-ad13-b8e699f1b059 id="webchatgpt-snackbar" style="z-index: 2147483647;"></webchatgpt-custom-element-8bd0b55a-77da-477c-ad13-b8e699f1b059></body>
```

**Comment by josStorer** [comment]
Build frontend client with [Wails](https://github.com/wailsapp/wails), execute `make build`.
For detailed steps, refer to: https://github.com/josStorer/RWKV-Runner/blob/master/.github/workflows/release.yml#L97

NPM only builds the web frontend, but the software startup relies on some local Go function calls. When NPM builds, the Go backend part is not exported so it will fail.

If you do not have a gui, you could use some other chatgpt services, like https://github.com/Yidadaa/ChatGPT-Next-Web
Here is an example: https://github.com/josStorer/RWKV-Runner/blob/master/deploy-examples/ChatGPT-Next-Web/setup.sh

**Comment by TeaCult** [comment]
Thank you for your reply.
