### ISSUE TITLE
速度问题

### ISSUE THREAD

**Issue by Terrency** [josStorer/RWKV-Runner#2]
尝试下载了7B-v11模型，配置使用GPU-6G-7B-CN，做了转换，其他参数默认，GPU显存占用6GB，运行速度与chatglm-6b-int4还是有些差距，结果看着要好不少，速度大概2个字/s， 请教一下性能在哪种配置下是最好的
显卡为2080super
cpu 为AMD 3060
内存 64GB

**Comment by josStorer** [comment]
用1.0.2，今天更新了内置cuda算子，速度提升明显
这里是演示视频，顺便求个三连转发：https://www.bilibili.com/video/BV1hM4y1v76R/
旧版本升级上来，建议把除了本体和models目录以外的文件删除，这个版本对pytorch有要求，重新安装会装特定版本

**Comment by SunshineboyZj** [comment]
> 用1.0.2，今天更新了内置cuda算子，速度提升明显 这里是演示视频，顺便求个三连转发：https://www.bilibili.com/video/BV1hM4y1v76R/ 旧版本升级上来，建议把除了本体和models目录以外的文件删除，这个版本对pytorch有要求，重新安装会装特定版本

使用自定义CUDA算子加速会输出莫名其妙的文字，关掉就正常输出了，可以问下这是什么情况吗
![使用自定义CUDA算子加速](https://github.com/josStorer/RWKV-Runner/assets/81549837/797789e5-8823-4ac1-9310-b34cd6ef9d92)
![莫名其妙的文字输出](https://github.com/josStorer/RWKV-Runner/assets/81549837/ffa663f5-490d-412e-bc5b-45c9a37ac515)
