### ISSUE TITLE
swagger api  怎么使用 json的参数如何填写。

### ISSUE THREAD

**Issue by anan1213095357** [josStorer/RWKV-Runner#20]

**Comment by josStorer** [comment]
https://github.com/josStorer/RWKV-Runner/issues/6#issuecomment-1560404423

不确定你的问题，看看这个有没有帮助

**Comment by anan1213095357** [comment]
> [#6 (comment)](https://github.com/josStorer/RWKV-Runner/issues/6#issuecomment-1560404423)
> 
> 不确定你的问题，看看这个有没有帮助

我的意思是有没有实例 json 参数。 我不太确定应该怎么填写那些值

**Comment by josStorer** [comment]
可以为空, 只填prompt一项即可

**Comment by anan1213095357** [comment]
> 可以为空, 只填prompt或messages一项即可，runner软件配置页面，每一项参数，鼠标悬停，有详细说明

你软件发消息的时候有 报文吗，我看一下报文我就明白了。

**Comment by anan1213095357** [comment]
> > 可以为空, 只填prompt或messages一项即可，runner软件配置页面，每一项参数，鼠标悬停，有详细说明
> 
> 你软件发消息的时候有 报文吗，我看一下报文我就明白了。

因为我怎么试都不行。能让我看一下你 客户都安实际发送的报文吗

**Comment by josStorer** [comment]
![image](https://github.com/josStorer/RWKV-Runner/assets/13366013/6177e953-842d-433b-b2ef-39bb12d15118)

**Comment by josStorer** [comment]
可以直接参考openai的文档 https://platform.openai.com/docs/api-reference/chat

**Comment by anan1213095357** [comment]
> 可以直接参考openai的文档 https://platform.openai.com/docs/api-reference/chat

谢谢哥

**Comment by josStorer** [comment]
这里有API示例https://www.bilibili.com/read/cv23921171
