### ISSUE TITLE
日志在哪看？

### ISSUE THREAD

**Issue by lampcccc** [josStorer/RWKV-Runner#202]
昨天2023.10.7还好好的，今天2023.10.8就无法运行。
后台只闪了一下就没了。
RWKV-Runner_windows_x64\error.txt里面啥也没有，话说日志在哪看？

**Comment by josStorer** [comment]
api.log是api日志，但api服务没起来的话没有

建议你配置页面换一个端口试试，可能是端口占用

**Comment by lampcccc** [comment]
ok 已解决

**Comment by beetaa** [comment]
@lampcccc 你好，我也遇到了启动时无法运行的情况，请问您是怎么解决的？谢谢。

**Comment by josStorer** [comment]
#205

**Comment by lampcccc** [comment]
配置
api 端口 随便改一改

**Comment by Buenbk** [comment]
> @lampcccc 你好，我也遇到了启动时无法运行的情况，请问您是怎么解决的？谢谢。

你好，我也是同样问题，改了端口并没有用，请问您解决了吗？
