### ISSUE TITLE
模型不能启动

### ISSUE THREAD

**Issue by beetaa** [josStorer/RWKV-Runner#205]
已按提示安装 python，依赖，已下载模型，但无法正常启动模型，命令行闪现后消失，不能查看输出信息。模型处于离线状态。版本：懒人包 1.3.7，最新版本 1.4.8 均已尝试。

![image](https://github.com/josStorer/RWKV-Runner/assets/5688224/12c8afd7-16f4-46f5-b65e-91de64cb4121)

![image](https://github.com/josStorer/RWKV-Runner/assets/5688224/09d2c3b9-8acc-4606-abf4-e2446de13ec4)

**Comment by josStorer** [comment]
手动在命令行内启动看看输出结果，执行`./py310/python.exe ./backend-python/main.py`

**Comment by beetaa** [comment]
> 手动在命令行内启动看看输出结果，执行`./py310/python.exe ./backend-python/main.py`
> 
> 很可能是端口占用，配置页面换个端口

确实是端口的原因，和预期不一样的是，被占用的不是 API 服务器的 8000 端口，是内置的 `3667/3670` 端口，如果是这样，一般很难通过端口占用信息来排查，建议可以在 Readme 中添加这两个端口的信息，以便用户排查启动故障。

![image](https://github.com/josStorer/RWKV-Runner/assets/5688224/299a1b28-4ffc-4cd3-a2e4-bc717d3e0c6b)

**Comment by josStorer** [comment]
`3667/3670`这是本地发起网络请求的端口，是随机的，并没有占用

**Comment by Buenbk** [comment]
你好，我也是无法正常启动模型，一个终端窗口闪一下就没了，请问您最终是如何解决的呢？
