### ISSUE TITLE
windows11下通过 exe 安装报错

### ISSUE THREAD

**Issue by PhilRandWu** [josStorer/RWKV-Runner#208]
windows11下通过 exe 安装报错
![image](https://github.com/josStorer/RWKV-Runner/assets/71576743/26dfdad2-4d70-4701-a1e1-a549a4f2c940)
The runtime failed to install correct y.Please try again.

**Comment by josStorer** [comment]
试试更新下edge浏览器

**Comment by PhilRandWu** [comment]
> 试试更新下edge浏览器

有将 edge 浏览器从 c 盘移动到了其他盘，可能是这个原因导致的。但为啥会有关于 edge 浏览器呢？有什么可以解决的方法吗？

**Comment by josStorer** [comment]
软件界面依赖系统浏览器组件

**Comment by PhilRandWu** [comment]
奥，好的谢谢，我再研究一下看看怎么能解决这个问题吧
