### ISSUE TITLE
INFO:     127.0.0.1:59688 - "POST /switch-model HTTP/1.1" 500 Internal Server Error

### ISSUE THREAD

**Issue by qinghuanyyz** [josStorer/RWKV-Runner#209]
--- 0.911884069442749 seconds ---
INFO:     Started server process [35344]
INFO:     Waiting for application startup.
torch found: F:\AI\wenda\runner\py310\Lib\site-packages\torch\lib
torch set
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:59688 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:59688 - "GET /status HTTP/1.1" 200 OK
INFO:     127.0.0.1:59688 - "OPTIONS /update-config HTTP/1.1" 200 OK
INFO:     127.0.0.1:59687 - "OPTIONS /switch-model HTTP/1.1" 200 OK
max_tokens=4100 temperature=1.2 top_p=0.5 presence_penalty=0.4 frequency_penalty=0.4
INFO:     127.0.0.1:59687 - "POST /update-config HTTP/1.1" 200 OK
RWKV_JIT_ON 1 RWKV_CUDA_ON 0 RESCALE_LAYER 6

Loading F:\AI\wenda\runner\models/RWKV-4-Raven-3B-v12-Eng49%-Chn49%-Jpn1%-Other1%-20230527-ctx4096.pth-cuda-fp16i8--24-.pth ...
Converted model: strategy cuda fp16i8 *24+, version 0.7

INFO:     127.0.0.1:59688 - "POST /switch-model HTTP/1.1" 500 Internal Server Error

3060的笔记本，关掉打开算子加速都会这样

**Comment by josStorer** [comment]
你用的是一个转换过的模型, 转换过的模型能提高载入速度, 但是不能再调整参数
你这个模型所用的参数是, int8精度 载入24层
你要在配置页面, 调整到这个参数, 才能载入

**Comment by qinghuanyyz** [comment]
> 你用的是一个转换过的模型， 转换过的模型能提高载入速度， 但是不能再调整参数 你这个模型所用的参数是， int8精度 载入24层 你要在配置页面， 调整到这个参数， 才能载入

成功了！！！感谢！！
