### ISSUE TITLE
找不到模型

### ISSUE THREAD

**Issue by ssochi** [josStorer/RWKV-Runner#21]
![image](https://github.com/josStorer/RWKV-Runner/assets/15121953/620a58f8-7090-4d06-bbdb-cbd5ef616b79)

**Comment by anan1213095357** [comment]
下载模型需要科学上网，然后懒人包里面有一个自带的3b的模型

**Comment by ssochi** [comment]
可我模型以及下完了，我下的是7B的，截图里有

**Comment by anan1213095357** [comment]
> 可我模型以及下完了，我下的是7B的，截图里有

你模型要选对，有好几个模型。

**Comment by anan1213095357** [comment]
> 你模型下的问题，你的体积是18.1GB，7B应该是13.77GB

老哥 我那个问题帮我看下

**Comment by ssochi** [comment]
![image](https://github.com/josStorer/RWKV-Runner/assets/15121953/258ad392-54fd-4735-aeb2-b4b083c53188)
必须要用v10x吗？

**Comment by josStorer** [comment]
所有的7B正常体积都是13.77GB，这个是显示了你本地文件的体积

**Comment by ssochi** [comment]
> 所有的7B正常体积都是13.77GB，这个是显示了你本地文件的体积

嗯嗯，sha256不一致，确实出问题了，我再下一次

**Comment by ssochi** [comment]
感觉可能是我中途暂停过一次，然后切了下代理。可能是bug

**Comment by josStorer** [comment]
可能是断点续传的bug
