### ISSUE TITLE
Missing dependencies after pip install

### ISSUE THREAD

**Issue by jcuenod** [josStorer/RWKV-Runner#210]
I cloned the repo, and ran `pip install -r requirements.txt` in the `python-backend` folder, but I still needed to install:

- sse_starlette
- mido
- midi2audio
- python-multipart

**Comment by josStorer** [comment]
but they are listed in the requirements.txt

![image](https://github.com/josStorer/RWKV-Runner/assets/13366013/62d0ee15-6318-4ebc-877e-f5470e4fa65d)

**Comment by jcuenod** [comment]
Interesting. I see that in my clone.

I use pyenv, so I started with `pyenv shell 3.11.4`. Any idea why `pip install -r requirements.txt` wouldn't install everything? Either way, I don't mind if this issue is closed.
