### ISSUE TITLE
.pth文件要放在哪个文件夹下面啊？

### ISSUE THREAD

**Issue by KAILAI346** [josStorer/RWKV-Runner#212]
我使用软件自行下载 RWKV-4-World-CHNtuned-7B-v1-20230709-ctx4096.pth，迟迟无法响应，我在浏览器上下载了这个文件，现在我不知道这个文件要放在那个文件夹下面。
这是我的文件夹截图：
![XISE_1108132847](https://github.com/josStorer/RWKV-Runner/assets/59322707/c448ffb9-5c72-495c-9596-b161f9cf7812)
这里先谢谢大家了。

**Comment by josStorer** [comment]
放进models目录下

**Comment by KAILAI346** [comment]
> 放进models目录下

感谢(*￣︶￣)
