### ISSUE TITLE
训练功能报错could not get distro "Ubuntu"'s state: exit status 0xffffffff  wsl -d Ubuntu -u root指令可以正常使用

### ISSUE THREAD

**Issue by 1luik** [josStorer/RWKV-Runner#213]

**Comment by josStorer** [comment]
wsl -l -v是否能看到Ubuntu, 且wsl版本是否为2
并尝试执行wsl --update

**Comment by 1luik** [comment]
PS E:\服务器\DraftShapeNetwork> wsl -l -v
命令行选项无效: -l
使用: wsl.exe [选项] ......
选项:
    -d, --distribution <DistributionName>
        启动指定的分发。

    -e, --exec <CommandLine>
        执行指定的 Linux 命令。其余的参数
        用作命令行执行。

    -u, --user <UserName>
        作为指定用户运行。

    --帮助
        显示使用信息。

    --
        停止解析参数，并将其余部分传递给 Linux 进程。

**Comment by 1luik** [comment]
PS E:\服务器\DraftShapeNetwork> wsl --update
命令行选项无效: --update
使用: wsl.exe [选项] ......
选项:
    -d, --distribution <DistributionName>
        启动指定的分发。

    -e, --exec <CommandLine>
        执行指定的 Linux 命令。其余的参数
        用作命令行执行。

    -u, --user <UserName>
        作为指定用户运行。

    --帮助
        显示使用信息。

    --
        停止解析参数，并将其余部分传递给 Linux 进程。

**Comment by 1luik** [comment]
服务器版本windows

**Comment by 1luik** [comment]
网上的所有指令都是这样的

**Comment by 1luik** [comment]
命令行选项无效********

**Comment by 1luik** [comment]
另外rwkv的模型无法再windows训练的原因是因为官方不会使用参数，在加载的时候忘记删除空格了我删除之后是可以正常运行的


wkv5_cuda = load(name="wkv5", sources=["cuda/wkv5_op.cpp", f"cuda/wkv5_cuda.cu"],
                verbose=True, extra_cuda_cflags=["-res-usage", "--use_fast_math", "-O3", "-Xptxas -O3", "--extra-device-vectorization", f"-D_N_={HEAD_SIZE}"])
                
                改成
wkv5_cuda = load(name="wkv5", sources=["cuda/wkv5_op.cpp", f"cuda/wkv5_cuda.cu"],
                verbose=True, extra_cuda_cflags=["-res-usage", "--use_fast_math", "-O3", "-Xptxas", "-O3", "--extra-device-vectorization", f"-D_N_={HEAD_SIZE}"])

**Comment by 1luik** [comment]
https://github.com/BlinkDL/RWKV-LM/blob/main/RWKV-v5/src/model.py

**Comment by 1luik** [comment]
我不知道怎么设置参数跟参数都是什么所以我是自己写的训练的

**Comment by josStorer** [comment]
> PS E:\服务器\DraftShapeNetwork> wsl -l -v 命令行选项无效: -l 使用: wsl.exe [选项] ...... 选项: -d, --distribution 启动指定的分发。
> 
> ```
> -e, --exec <CommandLine>
>     执行指定的 Linux 命令。其余的参数
>     用作命令行执行。
> 
> -u, --user <UserName>
>     作为指定用户运行。
> 
> --帮助
>     显示使用信息。
> 
> --
>     停止解析参数，并将其余部分传递给 Linux 进程。
> ```

这说明你的windows版本太旧, 需要升级

**Comment by josStorer** [comment]
> 另外rwkv的模型无法再windows训练的原因是因为官方不会使用参数，在加载的时候忘记删除空格了我删除之后是可以正常运行的
> 
> wkv5_cuda = load(name="wkv5", sources=["cuda/wkv5_op.cpp", f"cuda/wkv5_cuda.cu"], verbose=True, extra_cuda_cflags=["-res-usage", "--use_fast_math", "-O3", "-Xptxas -O3", "--extra-device-vectorization", f"-D_N_={HEAD_SIZE}"])
> 
> ```
>             改成
> ```
> 
> wkv5_cuda = load(name="wkv5", sources=["cuda/wkv5_op.cpp", f"cuda/wkv5_cuda.cu"], verbose=True, extra_cuda_cflags=["-res-usage", "--use_fast_math", "-O3", "-Xptxas", "-O3", "--extra-device-vectorization", f"-D_N_={HEAD_SIZE}"])

windows无法训练是因为训练需要deepspeed, 而deepspeed不完全支持windows

**Comment by 1luik** [comment]
windows版本太旧，

你的设备中缺少重要的安全和质量修复。我一直都不知道不过系统版本是windows server 2019数据中心版

**Comment by 1luik** [comment]
> > PS E:\服务器\DraftShapeNetwork> wsl -l -v 命令行选项无效: -l 使用: wsl.exe [选项] ...... 选项: -d, --distribution 启动指定的分发。 
> > ```
> > -e, --exec <CommandLine>
> >     执行指定的 Linux 命令。其余的参数
> >     用作命令行执行。
> > 
> > -u, --user <UserName>
> >     作为指定用户运行。
> > 
> > --帮助
> >     显示使用信息。
> > 
> > --
> >     停止解析参数，并将其余部分传递给 Linux 进程。
> > ```
> 
> 这说明你的windows版本太旧, 需要升级
版本号17763.107系统是server 2019数据中心版，
很不幸这个版本是2018年的，我今年下载的

**Comment by 1luik** [comment]
> > > PS E:\服务器\DraftShapeNetwork> wsl -l -v 命令行选项无效: -l 使用: wsl.exe [选项] ...... 选项: -d, --distribution 启动指定的分发。 
> > > ```
> > > -e, --exec <CommandLine>
> > >     执行指定的 Linux 命令。其余的参数
> > >     用作命令行执行。
> > > 
> > > -u, --user <UserName>
> > >     作为指定用户运行。
> > > 
> > > --帮助
> > >     显示使用信息。
> > > 
> > > --
> > >     停止解析参数，并将其余部分传递给 Linux 进程。
> > > ```
> > 
> > 
> > 这说明你的windows版本太旧, 需要升级 
> > 版本号17763.107系统是server 2019数据中心版， 
> > 很不幸这个版本是2018年的，我今年下载的

之前更新挂了我没有发现

**Comment by 1luik** [comment]
你可以加一个提示吗我找了半个月报错，网上没有任何相关的

**Comment by 1luik** [comment]
> > PS E:\服务器\DraftShapeNetwork> wsl -l -v 命令行选项无效: -l 使用: wsl.exe [选项] ...... 选项: -d, --distribution 启动指定的分发。 
> > ```
> > -e, --exec <CommandLine>
> >     执行指定的 Linux 命令。其余的参数
> >     用作命令行执行。
> > 
> > -u, --user <UserName>
> >     作为指定用户运行。
> > 
> > --帮助
> >     显示使用信息。
> > 
> > --
> >     停止解析参数，并将其余部分传递给 Linux 进程。
> > ```
> 
> 这说明你的windows版本太旧, 需要升级

我更新没用已经是

**Comment by 1luik** [comment]
> > PS E:\服务器\DraftShapeNetwork> wsl -l -v 命令行选项无效: -l 使用: wsl.exe [选项] ...... 选项: -d, --distribution 启动指定的分发。  
> > ```
> > -e, --exec <CommandLine>
> >     执行指定的 Linux 命令。其余的参数
> >     用作命令行执行。
> > 
> > -u, --user <UserName>
> >     作为指定用户运行。
> > 
> > --帮助
> >     显示使用信息。
> > 
> > --
> >     停止解析参数，并将其余部分传递给 Linux 进程。
> > ```
> 
> 这说明你的windows版本太旧, 需要升级


我跟新最新版系统了用设置里的更新，没用已经是最新版了还是那个报错


PS C:\Users\Administrator> wsl -l -v
命令行选项无效: -l
使用: wsl.exe [选项] ......
选项:
    -d, --distribution <DistributionName>
        启动指定的分发。

    -e, --exec <CommandLine>
        执行指定的 Linux 命令。其余的参数
        用作命令行执行。

    -u, --user <UserName>
        作为指定用户运行。

    --帮助
        显示使用信息。

    --
        停止解析参数，并将其余部分传递给 Linux 进程。
PS C:\Users\Administrator>

而且重启还tm是系统强制的

**Comment by josStorer** [comment]
> 版本号17763.107系统是server 2019数据中心版，
> 很不幸这个版本是2018年的，我今年下载的
>

https://github.com/MicrosoftDocs/WSL/issues/678

WSL2是2019年发布的, windows server2019基于windows 1809, 如你所说, 你的版本是17763, 不支持WSL2

以下是新版WSL的典型命令行信息
![image](https://github.com/josStorer/RWKV-Runner/assets/13366013/54c84185-1241-4ef0-aa57-063cf9881261)

**Comment by 1luik** [comment]
> > 版本号17763.107系统是server 2019数据中心版，
> > 很不幸这个版本是2018年的，我今年下载的
> 
> [MicrosoftDocs/WSL#678](https://github.com/MicrosoftDocs/WSL/issues/678)
> 
> WSL2是2019年发布的, windows server2019基于windows 1809, 如你所说, 你的版本是17763, 不支持WSL2
> 
> 以下是新版WSL的典型命令行信息 ![image](https://user-images.githubusercontent.com/13366013/284106038-54c84185-1241-4ef0-aa57-063cf9881261.png)

这个怎么升级啊

**Comment by 1luik** [comment]
网上都被使用windows更新盖住了

**Comment by josStorer** [comment]
必须升级到高版本windows

**Comment by 1luik** [comment]
网上都被使用设置里那个windows更新盖住了

> 必须升级到高版本windows

**Comment by 1luik** [comment]
百度搜windows升级结果是一样的

**Comment by 1luik** [comment]
然后就是升级11的

**Comment by 1luik** [comment]
跟版本没有半点关系

**Comment by josStorer** [comment]
你使用的系统是windows server 2019数据中心版, 版本号17763.107
这个版本不能使用WSL2
因此你需要升级到更高版本号的windows
但是windows server是不能直接通过检查更新升级大版本的
因此如果你想要使用WSL2, 你需要重装更高版本的系统, 从而"升级"

**Comment by josStorer** [comment]
https://learn.microsoft.com/zh-cn/windows-server/get-started/install-upgrade-migrate
https://learn.microsoft.com/zh-cn/windows-server/get-started/perform-in-place-upgrade

你也可以参考此处的说明, 执行就地升级, 尝试升级到2022版本的windows server

**Comment by 1luik** [comment]
我脑子有点晕，是server 2019不是windows10吗，不支持2？？？？？？

**Comment by 1luik** [comment]
我没有tpm啊，没有安装

**Comment by 1luik** [comment]
网上tm有说要的有说不要的

**Comment by Rostopher** [comment]
> 你使用的系统是windows server 2019数据中心版, 版本号17763.107 这个版本不能使用WSL2 因此你需要升级到更高版本号的windows 但是windows server是不能直接通过检查更新升级大版本的 因此如果你想要使用WSL2, 你需要重装更高版本的系统, 从而"升级"

您好，所以版本号1809的Windows Server 2019 Datacenter是可以使用WSL2的吗

**Comment by josStorer** [comment]
@Rostopher 不能, 1903及以上才能用WSL2, 具体版本号是18362.1049及以上
