### ISSUE TITLE
DepCheck Error: 没有错误提示

### ISSUE THREAD

**Issue by hanmin0822** [josStorer/RWKV-Runner#222]
版本 1.5.2 最新版
运行提示报错 DepCheck Error:
![image](https://github.com/josStorer/RWKV-Runner/assets/22577547/0b39a65c-c834-45c4-8ea2-5a5bbac76172)
点击 安装依赖 多次还是同样的报错
尝试 手动执行 install-py-dep.bat 的指令 成功安装所有依赖后 重启 依然同样报错

**Comment by josStorer** [comment]
是否在设置内修改了python路径, 注意路径不需要引号

**Comment by hanmin0822** [comment]
设置了，但是没有引号
![image](https://github.com/josStorer/RWKV-Runner/assets/22577547/acbae1ce-38a6-429c-b3c1-22f0e265ddc7)

**Comment by josStorer** [comment]
不能有空格, golang的传参bug
https://github.com/golang/go/issues/17149#issuecomment-473976818
