### ISSUE TITLE
如何支持非OPENAI官方的API和KEY？

### ISSUE THREAD

**Issue by Lvjinhong** [josStorer/RWKV-Runner#228]
您好！您的项目非常出色！我想知道您是怎么支持 类OPENAI的api和key的，
可以麻烦告知一下对应的代码位置吗？ 我想参考一下
![image](https://github.com/josStorer/RWKV-Runner/assets/96970081/27c93981-382b-4cec-a5ed-4f49a5d5bdce)

代码文件我看了好久，知道如何 使用python后端部署rwkv模型，但是更进一步的 我想知道您是如何 设计请求结构的 ，
以至于 改变url地址后依旧可以正常对接。 这对我非常重要，如果您方便，可以麻烦帮助我一下吗？ 非常感谢

**Comment by josStorer** [comment]
请求结构直接抄的openai, 参考openai的文档写后端代码, 参数和返回值一样, 自然兼容了
