### ISSUE TITLE
Macos 选择配置后无法运行

### ISSUE THREAD

**Issue by Tsuzuki-Asato** [josStorer/RWKV-Runner#234]
macOS 114.1.2
Python 3.11.5
程序在/Applications/RWKV/RWKV-Runner.app
配置选择MAC-3B-CN后点运行
提示：
DepCheck Error: Traceback (most recent call last): File "/Applications/RWKV-Runner.app/Contents/MacOS/../../.././backend-python/dep_check.py", line 1, in <module> import multipart ModuleNotFoundError: No module named 'multipart'

点击安装后出现：
Last login: Sun Dec 10 21:28:10 on ttys000
cd /Applications/RWKV-Runner.app/Contents/MacOS/../../../ && python3 -m pip install -r ./backend-python/requirements_without_cyac.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
(base) jefflee@lizhefudeMacBook-Air ~ % cd /Applications/RWKV-Runner.app/Contents/MacOS/../../../ && python3 -m pip install -r ./backend-python/requirements_without_cyac.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: torch in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 1)) (2.1.1)
Requirement already satisfied: torchvision in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 2)) (0.16.1)
Requirement already satisfied: torchaudio in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 3)) (2.1.1)
Requirement already satisfied: rwkv==0.8.22 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 4)) (0.8.22)
Requirement already satisfied: langchain==0.0.322 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 5)) (0.0.322)
Requirement already satisfied: fastapi==0.104.0 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 6)) (0.104.0)
Requirement already satisfied: uvicorn==0.23.2 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 7)) (0.23.2)
Requirement already satisfied: sse-starlette==1.6.5 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 8)) (1.6.5)
Requirement already satisfied: pydantic==2.4.2 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 9)) (2.4.2)
Requirement already satisfied: psutil==5.9.6 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 10)) (5.9.6)
Requirement already satisfied: gputil==1.4.0 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 11)) (1.4.0)
Requirement already satisfied: tiktoken==0.5.1 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 12)) (0.5.1)
Requirement already satisfied: ftfy==6.1.1 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 13)) (6.1.1)
Requirement already satisfied: lm-dataformat==0.0.20 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 14)) (0.0.20)
Requirement already satisfied: numpy==1.24.4 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 15)) (1.24.4)
Requirement already satisfied: tokenizers==0.14.1 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 16)) (0.14.1)
Requirement already satisfied: tqdm==4.66.1 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 17)) (4.66.1)
Requirement already satisfied: midi2audio==0.1.1 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 18)) (0.1.1)
Requirement already satisfied: mido==1.3.0 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 19)) (1.3.0)
Requirement already satisfied: safetensors==0.4.0 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 20)) (0.4.0)
Requirement already satisfied: PyMuPDF==1.23.5 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 21)) (1.23.5)
Requirement already satisfied: python-multipart==0.0.6 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 22)) (0.0.6)
Requirement already satisfied: Cython==3.0.4 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from -r ./backend-python/requirements_without_cyac.txt (line 23)) (3.0.4)
Requirement already satisfied: PyYAML>=5.3 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from langchain==0.0.322->-r ./backend-python/requirements_without_cyac.txt (line 5)) (6.0)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from langchain==0.0.322->-r ./backend-python/requirements_without_cyac.txt (line 5)) (1.4.39)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from langchain==0.0.322->-r ./backend-python/requirements_without_cyac.txt (line 5)) (3.8.5)
Requirement already satisfied: anyio<4.0 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from langchain==0.0.322->-r ./backend-python/requirements_without_cyac.txt (line 5)) (3.7.1)
Requirement already satisfied: dataclasses-json<0.7,>=0.5.7 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from langchain==0.0.322->-r ./backend-python/requirements_without_cyac.txt (line 5)) (0.6.3)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from langchain==0.0.322->-r ./backend-python/requirements_without_cyac.txt (line 5)) (1.33)
Requirement already satisfied: langsmith<0.1.0,>=0.0.43 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from langchain==0.0.322->-r ./backend-python/requirements_without_cyac.txt (line 5)) (0.0.69)
Requirement already satisfied: requests<3,>=2 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from langchain==0.0.322->-r ./backend-python/requirements_without_cyac.txt (line 5)) (2.31.0)
Requirement already satisfied: tenacity<9.0.0,>=8.1.0 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from langchain==0.0.322->-r ./backend-python/requirements_without_cyac.txt (line 5)) (8.2.2)
Requirement already satisfied: starlette<0.28.0,>=0.27.0 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from fastapi==0.104.0->-r ./backend-python/requirements_without_cyac.txt (line 6)) (0.27.0)
Requirement already satisfied: typing-extensions>=4.8.0 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from fastapi==0.104.0->-r ./backend-python/requirements_without_cyac.txt (line 6)) (4.9.0)
Requirement already satisfied: click>=7.0 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from uvicorn==0.23.2->-r ./backend-python/requirements_without_cyac.txt (line 7)) (8.0.4)
Requirement already satisfied: h11>=0.8 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from uvicorn==0.23.2->-r ./backend-python/requirements_without_cyac.txt (line 7)) (0.14.0)
Requirement already satisfied: annotated-types>=0.4.0 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from pydantic==2.4.2->-r ./backend-python/requirements_without_cyac.txt (line 9)) (0.6.0)
Requirement already satisfied: pydantic-core==2.10.1 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from pydantic==2.4.2->-r ./backend-python/requirements_without_cyac.txt (line 9)) (2.10.1)
Requirement already satisfied: regex>=2022.1.18 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from tiktoken==0.5.1->-r ./backend-python/requirements_without_cyac.txt (line 12)) (2022.7.9)
Requirement already satisfied: wcwidth>=0.2.5 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from ftfy==6.1.1->-r ./backend-python/requirements_without_cyac.txt (line 13)) (0.2.5)
Requirement already satisfied: jsonlines in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from lm-dataformat==0.0.20->-r ./backend-python/requirements_without_cyac.txt (line 14)) (4.0.0)
Requirement already satisfied: ujson in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from lm-dataformat==0.0.20->-r ./backend-python/requirements_without_cyac.txt (line 14)) (5.4.0)
Requirement already satisfied: zstandard in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from lm-dataformat==0.0.20->-r ./backend-python/requirements_without_cyac.txt (line 14)) (0.19.0)
Requirement already satisfied: huggingface_hub<0.18,>=0.16.4 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from tokenizers==0.14.1->-r ./backend-python/requirements_without_cyac.txt (line 16)) (0.17.3)
Requirement already satisfied: packaging~=23.1 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from mido==1.3.0->-r ./backend-python/requirements_without_cyac.txt (line 19)) (23.1)
Requirement already satisfied: PyMuPDFb==1.23.5 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from PyMuPDF==1.23.5->-r ./backend-python/requirements_without_cyac.txt (line 21)) (1.23.5)
Requirement already satisfied: filelock in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from torch->-r ./backend-python/requirements_without_cyac.txt (line 1)) (3.9.0)
Requirement already satisfied: sympy in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from torch->-r ./backend-python/requirements_without_cyac.txt (line 1)) (1.11.1)
Requirement already satisfied: networkx in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from torch->-r ./backend-python/requirements_without_cyac.txt (line 1)) (3.1)
Requirement already satisfied: jinja2 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from torch->-r ./backend-python/requirements_without_cyac.txt (line 1)) (3.1.2)
Requirement already satisfied: fsspec in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from torch->-r ./backend-python/requirements_without_cyac.txt (line 1)) (2023.4.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from torchvision->-r ./backend-python/requirements_without_cyac.txt (line 2)) (10.0.1)
Requirement already satisfied: attrs>=17.3.0 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain==0.0.322->-r ./backend-python/requirements_without_cyac.txt (line 5)) (22.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain==0.0.322->-r ./backend-python/requirements_without_cyac.txt (line 5)) (2.0.4)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain==0.0.322->-r ./backend-python/requirements_without_cyac.txt (line 5)) (6.0.2)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain==0.0.322->-r ./backend-python/requirements_without_cyac.txt (line 5)) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain==0.0.322->-r ./backend-python/requirements_without_cyac.txt (line 5)) (1.8.1)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain==0.0.322->-r ./backend-python/requirements_without_cyac.txt (line 5)) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain==0.0.322->-r ./backend-python/requirements_without_cyac.txt (line 5)) (1.2.0)
Requirement already satisfied: idna>=2.8 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from anyio<4.0->langchain==0.0.322->-r ./backend-python/requirements_without_cyac.txt (line 5)) (3.4)
Requirement already satisfied: sniffio>=1.1 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from anyio<4.0->langchain==0.0.322->-r ./backend-python/requirements_without_cyac.txt (line 5)) (1.2.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from dataclasses-json<0.7,>=0.5.7->langchain==0.0.322->-r ./backend-python/requirements_without_cyac.txt (line 5)) (3.20.1)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from dataclasses-json<0.7,>=0.5.7->langchain==0.0.322->-r ./backend-python/requirements_without_cyac.txt (line 5)) (0.9.0)
Requirement already satisfied: jsonpointer>=1.9 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from jsonpatch<2.0,>=1.33->langchain==0.0.322->-r ./backend-python/requirements_without_cyac.txt (line 5)) (2.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from requests<3,>=2->langchain==0.0.322->-r ./backend-python/requirements_without_cyac.txt (line 5)) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from requests<3,>=2->langchain==0.0.322->-r ./backend-python/requirements_without_cyac.txt (line 5)) (2023.11.17)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from jinja2->torch->-r ./backend-python/requirements_without_cyac.txt (line 1)) (2.1.1)
Requirement already satisfied: mpmath>=0.19 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from sympy->torch->-r ./backend-python/requirements_without_cyac.txt (line 1)) (1.3.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in /Users/jefflee/anaconda3/lib/python3.11/site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7,>=0.5.7->langchain==0.0.322->-r ./backend-python/requirements_without_cyac.txt (line 5)) (1.0.0)

无报错但始终无法运行。

**Comment by Ivanyuanyuan** [comment]
我也是这个问题，请问有解决吗？

**Comment by Ivanyuanyuan** [comment]
> 我也是这个问题，请问有解决吗？

这个问题我解决了，如下操作。
/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip
更新pip
回到软件继续点击运行，点击它弹出的窗口安装后就成功了。

**Comment by Tsuzuki-Asato** [comment]
> > 我也是这个问题，请问有解决吗？
> 
> 这个问题我解决了，如下操作。 /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip 更新pip 回到软件继续点击运行，点击它弹出的窗口安装后就成功了。

我更新完出现

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in /Users/jefflee/Library/Python/3.9/lib/python/site-packages (23.3.1)

但是还是无法使用。还是一样的问题。

**Comment by Ivanyuanyuan** [comment]
> > > 我也是这个问题，请问有解决吗？
> > 
> > 
> > 这个问题我解决了，如下操作。 /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip 更新pip 回到软件继续点击运行，点击它弹出的窗口安装后就成功了。
> 
> 我更新完出现
> 
> Defaulting to user installation because normal site-packages is not writeable Requirement already satisfied: pip in /Users/jefflee/Library/Python/3.9/lib/python/site-packages (23.3.1)
> 
> 但是还是无法使用。还是一样的问题。

你给我的信息不对，你这信息只是提示你已经安装了包，还有其他报错么？

**Comment by Tsuzuki-Asato** [comment]
> > > > 我也是这个问题，请问有解决吗？
> > > 
> > > 
> > > 这个问题我解决了，如下操作。 /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip 更新pip 回到软件继续点击运行，点击它弹出的窗口安装后就成功了。
> > 
> > 
> > 我更新完出现
> > Defaulting to user installation because normal site-packages is not writeable Requirement already satisfied: pip in /Users/jefflee/Library/Python/3.9/lib/python/site-packages (23.3.1)
> > 但是还是无法使用。还是一样的问题。
> 
> 你给我的信息不对，你这信息只是提示你已经安装了包，还有其他报错么？
确实是没有别的内容了。
![Uploading 截屏2023-12-12 下午9.35.21.png…]()

**Comment by Tsuzuki-Asato** [comment]
> > > > 我也是这个问题，请问有解决吗？
> > > 
> > > 
> > > 这个问题我解决了，如下操作。 /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip 更新pip 回到软件继续点击运行，点击它弹出的窗口安装后就成功了。
> > 
> > 
> > 我更新完出现
> > Defaulting to user installation because normal site-packages is not writeable Requirement already satisfied: pip in /Users/jefflee/Library/Python/3.9/lib/python/site-packages (23.3.1)
> > 但是还是无法使用。还是一样的问题。
> 
> 你给我的信息不对，你这信息只是提示你已经安装了包，还有其他报错么？


确实是没有其他的了
<img width="608" alt="截屏2023-12-12 下午9 35 21" src="https://github.com/josStorer/RWKV-Runner/assets/11916774/6a6288d5-2348-42b9-a2a2-6bd87b1eceeb">

**Comment by Tsuzuki-Asato** [comment]
> > > > > > 我也是这个问题，请问有解决吗？
> > > > > 
> > > > > 
> > > > > 这个问题我解决了，如下操作。 /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip 更新pip 回到软件继续点击运行，点击它弹出的窗口安装后就成功了。
> > > > 
> > > > 
> > > > 我更新完出现
> > > > Defaulting to user installation because normal site-packages is not writeable Requirement already satisfied: pip in /Users/jefflee/Library/Python/3.9/lib/python/site-packages (23.3.1)
> > > > 但是还是无法使用。还是一样的问题。
> > > 
> > > 
> > > 你给我的信息不对，你这信息只是提示你已经安装了包，还有其他报错么？
> > 
> > 
> > 确实是没有其他的了 <img alt="截屏2023-12-12 下午9 35 21" width="608" src="https://private-user-images.githubusercontent.com/11916774/289876233-6a6288d5-2348-42b9-a2a2-6bd87b1eceeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzODk1MDAsIm5iZiI6MTcwMjM4OTIwMCwicGF0aCI6Ii8xMTkxNjc3NC8yODk4NzYyMzMtNmE2Mjg4ZDUtMjM0OC00MmI5LWEyYTItNmJkODdiMWVjZWViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDEzNTMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxNjU3NGIzYTBjNjJjMDkzNWE0YjZkMWRlMmM1ODAyMGY3NGMyZDk5MjllNDA4YjJjYjVjNWQ2Y2I0Mzk3OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NmcA9IPMbH28cfmuKIEvA25lDPnw6Nya-HAuzTVTzIA">
> 
> 我这条命令需要改变的，因为python环境安装的路径不一样，你点击软件的安装后看下你弹出的终端输出是什么 正常来说，你更新完pip，点击安装后，在终端的输出就自动安装所需的model了。 还有就是。。macos需要敲一条给予权限的命令，然后再打开软件。不知道你有没有完成这一步。 首页readme里点下macos，看下其中install的阅读文件。他有说明需要你敲一条给予权限的命令。

可以使用了，感谢。
