### ISSUE TITLE
欲使用 rwkv.cpp 推理应如何填写 Strategy ？本项目是否存在在线文档？

### ISSUE THREAD

**Issue by PJ-568** [josStorer/RWKV-Runner#239]
假如我想在 switch-model 时使用 rwkv.cpp 进行推理，我应该在 Strategy 填写什么？

是 `"strategy":"rwkv.cpp fp16"` ？

![示例](https://github.com/josStorer/RWKV-Runner/assets/63788100/024409f8-1f4c-4ca7-b58b-a346227fe971)

我好像没有找到可填写参数的完整列表。如果能够建立在线文档描述完整描述所有可选参数和文件释义、用法，或许能减少许多 Issue 。若有构建在线文档的需求，我愿意出一份力。

**Comment by josStorer** [comment]
载入模型时会提示 strategy is ignored

**Comment by josStorer** [comment]
忘记提醒了, 目前版本, 需要python main.py --rwkv.cpp 以激活rwkv.cpp模式, 然后才能正常载入.bin模型

**Comment by josStorer** [comment]
另外 `python main.py -h`可以查看所有参数和说明
