### ISSUE TITLE
用int8的话，输出token之前会卡一会儿，用fp16就不会。

### ISSUE THREAD

**Issue by doxtor6** [josStorer/RWKV-Runner#24]
模型使用的是7B从fp16转换到i8的模型。

内存和显存都够。但是开始产生token之前会等很久，token产生的速度也很快。

**Comment by doxtor6** [comment]
关闭cuda算子加速可以有效解决该问题，可能是这方面的兼容性问题。

**Comment by josStorer** [comment]
是什么显卡

**Comment by doxtor6** [comment]
3060 12G

**Comment by josStorer** [comment]
3060 12G推荐用10G-7B这个设置
第一个回答出的慢是正常的，后续速度正常就没问题

**Comment by doxtor6** [comment]
后续的回答出的还是挺慢的。。。不过不是特别严重的问题。

**Comment by BlinkDL** [comment]
策略需要优化一下 @josStorer 做个 12G 策略吧

**Comment by josStorer** [comment]
@BlinkDL 目前10G显存已经足够使用完整的int8 7B模型了，所以没法再针对12G显存改进了，目前的12G策略是跑14B的

**Comment by josStorer** [comment]
@doxtor6 加一下我QQ 1466587594 我给你远程看一下

**Comment by doxtor6** [comment]
好，已加。

**Comment by josStorer** [comment]
v1.1.0已加入模型状态缓存提速

**Comment by doxtor6** [comment]
感受到了，效果还不错！不过我感觉我还是得换张显卡以获得更好的体验。
