### ISSUE TITLE
M1 32 GB crashes with RWKV-5-World-3B-v2-20231118-ctx16k

### ISSUE THREAD

**Issue by rxjx** [josStorer/RWKV-Runner#241]
The error is:
/AppleInternal/Library/BuildRoots/0032d1ee-80fd-11ee-8227-6aecfccc70fe/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:126: failed assertion `[MPSNDArrayDescriptor sliceDimension:withSubrange:] error: the range subRange.start + subRange.length does not fit in dimension[2] (256)'

Happens on any input longer than a few sentences.

**Comment by josStorer** [comment]
try to switch Strategy to WebGPU or WebGPU(Python)

**Comment by rxjx** [comment]
Thanks! WebGPU worked.

**Comment by josStorer** [comment]
You have to switch to WebGPU (Python) to specify a custom tokenizer. The regular WebGPU mode is implemented in Rust, and there are currently some limitations in support for custom tokenizers.
