### ISSUE TITLE
Mac使用MPS加速，第二轮对话时程序会报错退出。

### ISSUE THREAD

**Issue by eyaeya** [josStorer/RWKV-Runner#250]
### 环境
> 电脑环境：MacBook Pro M3 Max 64GB统一内存
> 所用模型：[rwkv_v5.2_7B_role_play_16k.pth](https://huggingface.co/xiaol/RWKV-v5.2-7B-Role-play-16k/tree/main) （点击链接可下载）

#### 1、在Runner中配置模型，选择Strategy为MPS并启动。（成功）
![1](https://github.com/josStorer/RWKV-Runner/assets/5821137/0a1cc7dc-0ca2-4861-a323-f08ebc8b8c26)

#### 2、载入模型。（成功）
![2](https://github.com/josStorer/RWKV-Runner/assets/5821137/8336a336-e0bc-4b82-b2ee-7df993abfa0f)

#### 3、测试对话（第一轮）（成功）
![3](https://github.com/josStorer/RWKV-Runner/assets/5821137/8359e84d-eb45-4e8d-82d0-e7b91ebcdd00)

#### 4、测试对话（第二轮），程序报错退出。（失败）
![4](https://github.com/josStorer/RWKV-Runner/assets/5821137/d307f69e-720e-453f-b029-afe3f8ad41fb)

**报错退出前，终端提示：**

`/AppleInternal/Library/BuildRoots/0032d1ee-80fd-11ee-8227-6aecfccc70fe/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:126: failed assertion [MPSNDArrayDescriptor sliceDimension:withSubrange:] error: the range subRange.start + subRange.length does not fit in dimension[2] (256)'`
`[1]    2862 abort      /opt/homebrew/Cellar/python@3.10/3.10.13_1/bin/python3.10  --port 8000 --host`

**Comment by josStorer** [comment]
V5 MPS有点问题, 可以先用WebGPU或者 WebGPU(Python)

**Comment by eyaeya** [comment]
> V5 MPS有点问题, 可以先用WebGPU或者 WebGPU(Python)

需要先转换模型吗？
关于WebGPU的依赖，似乎没找到文档，我还没摸明白，求教。

**Comment by josStorer** [comment]
普通WebGPU可以直接转换并使用, 已经内置了转换和执行工具

**Comment by eyaeya** [comment]
> 普通WebGPU可以直接转换并使用, 已经内置了转换和执行工具

使用内置转换工具，将 .pth 转换为 .st 后，使用WebGPU运行报错：

`切换模型失败 - {"detail":"failed to load: web_rwkv_py not found, install it from https://github.com/cryscan/web-rwkv-py"}`

**Comment by josStorer** [comment]
你截图这个是 WebGPU (Python)的报错, 这个模式windows开箱即用, 但是mac要手动安装 https://github.com/cryscan/web-rwkv-py

如果你不知道怎么安装, 可以用普通的, WebGPU模式, 这个模式有什么报错吗

你截图这个状态, 再点一下运行

**Comment by eyaeya** [comment]
> 你截图这个是 WebGPU (Python)的报错, 这个模式windows开箱即用, 但是mac要手动安装 https://github.com/cryscan/web-rwkv-py
> 
> 如果你不知道怎么安装, 可以用普通的, WebGPU模式, 这个模式有什么报错吗
> 
> 你截图这个状态, 再点一下运行

如图，此为选择“WebGPU”的运行情况。
![02](https://github.com/josStorer/RWKV-Runner/assets/5821137/25274f7b-c7ea-4e13-8d16-bae27462012d)

**Comment by josStorer** [comment]
先把所有终端关了, 因为占着端口, 服务启动不起来

**Comment by eyaeya** [comment]
顺利通过了，跪谢作者！🎉

![03](https://github.com/josStorer/RWKV-Runner/assets/5821137/0a6a3aed-8c74-4898-9fe1-2acb559d53b0)

-----------------------

### 关联问题请教：
WebGPU 相较于 MPS，在macOS中的性能，差异非常大吗？
（因为我感觉到，WebGPU的速度非常的快，似乎和MPS没有差异）

**Comment by josStorer** [comment]
WebGPU模式是cryscan自己写的wgsl算子: https://github.com/cryscan/web-rwkv/blob/main/src/shaders
在mac下使用metal的计算着色器

而MPS模式目前调用普通的pytorch API实现, 实现的相对随便一点?

Metal和MPS实现孰优孰劣不好说: `https://github.com/pytorch/pytorch/issues/86076`

**Comment by eyaeya** [comment]
> WebGPU模式是cryscan自己写的wgsl算子: https://github.com/cryscan/web-rwkv/blob/main/src/shaders 在mac下使用metal的计算着色器
> 
> 而MPS模式目前调用普通的pytorch API实现, 实现的相对随便一点?
> 
> Metal和MPS实现孰优孰劣不好说: `https://github.com/pytorch/pytorch/issues/86076`

非常感谢，我去阅读了解。
我将Close这个主题。
