### ISSUE TITLE
macOS下没办法用MPS进行续写

### ISSUE THREAD

**Issue by Retromemory** [josStorer/RWKV-Runner#256]
最新的14.2.1系统，目前WebGPU功能正常，以MPS在配置里可以正常启动加载好模型，但任何续写生成都会导致load failed, 且弹窗Python意外终止，Terminal提示如下
Sources/MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:126: failed assertion `[MPSNDArrayDescriptor sliceDimension:withSubrange:] error: the range subRange.start + subRange.length does not fit in dimension[2] (256)'
zsh: abort      python3 ./backend-python/main.py --port 8000 --host 0.0.0.0

**Comment by josStorer** [comment]
RWKV5的MPS没支持, WebGPU很快无脑用
