### ISSUE TITLE
Support calling Python in the specified conda environment?

### ISSUE THREAD

**Issue by Pevernow** [josStorer/RWKV-Runner#26]
Most AI programmers are generally accustomed to using Conda to manage different versions of Python environments to reduce dependency conflicts

Can we support calling Python in the specified conda environment?

**Comment by Chrisma-98** [comment]
totally agree!!

**Comment by josStorer** [comment]
https://github.com/josStorer/RWKV-Runner/releases/tag/v1.1.3
