### ISSUE TITLE
在webUI里加个类似ComfyUI的功能

### ISSUE THREAD

**Issue by lampcccc** [josStorer/RWKV-Runner#266]
写小说真的不太行，叙事琐碎，剧情平淡，上下文关联不强，文笔太差了，签约都过不了。

弄个节点功能，自定义形式的，像角色关系图，细纲，大纲这些东西分成若干个节点。
每一个属性对应一个节点，相互关联，生成的内容可以根据需要进行定向生成。

![LOO36C4(02R`7D KJGY2G2V](https://github.com/josStorer/RWKV-Runner/assets/129349778/74ed798d-bb8f-4d7d-a736-19b16ca4f715)

**Comment by josStorer** [comment]
你是完全使用AI生成, 不做任何修改直接投稿的吗

**Comment by lampcccc** [comment]
肯定修改了，不然没法看

**Comment by lampcccc** [comment]
随便问下，是用的https://github.com/cryscan/web-rwkv-py/tree/main/src，这个web功能吗，没看到相关文件啊？

**Comment by lampcccc** [comment]
哥们。几个月的努力分文不值，相当痛苦。

自带的《背影》这个故事，生成1000字，看看就知道，上下文完全狗屁不通。

不做设定的提示词，完全是瞎写。
而且提示词有时候也不好用。

**Comment by josStorer** [comment]
逻辑是要自己把控的, 目前AI主要是辅助生成创意, 基于细纲扩写, 水字数

你要自己定好整个故事大纲, 然后自己拆分成一个个章节编写细纲, 拆分的过程可以用AI辅助生成想法

之后自己把控细纲与大纲间的逻辑

再基于细纲, 让AI生成各节的文章, 自己再进一步调整逻辑走向 (这个过程建议在续写页面, 右上角, 选择指令模式; 或者, 选择一些针对相关功能微调的模型, 例如: https://huggingface.co/xiaol/RWKV-4-world-one-state-novel-tuned-65k)
