### ISSUE TITLE
更改API主机地址后无法加载模型

### ISSUE THREAD

**Issue by xzldragones** [josStorer/RWKV-Runner#27]
设置界面将API主机地址由127.0.0.1更改为本机真实IP后，无法加载模型。

**Comment by josStorer** [comment]
要公开让其他ip访问的话，填0.0.0.0

**Comment by xzldragones** [comment]
设置界面将API主机地址由127.0.0.1更改为0.0.0.0后，已可正常加载模型并可共享给局域网中的其他电脑使用。感谢！
