### ISSUE TITLE
FileNotFoundError: Could not find module 'G:\ai\backend-python\wkv_cuda\wkv_cuda.pyd

### ISSUE THREAD

**Issue by i3587616** [josStorer/RWKV-Runner#279]
win10 ,使用自定义CUDA算子加速
报错：Detected CUDA files, patching ldflags
Emitting ninja build file G:\ai\backend-python\wkv_cuda\build.ninja...
Building extension module wkv_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module wkv_cuda...
Could not find module 'G:\ai\backend-python\wkv_cuda\wkv_cuda.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
Traceback (most recent call last):
  File "G:\ai\backend-python\routes\config.py", line 73, in switch_model
    RWKV(model=body.model, strategy=body.strategy, tokenizer=body.tokenizer),
  File "G:\ai\backend-python\utils\rwkv.py", line 559, in RWKV
    from rwkv_pip.beta.model import (
  File "G:\ai\backend-python\rwkv_pip\beta\model.py", line 85, in <module>
    load(
  File "G:\ai\py310\Lib\site-packages\torch\utils\cpp_extension.py", line 1306, in load
    return _jit_compile(
  File "G:\ai\py310\Lib\site-packages\torch\utils\cpp_extension.py", line 1736, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "G:\ai\py310\Lib\site-packages\torch\utils\cpp_extension.py", line 2137, in _import_module_from_library
    torch.ops.load_library(filepath)
  File "G:\ai\py310\Lib\site-packages\torch\_ops.py", line 933, in load_library
    ctypes.CDLL(path)
  File "ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'G:\ai\backend-python\wkv_cuda\wkv_cuda.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by josStorer** [comment]
是否使用了自定义python, 建议不要用自定义的, 用自动下载的
自定义的需要自己编译, 比较麻烦

**Comment by i3587616** [comment]
> 是否使用了自定义python, 建议不要用自定义的, 用自动下载的 自定义的需要自己编译, 比较麻烦

我是用的RWKV-Runner_windows_x64.exe自已执行的下载的python.然后他不是没有库，G:\ai\py310\Include
这个下面的是空的，然后我就看了python的版本是3.10.11就去官方下载了，然后选择了那个下载，把G:\ai\py310\Include
下的文件补全了而已。如果没有使用自定义CUDA算子加速。而是cuda。就不会报错

**Comment by i3587616** [comment]
我python执行是正常的，就是少了python-dev,然后从自定义里把\py310\Include里的文件给补全了，这样不行吗。我得重新在装一次python是吗

**Comment by i3587616** [comment]
wkv_cuda.pyd' (or one of its dependencies) 是不是wkv_cuda.pyd需要引入什么，它需要哪些类库

**Comment by i3587616** [comment]
import av 之类的运行是正常的，我以前有用过python的。不会报no module

**Comment by i3587616** [comment]
> 是否使用了自定义python, 建议不要用自定义的, 用自动下载的 自定义的需要自己编译, 比较麻烦
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
torch version 错了，后面改pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117就没
错了,问解决定,谢了.
