### ISSUE TITLE
申请增加Python环境配置项

### ISSUE THREAD

**Issue by Chrisma-98** [josStorer/RWKV-Runner#28]
现有1.0.8版本中未增加Python环境自定义管理。
对于一切用户均在运行目录里下载和配置一个带torch的py3.10环境，对于小白很友好。
但希望发开自定义环境配置，电脑里已经有5个python，4个torch啦。。。。

**Comment by josStorer** [comment]
cuda算子对python版本和torch版本均有要求，所以才强制的

**Comment by wikeeyang** [comment]
附一下上面 Chrisma-98 的提议。可以看出来，版主是技术牛人，RWKV-Runner、chatGPTBox、selfhostedAI几个开源应用水平都很高！估计是不太愿意浪费时间、重重复复的回答或解决一些简单的技术问题。但其实这个社会绝大部分人都是技术小白，或者都是从小白开始慢慢成长的。我是老IT、老理工，60后，以前学的代码和技术都落伍了。我也是今年才开始接触各种大模型，接触两三月后，看来国内RWKV和ChatGLM技术以及用户环境是比较好的，我都是把各家模型从huggingface.co上手工下载，并统一放在一个固定目录，用过LLaMA、GPT4ALL、ChatCSDN、ChatYuan、MOSS、Replitcode、StableDiffusion、PaddleSpeech、Whisper等等，目录光模型就占150GB左右的空间，Python有3.9、3.10、3.11三个可以用自己写的BAT脚本切换的版本，CUDA有11.7、11.8、12.1三个版本，cudnn有8.7、8.8、8.9三个版本，这些加起来也有30-50GB了，可以通过改变环境参数切换，最费事的一次测试就是把ChatGLM-6B和PaddleSpeech整合起来，可以通过API调用，实现基于Web的语音聊天，为此还在自己的Python3.9环境，用C++重新编译了第三方ctc_decoders包，看了里面很多源码后，发现其实这是PaddleSpeech很小的一个坑，无非就是Linux和Windows环境的差异问题，其实百度技术人员多花半小时，就能给Windows平台的试用人员提供更友好的测试环境。我看了版主的RWKV-Runner，第一想法就是希望能可以自己配置模型路径和Pathon环境，ChatRWKV_PC是可以自己选模型，GPT4ALL也是，当然，我也充分理解Python各种依赖包的环境是比较复杂。只是建议，最终由版主考虑决定，谢谢版主开源分享！

**Comment by josStorer** [comment]
我可以在设置里添加自定义模型目录和python解释器路径，后面版本加吧

**Comment by wikeeyang** [comment]
谢谢！给您点赞！模型路径及模型加载自定义会相对简单一些，Python解释器自定义后，后面依赖包检查可能会比较复杂一些，可以在requirements.txt注释一下，或者通过PYthon脚本检查一下关键的依赖。希望应用越做越好！

**Comment by Chrisma-98** [comment]
> 我可以在设置里添加自定义模型目录和python解释器路径，后面版本加吧

感谢大佬回复和考虑跟进。

**Comment by josStorer** [comment]
https://github.com/josStorer/RWKV-Runner/releases/tag/v1.1.3

**Comment by wikeeyang** [comment]
点赞。。。
