### ISSUE TITLE
RWKV 1.5B is insanely good at it scale

### ISSUE THREAD

**Issue by yhyu13** [josStorer/RWKV-Runner#3]
Even though it does not directly point out that AI does no exists in the year 1010. But it does reason a lot philosoically.

![RWKV-Runner_windows_x64_rZox1v8w3T](https://github.com/josStorer/RWKV-Runner/assets/19365678/58a8f31b-93f2-454b-a23f-17a6cb2aa6e6)

Mostly LLaMA tuned model simply spit out, "It's hard to predit what AI will be like because 1010 is xxx years in the future," LOL

**Comment by luxu1220** [comment]
![image](https://github.com/josStorer/RWKV-Runner/assets/24969222/5bb7b56d-dc77-4d3b-bc2f-9aea1d2b3867)
