### ISSUE TITLE
Network error when going to sleep or hibernate. 

### ISSUE THREAD

**Issue by Kataphractoi** [josStorer/RWKV-Runner#313]
I'm relatively unskilled when it comes to this thing (my installation was simply by following the GUI and the provided instructions) 

But I've noticed that when a message is still generating but the computer has been put to sleep or hibernate, the generation of the message would be cut short and an "[Network Error]" error message would pop up, necessitating a regeneration to get a similar message, but ultimately the original cut off message would be lost. 

This is odd to me, as usually computation can be picked up from saved data during sleep or hibernate as if nothing happened for most programs, even with other offline LLM runners like GPT4ALL. 

If there's a quick patch or something, please let me know, otherwise, I see this as a relatively low priority issue, being that its a simple Quality Of Life request. The fix for me now is to just regen for a complete message.

**Comment by josStorer** [comment]
This could be a webview behavior, RWKV-Runner client is developed based on webview, and webview may interrupt ongoing requests when it goes to sleep.

**Comment by Kataphractoi** [comment]
Got it, thank you.

**Comment by Kataphractoi** [comment]
Doesn't seem to be an issue inherent with RWKV Runner. May be a webview issue. Solution: keep the computer on and plugged in.
