### ISSUE TITLE
LoRa微调问题: 训练一段时间后 ，ubantu窗口和wsl窗口就关闭了 

### ISSUE THREAD

**Issue by wanYuXuan** [josStorer/RWKV-Runner#319]
大约训练半小时左右出现
并没有报什么错误资讯，linux窗口闪退，GPU CUDA占用从100%降为0
训练参数都为默认未修改
模型基底为 RWKV-x060-World-3B-v2-20240228-ctx4096.pth
训练数据大小为 3.5G 左右  实例格式，一百六十万行数据
显卡为 4090 24GB
内存为 64G
wslcong配置划分 memory=32GB swap=16GB

##############################
 NVIDIA-SMI 535.103                Driver Version: 537.13       CUDA Version: 12.2

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Jun_13_19:16:58_PDT_2023
Cuda compilation tools, release 12.2, V12.2.91
Build cuda_12.2.r12.2/compiler.32965470_0

############################

torch                    2.2.1+cu121
torchaudio               2.2.1+cu121
torchmetrics             1.3.2
torchvision              0.17.1+cu121

**Comment by josStorer** [comment]
这个我也不清楚是什么原因导致的, 此前没有人反馈的, 训练得到的lora你可以选择后继续训练先
