### ISSUE TITLE
MacOS版本的停止按钮失效？

### ISSUE THREAD

**Issue by Retromemory** [josStorer/RWKV-Runner#321]
今天更新1.7.7之后发现的，之前1.7.5同一个配置没问题，WebGPU，一旦模型开始输出文本，只能等待全部输出完毕，没办法像之前一样点击停止按钮来终止输出。

停止按钮只有在点击生成 - 模型尚未输出文字这段期间可以打断输出，输出文本期间，停止按钮直接不出现（依然保持生成按钮），同为1.7.7的Windows版本没这个问题

**Comment by josStorer** [comment]
先回退到1.7.5, 等1.7.8的更新, 是这个issue引起的: https://github.com/Ai00-X/ai00_server/issues/90, 那边已经修复
