### ISSUE TITLE
切换.bin模型失败

### ISSUE THREAD

**Issue by xwxYa** [josStorer/RWKV-Runner#322]
使用版本为1.7.8，配置为GPU-4G-3B-CN，使用的模型叫pvtorchmodel-00003-of-00003.bin，Strategy为CPU（rwkv.cpp)
4060 8G显卡，32G内存，50G虚拟内存

报错如下
--- 0.43301892280578613 seconds ---
INFO:     Started server process [18132]
INFO:     Waiting for application startup.
torch found: D:\software\RWKV\py310\Lib\site-packages\torch\lib
torch set
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:50805 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:50805 - "GET /status HTTP/1.1" 200 OK
Updated Model Config: max_tokens=4100 temperature=1.0 top_p=0.3 presence_penalty=0.0 frequency_penalty=1.0 penalty_decay=None top_k=None global_penalty=None
INFO:     127.0.0.1:50805 - "POST /update-config HTTP/1.1" 200 OK
Strategy Devices: {''}
state cache enabled
Using rwkv.cpp, strategy is ignored

D:\a\rwkv.cpp\rwkv.cpp\rwkv_file_format.inc:93: header.magic == 0x67676d66
Invalid file header
D:\a\rwkv.cpp\rwkv.cpp\rwkv_model_loading.inc:158: rwkv_fread_file_header(file.file, model.header)

D:\a\rwkv.cpp\rwkv.cpp\rwkv.cpp:63: rwkv_load_model_from_file(file_path, *ctx->model)
rwkv_init_from_file failed, check stderr
Traceback (most recent call last):
  File "D:\software\RWKV\backend-python\routes\config.py", line 73, in switch_model
    RWKV(model=body.model, strategy=body.strategy, tokenizer=body.tokenizer),
  File "D:\software\RWKV\backend-python\utils\rwkv.py", line 636, in RWKV
    model = Model(model, strategy)
  File "D:\software\RWKV\backend-python\rwkv_pip\cpp\model.py", line 9, in __init__
    self.model = rwkv_cpp_model.RWKVModel(self.library, model_path)
  File "D:\software\RWKV\backend-python\rwkv_pip\cpp\rwkv_cpp_model.py", line 66, in __init__
    self._ctx: rwkv_cpp_shared_library.RWKVContext = self._library.rwkv_init_from_file(model_path, thread_count)
  File "D:\software\RWKV\backend-python\rwkv_pip\cpp\rwkv_cpp_shared_library.py", line 146, in rwkv_init_from_file
    raise ValueError("rwkv_init_from_file failed, check stderr")
ValueError: rwkv_init_from_file failed, check stderr

INFO:     127.0.0.1:50806 - "POST /switch-model HTTP/1.1" 500 Internal Server Error

**Comment by josStorer** [comment]
必须是RWKV架构

**Comment by josStorer** [comment]
pvtorchmodel-00003-of-00003.bin
这个模型名称, 看起来是某个模型的三分之一, 并且它可能是任何模型, pytorch还打错了, 更一步对模型来源和使用方式产生疑惑
