### ISSUE TITLE
Win10 無法啟動

### ISSUE THREAD

**Issue by AlliotQ** [josStorer/RWKV-Runner#327]
RWKV-Runner_windows_x64.exe 啟動後
產生了部分資料夾
![image](https://github.com/josStorer/RWKV-Runner/assets/20041412/7603ea2e-ab18-4a8c-8a40-aa82df5de669)
之後就完全沒有反應了
有什麼方法查錯誤LOG?

這邊不確定有沒有關係
電腦的outlook目前也打不開
看紀錄發現outlook有錯誤紀錄是
ucrtbase.dll 的 0xc0000409
印象有查到之前問題
提到有依賴ucrtbase.dll 看到順便提一下

**Comment by josStorer** [comment]
试试手动安装webview2
https://developer.microsoft.com/zh-TW/microsoft-edge/webview2

**Comment by AlliotQ** [comment]
等等會在重新確認
但是印象webview2之前已經有安裝過
sfc /scannow也跑過

之前的狀況是
第一次啟動有看到成功開啟畫面視窗
但是被判斷成病毒刪掉EXE檔
之後設定好再重新安裝時就打不開了

**Comment by josStorer** [comment]
添加信任:
Windows Security -> Virus & threat protection -> Manage settings -> Exclusions -> Add or remove exclusions -> Add an exclusion -> Folder -> RWKV-Runner

**Comment by AlliotQ** [comment]
感謝 真的是防毒設定問題
結果必須要設定到EXE在的那個資料夾
原本排除設定到了再上一層想說可以
