### ISSUE TITLE
升级到1.09版又报Python依赖缺失，还需要安装VC++14？

### ISSUE THREAD

**Issue by Juniy** [josStorer/RWKV-Runner#33]
![image](https://github.com/josStorer/RWKV-Runner/assets/11728986/b6c72fb3-da43-487a-ab19-7296c4595e28)
如图

**Comment by Misaka-Mikoto-Tech** [comment]
其实是py310目录不全，缺少 include 和 Libs 目录，从别的地方copy过去再编译就通过了

**Comment by josStorer** [comment]
使用v1.1.0最新版，1.1.0版本直接内置了部份依赖

**Comment by Juniy** [comment]
py310目录是全的，之前版本1.07版本是运行正常的，不过无所谓了，升级1.10版本运行正常了
