### ISSUE TITLE
服务启动成功，但是访问报500

### ISSUE THREAD

**Issue by lascyb** [josStorer/RWKV-Runner#342]
![image](https://github.com/josStorer/RWKV-Runner/assets/37490770/77b784f0-497d-449d-b7e8-25413f5ff0d8)

**Comment by lascyb** [comment]
--- 0.8576188087463379 seconds ---
INFO:     Started server process [22196]
INFO:     Waiting for application startup.
torch found: G:\AI\RWKV-Runner-Backend\py310\Lib\site-packages\torch\lib
torch set
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:31858 - "GET / HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:31858 - "GET /status HTTP/1.1" 200 OK
INFO:     127.0.0.1:31858 - "OPTIONS /update-config HTTP/1.1" 200 OK
INFO:     127.0.0.1:31857 - "OPTIONS /switch-model HTTP/1.1" 200 OK
state not loaded
Updated Model Config: max_tokens=4100 temperature=1.0 top_p=0.3 presence_penalty=0.0 frequency_penalty=1.0 penalty_decay=None top_k=None global_penalty=None state=None
INFO:     127.0.0.1:31857 - "POST /update-config HTTP/1.1" 200 OK
Strategy Devices: {'cuda'}
state cache enabled
G:\AI\RWKV-Runner-Backend\py310\Lib\site-packages\_distutils_hack\__init__.py:11: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
  warnings.warn(
G:\AI\RWKV-Runner-Backend\py310\Lib\site-packages\_distutils_hack\__init__.py:26: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
cannot import name 'packaging' from 'pkg_resources' (G:\AI\RWKV-Runner-Backend\py310\Lib\site-packages\pkg_resources\__init__.py)
Traceback (most recent call last):
  File "G:\AI\RWKV-Runner-Backend\backend-python\routes\config.py", line 73, in switch_model
    RWKV(model=body.model, strategy=body.strategy, tokenizer=body.tokenizer),
  File "G:\AI\RWKV-Runner-Backend\backend-python\utils\rwkv.py", line 644, in RWKV
    from rwkv_pip.model import (
  File "G:\AI\RWKV-Runner-Backend\backend-python\rwkv_pip\model.py", line 84, in <module>
    from torch.utils.cpp_extension import load
  File "G:\AI\RWKV-Runner-Backend\py310\Lib\site-packages\torch\utils\cpp_extension.py", line 25, in <module>
    from pkg_resources import packaging  # type: ignore[attr-defined]
ImportError: cannot import name 'packaging' from 'pkg_resources' (G:\AI\RWKV-Runner-Backend\py310\Lib\site-packages\pkg_resources\__init__.py)

INFO:     127.0.0.1:31858 - "POST /switch-model HTTP/1.1" 500 Internal Server Error

**Comment by josStorer** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/15863

`./py310/python -m pip install setuptools==69.5.1`

**Comment by lascyb** [comment]
解决了，谢谢
