### ISSUE TITLE
显卡能使用计算卡吗？

### ISSUE THREAD

**Issue by Xiao-yux** [josStorer/RWKV-Runner#343]
![image](https://github.com/josStorer/RWKV-Runner/assets/79674967/2e0697f4-5392-46e8-a091-c1ac9527fab4)
我这里有一张计算卡，应该怎么使用它
![image](https://github.com/josStorer/RWKV-Runner/assets/79674967/73361f7d-14e4-4823-9673-9f1341b2963d)
软件启动后没有识别到

**Comment by josStorer** [comment]
要修改驱动模式

**Comment by Xiao-yux** [comment]
![image](https://github.com/josStorer/RWKV-Runner/assets/79674967/255df0d5-93e7-44a6-a545-36114eea06ba)
打了个驱动，识别到了
