### ISSUE TITLE
转换模型失败

### ISSUE THREAD

**Issue by haisheng666** [josStorer/RWKV-Runner#35]
转换失败，exit stauts 1，管理员运行的，帮看一下怎么回事

**Comment by Douding521** [comment]
我也是一样的问题,你现在找到处理方法了吗?

**Comment by josStorer** [comment]
使用v1.1.0最新版，这个错误一般是脚本文件没下载完成，1.1.0版本直接内置了

**Comment by josStorer** [comment]
请使用最新版， 注意路径不要有空格，是golang的bug
