### ISSUE TITLE
from numpy import BUFSIZE ImportError: cannot import name 'BUFSIZE' from 'numpy' 

### ISSUE THREAD

**Issue by lwstudy** [josStorer/RWKV-Runner#353]
在lora训练前的环境安装也没看到什么问题。
不太清楚为什么会报这个，是版本numpy不对？似乎是无法运行NumPy 2.0.0，但是我该如何降低版本呢？
或者有什么其他办法让我能训练，想尝试一下。
from numpy import BUFSIZE
ImportError: cannot import name 'BUFSIZE' from 'numpy' (/usr/local/lib/python3.10/dist-packages/numpy/__init__.py)

环境：1.8.4 RWKV-Runner
模型：RWKV-4-World-0.1B-v1-20230520-ctx4096.pth

**Comment by lwstudy** [comment]
头大，查了下是6月16更新了NumPy 2.0版本。

**Comment by josStorer** [comment]
手动降一下numpy版本吧

**Comment by josStorer** [comment]
如果是windows下, 点击顶部的WSL标签, 然后输入 `pip install numpy==1.26.4`

**Comment by lwstudy** [comment]
OK，这个办法的确的确可以暂时解决，谢谢。

**Comment by josStorer** [comment]
https://github.com/josStorer/RWKV-Runner/releases/tag/v1.8.5

**Comment by Lsy235** [comment]
You can try pip install numpy==1.23.5. This deal with my problem.
