### ISSUE TITLE
点击运行后显示没有模型

### ISSUE THREAD

**Issue by Order15** [josStorer/RWKV-Runner#358]
![B(92~Q%~N%` F17~0KTY5(L](https://github.com/josStorer/RWKV-Runner/assets/112788228/322505bd-bbf0-44e9-8421-00389794aee7)
![IQ~VFYQ6RYM~P068J}8GO)6](https://github.com/josStorer/RWKV-Runner/assets/112788228/714f4814-f613-47ee-89ec-ec43ae3b628c)
![W_%TYYO7N6UV8S4T3SDXZ$U](https://github.com/josStorer/RWKV-Runner/assets/112788228/80ab2f7b-5bc9-45e6-b19c-e64c32d30437
点击运行后显示没有模型

**Comment by Order15** [comment]
![Uploading W_%TYYO7N6UV8S4T3SDXZ$U.png…]()

**Comment by josStorer** [comment]
#359
