### ISSUE TITLE
转换模型失败

### ISSUE THREAD

**Issue by Douding521** [josStorer/RWKV-Runner#36]
一直提示转换模型失败

**Comment by josStorer** [comment]
使用的是什么版本，错误是exit1吗，使用v1.1.0最新版，这个错误一般是脚本文件没下载完成，1.1.0版本直接内置了

**Comment by Douding521** [comment]
使用1.1.0版git上下载的没法安装py 命令行闪一下就没了

**Comment by josStorer** [comment]
麻烦录个屏，或者进群283430436详细截图沟通

**Comment by josStorer** [comment]
尝试用管理员权限执行exe，目前尚不明确为什么一些电脑需要管理员权限

**Comment by josStorer** [comment]
请使用最新版， 注意路径不要有空格，是golang的bug
