### ISSUE TITLE
使用自定义CUDA算子加速会输出莫名其妙的文字，关掉就正常输出了

### ISSUE THREAD

**Issue by SunshineboyZj** [josStorer/RWKV-Runner#37]
请问这是什么情况呀
![使用自定义CUDA算子加速](https://github.com/josStorer/RWKV-Runner/assets/81549837/c5f8f208-ffbf-4036-abdc-b915bb223fd2)
![莫名其妙的文字输出](https://github.com/josStorer/RWKV-Runner/assets/81549837/ada117c8-b163-4c3f-a50b-07a1fb120308)

**Comment by SunshineboyZj** [comment]
版本1.1.0
显卡：GTX1650 4G（notebook）

**Comment by josStorer** [comment]
更新显卡驱动

**Comment by SunshineboyZj** [comment]
> 更新显卡驱动

有时候点消息框右边的停止，上一条提问的回答还是在输出。新发送的问题也不会回应。不过这个是偶发性的问题

**Comment by SunshineboyZj** [comment]
> 更新显卡驱动

有时候点消息框右边的停止，上一条提问的回答还是在输出。新发送的问题也不会回应。不过这个是偶发性的问题

**Comment by SunshineboyZj** [comment]
> 更新显卡驱动

有时候点消息框右边的停止，上一条提问的回答还是在输出，新发送的问题也不会回应。不过这个是偶发性的问题，偶尔出现

**Comment by josStorer** [comment]
这个是前端中断信号的问题，小问题，这个项目重在通用的后端，前端只做效果演示
