### ISSUE TITLE
The MPS backend is supported on MacOS 12.3+.Current OS version can be queried using `sw_vers`

### ISSUE THREAD

**Issue by wudisong-hub** [josStorer/RWKV-Runner#388]
<img width="570" alt="image" src="https://github.com/user-attachments/assets/499002ee-acf4-4fd6-ad3e-6788b626ccfb">
mac使用出现异常，请教下该如何解决？使用的模型是
<img width="1024" alt="image" src="https://github.com/user-attachments/assets/bacfac4e-d6d2-4e25-b140-183325aedadc">

**Comment by josStorer** [comment]
用WebGPU Python, 速度更快，占用更低

**Comment by wudisong-hub** [comment]
您是指换一个模型吗？但是我的模型里没有这一款？是另外一模型文件地址吗？能否提供下？
<img width="1024" alt="image" src="https://github.com/user-attachments/assets/82f36c99-54e3-4d2e-939a-fec512f8e787">

**Comment by wudisong-hub** [comment]
感谢，我用我的window使用WebGPU(Python)可以了
