### ISSUE TITLE
请问如何搭载state

### ISSUE THREAD

**Issue by wudisong-hub** [josStorer/RWKV-Runner#391]
我使用的配置是GPU-2G-1B5-World，模型是RWKV-x060-ChnNovel-1B-20240807-ctx4096.st 但是并没有出现state的选择框

**Comment by yzxh24** [comment]
<img width="843" alt="image" src="https://github.com/user-attachments/assets/05920e1e-d06b-4721-a73b-2bc931194ef4">
不能选 CPU(rwkv.cpp) 那个模式。

**Comment by josStorer** [comment]
CPU和CUDA这两个模式支持动态state

**Comment by wudisong-hub** [comment]
好的 但是用CPU没有GPU快 我尝试下使用CPU
