### ISSUE TITLE
模型版本识别错误导致启动失败

### ISSUE THREAD

**Issue by zonde306** [josStorer/RWKV-Runner#407]
RWKV5 被识别成 RWKV7，导致启动失败
模型：[rwkv-5-h-world-7B.pth](https://hf-mirror.com/a686d380/rwkv-5-h-world)
版本：[v1.8.9](https://github.com/josStorer/RWKV-Runner/releases/tag/v1.8.9)
上一版正常

**Comment by josStorer** [comment]
好，下版本修复

**Comment by josStorer** [comment]
修了
