### ISSUE TITLE
模型转换失败

### ISSUE THREAD

**Issue by NeonBubbles** [josStorer/RWKV-Runner#44]
我已经运行了一个模型，现在打算运行另一个模型，结果就遇到了以下错误。我的版本是1.1.4，尝试过管理员运行也没用。

Could not import azure.core python package.
INFO:     Started server process [15024]
INFO:     Waiting for application startup.
torch found: C:\Users\clank\Downloads\py310\Lib\site-packages\torch\lib
torch set
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:49266 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:49268 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:49266 - "GET /status HTTP/1.1" 200 OK
INFO:     127.0.0.1:49266 - "OPTIONS /update-config HTTP/1.1" 200 OK
INFO:     127.0.0.1:49268 - "OPTIONS /switch-model HTTP/1.1" 200 OK
max_tokens=4100 temperature=1.2 top_p=0.5 presence_penalty=0.4 frequency_penalty=0.4
INFO:     127.0.0.1:49268 - "POST /update-config HTTP/1.1" 200 OK
RWKV_JIT_ON 1 RWKV_CUDA_ON 0 RESCALE_LAYER 6

Loading ./models/RWKV-4-Raven-3B-v11-Eng49%-Chn49%-Jpn1%-Other1%-20230429-ctx4096.pth ...
PytorchStreamReader failed reading zip archive: invalid header or archive is corrupted
INFO:     127.0.0.1:49266 - "POST /switch-model HTTP/1.1" 500 Internal Server Error

**Comment by josStorer** [comment]
由于文件过大，做校验时间太长，我没做校验功能

**Comment by NeonBubbles** [comment]
py310\Lib\site-packages [目录下[](url)](url)
<img width="524" alt="20230602002122592" src="https://github.com/josStorer/RWKV-Runner/assets/43613294/8259c47b-3dc8-459b-bd56-4fbcacff926b">

**Comment by NeonBubbles** [comment]
我把v11那个模型删了重新下，现在用之前下好的v12就可以运行，但是终端第一行总是提示Could not import azure.core python package.，虽然好像不影响使用，但强迫症犯了，这个怎么解决呢

**Comment by josStorer** [comment]
那个提示是其他包的，暂时无解
