### ISSUE TITLE
关于int8量化加速的问题

### ISSUE THREAD

**Issue by irasin** [josStorer/RWKV-Runner#45]
关于int8量化，有几个问题想请教一下

1. int8量化模型是什么如何生成的？使用GPTQ/RPTQ之类的方法，还是说仅仅对权重进行pertensor/perchannel的量化？
2. int8量化模型是如何推理的？是在kernel中进行将权重反量化回fp16，然后再和fp16的activation相乘吗？还是说activation也被量化乘int8了，进行int8 * int8的乘法？

烦请指教，谢谢

**Comment by josStorer** [comment]
建议去RWKV官方仓库问相关问题，该问题与本仓库无关
https://github.com/BlinkDL/ChatRWKV
https://github.com/BlinkDL/RWKV-LM
