### ISSUE TITLE
Feature Request: Log all prompts and responses for API calls

### ISSUE THREAD

**Issue by cryscan** [josStorer/RWKV-Runner#46]
Some platform does not expose their full prompt, which makes it difficult for debugging. Having a local log would be nice.

**Comment by cabralski** [comment]
CC: @josStorer 

Absolutely. Currently, the prompt for the **Chat** mode on `python-backend` is as follows:

```txt
The following is a coherent verbose detailed conversation between a girl named {bot} and her friend {user}.
{bot} is very intelligent, creative and friendly.
{bot} is unlikely to disagree with {user}, and {bot} doesn't like to ask {user} questions.
{bot} likes to tell {user} a lot about herself and her opinions.
{bot} usually gives {user} kind, helpful and informative advices.
```

Some releases of RWKV such as RWKV-4-World, state that Alice/Bob should **not be used**, but instead: Human/Bot, User/AI, Question/Answer, see [this model card](https://huggingface.co/BlinkDL/rwkv-4-world) for the exact statement.

There are plenty of "configuration" endpoints now, such as:
```py
@router.post("/switch-model")
def switch_model(body: SwitchModelBody, response: Response):
    ...
```

We could make one more endpoint such as:
```py
@router.post("/change-chat-prompt")
def change_chat_prompt(body: ChangeChatPromptBody):
    ...
```
..that allows for changes the prompt, as well as specifying what `stop` is going to be. That will also require some UI changes.

**Comment by josStorer** [comment]
v1.1.7
![image](https://github.com/josStorer/RWKV-Runner/assets/13366013/ea51b3fe-0b65-4e13-956b-797ce54c4e42)
