### ISSUE TITLE
Feature Request: Change Chat Prompt (Roles and Prompt)

### ISSUE THREAD

**Issue by cabralski** [josStorer/RWKV-Runner#48]
Currently, the prompt for the **Chat** mode on `python-backend` is as follows:

```txt
The following is a coherent verbose detailed conversation between a girl named {bot} and her friend {user}.
{bot} is very intelligent, creative and friendly.
{bot} is unlikely to disagree with {user}, and {bot} doesn't like to ask {user} questions.
{bot} likes to tell {user} a lot about herself and her opinions.
{bot} usually gives {user} kind, helpful and informative advices.
```

Some releases of RWKV such as RWKV-4-World, state that Alice/Bob should **not be used**, but instead: Human/Bot, User/AI, Question/Answer, see [this model card](https://huggingface.co/BlinkDL/rwkv-4-world) for the exact statement.

There are plenty of "configuration" endpoints now, such as:
```py
@router.post("/switch-model")
def switch_model(body: SwitchModelBody, response: Response):
    ...
```

We could make one more endpoint such as:
```py
@router.post("/change-chat-prompt")
def change_chat_prompt(body: ChangeChatPromptBody):
    ...
```
..that allows for changes the prompt, as well as specifying what `stop` is going to be (user, assistant). That will also require some UI changes.

**Comment by josStorer** [comment]
v1.4.3 and v1.4.5 have added user_name, assistant_name, raw, presystem fields to implement this

![image](https://github.com/josStorer/RWKV-Runner/assets/13366013/a42d3ad3-5a23-41c2-80be-fe503f1881a8)
