### ISSUE TITLE
windows 10 运行时报错:

### ISSUE THREAD

**Issue by gameplusai** [josStorer/RWKV-Runner#51]
NFO:     Started server process [11568]
INFO:     Waiting for application startup.
torch found: E:\ai\py310\Lib\site-packages\torch\lib
torch set
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:53384 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:53384 - "GET /status HTTP/1.1" 200 OK
INFO:     127.0.0.1:53384 - "OPTIONS /update-config HTTP/1.1" 200 OK
INFO:     127.0.0.1:53381 - "OPTIONS /switch-model HTTP/1.1" 200 OK
max_tokens=4100 temperature=1.2 top_p=0.5 presence_penalty=0.4 frequency_penalty=0.4
INFO:     127.0.0.1:53384 - "POST /update-config HTTP/1.1" 200 OK
E:\ai\py310\Lib\site-packages\_distutils_hack\__init__.py:18: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
  warnings.warn(
E:\ai\py310\Lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Using E:\ai\backend-python as PyTorch extensions root...
Ninja is required to load C++ extensions
INFO:     127.0.0.1:53384 - "POST /switch-model HTTP/1.1" 500 Internal Server Error

**Comment by josStorer** [comment]
检查torch版本是1.13

**Comment by josStorer** [comment]
最新版本已经解决了部分windows版本无法顺序安装依赖的问题，全新安装已不存在此问题
