### ISSUE TITLE
没有找到自定义的cuda文件

### ISSUE THREAD

**Issue by zsxbcc** [josStorer/RWKV-Runner#55]
运行时提示没有找到自定义的cuda文件

**Comment by zsxbcc** [comment]
我的 笔记本是有独立显卡的并且驱动更新到最新了  我的显卡时NVIDIA Geforce GTX950m 驱动版本 532.03

**Comment by josStorer** [comment]
目前内置算子不支持90系

**Comment by josStorer** [comment]
这个提示不影响使用，只是没有开启加速

**Comment by zsxbcc** [comment]
好的，谢谢您的解答， 什么时候更新训练功能啊

**Comment by josStorer** [comment]
目前前置功能告一段落，接下来会开始做训练

**Comment by josStorer** [comment]
[v1.3.5][https://github.com/josStorer/RWKV-Runner/releases/tag/v1.3.5] lora 微调已初步完善
