### ISSUE TITLE
Gtk-WARNING **: 11:29:16.623: cannot open display:

### ISSUE THREAD

**Issue by XiaolanX** [josStorer/RWKV-Runner#58]
![image](https://github.com/josStorer/RWKV-Runner/assets/67143380/a96b7ff6-daec-4d14-bfff-426b4dc7819a)
系统: ubuntu 22.04 LTS ,配置:  CPU: E5-2697v4 12H 内存: 12G 无显存（服务器awa）

**Comment by josStorer** [comment]
目前release中的均是gui版本，后面我会另外写服务器部署的说明

**Comment by josStorer** [comment]
可以

**Comment by XiaolanX** [comment]
我试试awa

**Comment by josStorer** [comment]
服务器部署示例脚本
https://github.com/josStorer/RWKV-Runner/tree/master/deploy-examples/ChatGPT-Next-Web
