### ISSUE TITLE
使用python来request会卡住。

### ISSUE THREAD

**Issue by doxtor6** [josStorer/RWKV-Runner#6]
第一次request没问题，第二次request就会卡住，不知道为什么。

**Comment by josStorer** [comment]
能否给个请求示例代码

**Comment by doxtor6** [comment]
import requests
data = {'model': 'rwkv', "messages": [
   {
     "role": "user",
     "content": "你好，我是TimmyLi."
   }
 ],}
requests.post("http://127.0.0.1:8000/v1/chat/completions", json=data).json()

python代码如上

就不会显示新的INFO
INFO:     127.0.0.1:55751 - "POST /switch-model HTTP/1.1" 200 OK
INFO:     127.0.0.1:56400 - "POST /v1/chat/completions HTTP/1.1" 200 OK

**Comment by josStorer** [comment]
替换这个文件
https://github.com/josStorer/RWKV-Runner/blob/master/backend-python/routes/completion.py

**Comment by josStorer** [comment]
可以直接把软件里的backend-python目录删掉，然后用github仓库里的覆盖
cdn缓存还没刷新，所以现在拉不到最新py

**Comment by doxtor6** [comment]
ok了，完美，感谢大佬。
