### ISSUE TITLE
希望能增加训练功能

### ISSUE THREAD

**Issue by win10ogod** [josStorer/RWKV-Runner#60]
希望能支持本地训练。

**Comment by Studying-365** [comment]
很感谢你们开发这个软件，我也希望有可以本地训练的功能。

**Comment by Studying-365** [comment]
> [v1.3.5](https://github.com/josStorer/RWKV-Runner/releases/tag/v1.3.5) lora 微调已初步完善

请教一下，RWKV-Runner使用lora微调有教程吗？LoRA model这里显示的是None。需请问要去哪里下载model吗？
此外，用sample里的形式输入文本，比如:
{"text": "1:There are 700 students in this school"}
{"text": "2:Each one paid 10000 dollars"}
...
麻烦确认下我的理解是正确的。

非常感谢你们付出时间来开发完善这个软件。


![image](https://github.com/josStorer/RWKV-Runner/assets/112904166/076497cc-8059-481c-9dd2-098a4a4ac374)

**Comment by josStorer** [comment]
LoRA模型为空就是正常训练，选中一个模型则是从此处继续训练
选中要用的LoRA模型点击合并，就会生成最终可用的完整模型

训练数据内的文本形式参考Completion页面的各种预设，如果是文章，就直接填全文，如果是对话，就写对话内容

**Comment by Studying-365** [comment]
> LoRA模型为空就是正常训练，选中一个模型则是从此处继续训练 选中要用的LoRA模型点击合并，就会生成最终可用的完整模型
> 
> 训练数据内的文本形式参考Completion页面的各种预设，如果是文章，就直接填全文，如果是对话，就写对话内容

我懂了，所以不一定要按照sample里面{"text": "1:There are 700 students in this school"} {"text": "2:Each one paid 10000 dollars"} 的格式。

理解了，非常感谢！

**Comment by ShawnL66** [comment]
你好，请问一下，本地模型下载之后，上传finetune 文本，全部用的默认设置，但点击Train但没有任何反应，请问是不是哪里出错了？

**Comment by josStorer** [comment]
@ShawnL66 Windows部分版本的系统可能因为组件缺失或版本问题, 没有调起WSL, 可以自己使用`wsl -l -v`确认有Ubuntu系统.
训练前可以手动安装好Ubuntu

**Comment by josStorer** [comment]
@Studying-365 最近更新了sample.jsonl, 可以参考里面的内容
点了Train没反应不正常, 参考我上一条回复, 检查下WSL Ubuntu
