### ISSUE TITLE
检测到病毒无法下载

### ISSUE THREAD

**Issue by ugkjkj** [josStorer/RWKV-Runner#62]
检测到病毒无法下载

**Comment by josStorer** [comment]
尝试添加到信任，或下载v1.0.9版本，然后滚动升级到最新版

**Comment by xzldragones** [comment]
1.1.9滚动升级到最新版1.2.0被windows11自带杀毒软件杀除。现在迫于无奈继续在使用1.1.9版本。

**Comment by josStorer** [comment]
建议添加信任

**Comment by josStorer** [comment]
可尝试这个版本：https://github.com/josStorer/RWKV-Runner/releases/download/v1.3.6/RWKV-Runner_win.zip
移除了运行释放功能

**Comment by xzldragones** [comment]
Thanks.

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: josc146 ***@***.***>
发送时间: Monday, July 10, 2023 2:56:41 PM
收件人: josStorer/RWKV-Runner ***@***.***>
抄送: xzldragones ***@***.***>; Comment ***@***.***>
主题: Re: [josStorer/RWKV-Runner] 检测到病毒无法下载 (Issue #62)


可尝试这个版本：https://github.com/josStorer/RWKV-Runner/releases/download/v1.3.6/RWKV-Runner_win.zip
移除了运行释放功能

―
