### ISSUE TITLE
切换模式错误

### ISSUE THREAD

**Issue by Jackjiang665** [josStorer/RWKV-Runner#63]
C:\Users\14821\Downloads\py310\Lib\site-packages\_distutils_hack\__init__.py:18: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
  warnings.warn(
C:\Users\14821\Downloads\py310\Lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Using C:\Users\14821\Downloads\backend-python as PyTorch extensions root...
Ninja is required to load C++ extensions
INFO:     127.0.0.1:61701 - "POST /switch-model HTTP/1.1" 500 Internal Server Error
显示这个错误是怎么回事？要怎么做呢？

**Comment by josStorer** [comment]
你开启了cuda算子加速，并安装了torch2.x版本
关闭加速或者降级到torch1.13

**Comment by josStorer** [comment]
最新版本已经解决了部分windows版本无法顺序安装依赖的问题，全新安装已不存在此问题
