### ISSUE TITLE
端口号被占用问题

### ISSUE THREAD

**Issue by 77283103** [josStorer/RWKV-Runner#65]
当端口号被占用，因为启动程序会一闪而过，很难排查到这个问题，希望将端口号配置配置设置再UI里面

**Comment by josStorer** [comment]
配置页面可以设置端口号，我想我是应该做一下端口号占用检测

**Comment by 77283103** [comment]
好的  我找见了端口配置  可以把cmd控制台集成到 UI里面  避免意外关闭

**Comment by josStorer** [comment]
https://github.com/josStorer/RWKV-Runner/releases/tag/v1.5.0

已加入端口占用检测
