### ISSUE TITLE
切换模型失败

### ISSUE THREAD

**Issue by lujunjiehhh** [josStorer/RWKV-Runner#66]
报错 INFO:     127.0.0.1:62749 - "POST /switch-model HTTP/1.1" 500 Internal Server Error
![image](https://github.com/josStorer/RWKV-Runner/assets/49628289/bfbe2acc-4fcb-4614-89e8-d8c7617dacc0)

**Comment by josStorer** [comment]
#38, #53
错误的torch版本
关闭算子加速，或安装指定版本(仅限windows启用内置算子加速)

**Comment by josStorer** [comment]
最新版本已经解决了部分windows版本无法顺序安装依赖的问题，全新安装已不存在此问题
