### ISSUE TITLE
不知道有没有兴趣推出基于arm架构的linux版本？

### ISSUE THREAD

**Issue by NeonBubbles** [josStorer/RWKV-Runner#67]
我的oracle 免费 vps 用的是arm架构，目前似乎只能通过源码编译，还不知道行不行。

**Comment by josStorer** [comment]
源码编译可以参考自动构建管线的linux部分: https://github.com/josStorer/RWKV-Runner/blob/master/.github/workflows/release.yml

**Comment by josStorer** [comment]
目前暂没有计划直接提供arm版本，抱歉
