### ISSUE TITLE
1.切换模型失败,请尝试以管理员权限启动程序   2.没有找到支持的自定义cuda文件   3.正在读取模型

### ISSUE THREAD

**Issue by sola0031** [josStorer/RWKV-Runner#68]
第一步，配置参数，提示能配置成功，提示转换成功

可是为什么在上述配置时，显示用的是cpu，并且内存占满使用，而显卡几乎没用

我用的python=3.10 

torch= 2.0.1+cu118

torchaudio=2.0.2+cu118

torchvision= 0.15.2+cu118

我上述版本不正确嘛？

第二步，我点运行，就会报错

1.切换模型失败,请尝试以管理员权限启动程序 

2.没有找到支持的自定义cuda文件  

 3.正在读取模型

请问如何解决

**Comment by josStorer** [comment]
错误安装了cpu版本的torch，删除py310/lib/site-packages/torch 以及torch-2.0.1.dist-info, 并删除exe旁边的cache.json, 然后启动重装依赖
你的windows版本是什么

**Comment by sola0031** [comment]
我是win10版本
我之前用pip list 显示，我只 有
torch= 2.0.1+cu118

torchaudio=2.0.2+cu118

torchvision= 0.15.2+cu118

我待会去看看是否因为有残留吧

谢谢

**Comment by josStorer** [comment]
最新版本已经解决了部分windows版本无法顺序安装依赖的问题，全新安装已不存在此问题

**Comment by sola0031** [comment]
感谢，收到
