### ISSUE TITLE
INFO:     127.0.0.1:51637 - "POST /v1 HTTP/1.1" 404 Not Found

### ISSUE THREAD

**Issue by sdpfer** [josStorer/RWKV-Runner#73]
请问这是怎么回事
INFO:     127.0.0.1:51637 - "POST /v1 HTTP/1.1" 404 Not Found

  function sendMessageToAPI(message) {
    // 使用AJAX发送POST请求到本地API
    const xhr = new XMLHttpRequest();
    xhr.open('POST', 'http://127.0.0.1:8000/v1', true);
    xhr.setRequestHeader('Content-Type', 'application/json');

    xhr.onload = function () {
      if (xhr.status == 200) {
        const response = JSON.parse(xhr.responseText);
        const reply = response.reply;

        appendMessage('AI', reply);
      } else {
        console.error(xhr.statusText);
      }
    };

**Comment by josStorer** [comment]
看api文档 http://127.0.0.1:8000/docs

**Comment by sdpfer** [comment]
看过很多次了，但是不知道怎么用

**Comment by sdpfer** [comment]
> 看api文档 http://127.0.0.1:8000/docs

看过了，但是不知道什么意思

**Comment by josStorer** [comment]
https://github.com/josStorer/RWKV-Runner/wiki/FAQs

浏览器控制台调用示例
```javascript
fetch("http://127.0.0.1:8000/chat/completions", {
  method: "POST",
  headers: { "Content-Type": "application/json" },
  body: JSON.stringify({ messages: [{ role: "user", content: "Hello" }] }),
})
  .then((r) => r.json())
  .then(console.log);
```

**Comment by sdpfer** [comment]
> https://github.com/josStorer/RWKV-Runner/wiki/FAQs
> 
> 浏览器控制台调用示例
> 
> ```js
> fetch("http://127.0.0.1:8000/chat/completions", {
>   method: "POST",
>   headers: { "Content-Type": "application/json" },
>   body: JSON.stringify({ messages: [{ role: "user", content: "Hello" }] }),
> })
>   .then((r) => r.json())
>   .then(console.log);
> ```

感谢
