### ISSUE TITLE
停止和重新生成 RWKV 响应的建议函数

### ISSUE THREAD

**Issue by ook11** [josStorer/RWKV-Runner#76]
如果Chat增加一个类似ChatGPT的功能，比如标题中的功能，就可以在不牺牲前一个反应的历史的情况下，在反应崩溃的情况下重新进行。

我很抱歉，这句话可能不是正确的角色，因为我使用了翻译器。

**Comment by josStorer** [comment]
Are you talking about adding a retry button or the function to edit your question?

BTW: I can speak English. Even if you are not from an English-speaking country, some translators may provide better quality when translating to English.

**Comment by ook11** [comment]
Yes, I am. I propose adding a ChatGPT-like retry button, a stop button, and the ability to edit questions to the chat. I would also suggest adding a button to generate a continuation of a response that has been stopped due to a token limit.

**Comment by josStorer** [comment]
Okay, I will add these features, and also, while an answer is being generated, the send button will change to a stop button which you can click to stop the generation.

**Comment by ook11** [comment]
Oh! Thank you, Now I can enjoy RWKV-Runner even more!

**Comment by josStorer** [comment]
retry and edit button have been implemented since v1.2.7
