### ISSUE TITLE
Support for custom tokenizer/vocab size

### ISSUE THREAD

**Issue by Yuzabotov** [josStorer/RWKV-Runner#77]
It would be nice if we could choose a custom tokenizer json file and vocab size, for custom models that have new tokens added

**Comment by josStorer** [comment]
[v1.4.6](https://github.com/josStorer/RWKV-Runner/releases/tag/v1.4.6)

![image](https://github.com/josStorer/RWKV-Runner/assets/13366013/604a8f5a-51d0-4e7f-9e54-d760b0ae67fb)
