### ISSUE TITLE
[1.2.4 on linux] Nothing happens when I try to run the model

### ISSUE THREAD

**Issue by Maykeye** [josStorer/RWKV-Runner#79]
Linux, 32GB RAM, 16GB VRAM.

I downloaded 7B world, 
however when I click "Run" in configs nothing happens  - button turns into "Starting" for two seconds and then the button returns to "run". Nothing is reported and model is not loaded (as judging by "Chat" and "Completition" tab, and if I try to run from there - also nothing happen).

last config I tried
![image](https://github.com/josStorer/RWKV-Runner/assets/13607441/c38e682b-6077-4f3c-9a35-ebebb1205143)

It doesn't matter if I turn off/on custom kernel, change the precision to fp16/fp32/i8, change number of layers on gpu, use CPU strategy -- model stays offline

To rule out corrupted download, I tried RWKV-4-Pile-7B-20230109-ctx4096.pth (known to work using ooba with `cuda fp16i8` strategy which I also tried) - nothing happens. 
`nvidia-smi` doesn't show that VRAM was allocated by the program either.
And I can't find any logs to dig further.

**Comment by josStorer** [comment]
Try executing `python3 backend-python/main.py` to see if there are any error messages

**Comment by Maykeye** [comment]
```
INFO:     Started server process [1310434]
INFO:     Waiting for application startup.
torch found: /home/fella/src/sd/sd/lib/python3.11/site-packages/torch/lib
torch set
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
max_tokens=4100 temperature=1.2 top_p=0.5 presence_penalty=0.4 frequency_penalty=0.4
INFO:     127.0.0.1:56866 - "POST /update-config HTTP/1.1" 200 OK
Killed
```
Frontend calls  `/exit` after a while which terminates main.py
