### ISSUE TITLE
chat/completion里没有system的role

### ISSUE THREAD

**Issue by doxtor6** [josStorer/RWKV-Runner#8]
user和assistant的role都有，建议增加system的role.

**Comment by josStorer** [comment]
因为对rwkv来说，system并不能和gpt的api兼容，所以我没有提供，建议使用/completion 接口，同样可以定义你的prompt

**Comment by josStorer** [comment]
我可以通过简单的文本替换来兼容试试

**Comment by doxtor6** [comment]
可以，我刚刚也想说可以这样，拜托大佬了。

**Comment by doxtor6** [comment]
牛的，感谢。
