### ISSUE TITLE
MAC 回复响应速度极慢

### ISSUE THREAD

**Issue by zllxta** [josStorer/RWKV-Runner#82]
硬件信息：MACBOOK  M1 8G内存
模型：RWKV-4-World-CHNtuned-1.5B-v1-20230620-ctx4096.pth   描述：100+ 语言 1.5B v1 中文增强
问题1：不论使用MPS 或者CPU  载入后的回复 几乎是30-60秒一个中文字符，CPU占用率不高
问题2:下载载入RWKV-4-Raven-7B-v12-Eng49%-Chn49%-Jpn1%-Other1%-20230530-ctx8192.pth 描述：中文 7B v12 载入直接失败。

**Comment by josStorer** [comment]
内存不够，存硬盘了，硬盘速度慢
