### ISSUE TITLE
Failed to switch model - {"detail":"failed to load: Command '['where', 'cl']' returned non-zero exit status 1."}

### ISSUE THREAD

**Issue by caojiachen1** [josStorer/RWKV-Runner#84]
INFO:     Started server process [18744]
INFO:     Waiting for application startup.
torch found: D:\RWKV\venv\Lib\site-packages\torch\lib
torch set
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:1046 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:1046 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:1046 - "GET /status HTTP/1.1" 200 OK
INFO:     127.0.0.1:1046 - "OPTIONS /update-config HTTP/1.1" 200 OK
max_tokens=4100 temperature=1.2 top_p=0.5 presence_penalty=0.4 frequency_penalty=0.4
INFO:     127.0.0.1:1046 - "POST /update-config HTTP/1.1" 200 OK
INFO:     127.0.0.1:1049 - "OPTIONS /switch-model HTTP/1.1" 200 OK
Using D:\RWKV\backend-python as PyTorch extensions root...
D:\RWKV\venv\lib\site-packages\torch\utils\cpp_extension.py:358: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
Detected CUDA files, patching ldflags
Emitting ninja build file D:\RWKV\backend-python\wkv_cuda\build.ninja...
INFO: Could not find files for the given pattern(s).
Command '['where', 'cl']' returned non-zero exit status 1.
INFO:     127.0.0.1:1049 - "POST /switch-model HTTP/1.1" 500 Internal Server Error

**Comment by dionylon** [comment]
> INFO: Started server process [18744] INFO: Waiting for application startup. torch found: D:\RWKV\venv\Lib\site-packages\torch\lib torch set INFO: Application startup complete. INFO: Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit) INFO: 127.0.0.1:1046 - "GET / HTTP/1.1" 200 OK INFO: 127.0.0.1:1046 - "GET / HTTP/1.1" 200 OK INFO: 127.0.0.1:1046 - "GET /status HTTP/1.1" 200 OK INFO: 127.0.0.1:1046 - "OPTIONS /update-config HTTP/1.1" 200 OK max_tokens=4100 temperature=1.2 top_p=0.5 presence_penalty=0.4 frequency_penalty=0.4 INFO: 127.0.0.1:1046 - "POST /update-config HTTP/1.1" 200 OK INFO: 127.0.0.1:1049 - "OPTIONS /switch-model HTTP/1.1" 200 OK Using D:\RWKV\backend-python as PyTorch extensions root... D:\RWKV\venv\lib\site-packages\torch\utils\cpp_extension.py:358: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified warnings.warn(f'Error checking compiler version for {compiler}: {error}') Detected CUDA files, patching ldflags Emitting ninja build file D:\RWKV\backend-python\wkv_cuda\build.ninja... INFO: Could not find files for the given pattern(s). Command '['where', 'cl']' returned non-zero exit status 1. INFO: 127.0.0.1:1049 - "POST /switch-model HTTP/1.1" 500 Internal Server Error

same ERROR，try put msvc cl into your environment PATH, 
like this: "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x64"

but I got another link error , finally I just turn off the "Use Custom CUDA kernel to Accelerate"  and everything fine.

**Comment by josStorer** [comment]
Are you using a custom Python interpreter? A custom interpreter requires compiling the CUDA kernel by yourself. Using an auto downloaded Python interpreter will enable the built-in kernel.

**Comment by caojiachen1** [comment]
That works.I shouldn't use venv.Thanks a lot!
