### ISSUE TITLE
No module named 'tiktoken'

### ISSUE THREAD

**Issue by WRTY1** [josStorer/RWKV-Runner#90]
错误来源于backend-python\routes\completion.py

更新版本：1.1.9->1.2.8

**Comment by josStorer** [comment]
点击安装即可，新增了一个依赖

**Comment by josStorer** [comment]
如果是手动替换安装，请删除cache.json重启

**Comment by LainNetWork** [comment]
我也遇到了，自己倒腾了一下，在.\RWKVRunner安装路径\py310\Scripts 下执行 .\pip3.10.exe install tiktoken 貌似也行
