### ISSUE TITLE
乱码、卡死

### ISSUE THREAD

**Issue by David7725111** [josStorer/RWKV-Runner#91]
![image](https://github.com/josStorer/RWKV-Runner/assets/135567586/93c63cbc-3337-47fb-a3ab-2be7bd288e13)
聊天都是乱码，而且聊着没几句就卡死了，后台没报错，知道是为什么以吗

**Comment by josStorer** [comment]
更新显卡驱动试试，你是什么显卡

**Comment by David7725111** [comment]
感谢回复，我是笔记本1660 6G显存的显卡。我能确认我载入了正确的模型文件，聊天对聊天文件。小说模块用的小说模型，但是点生成是完全没有反应的状态。

________________________________

**Comment by chenzanyu** [comment]
我的也是笔记本1660Ti.使用1.5B模型正常， 3B及以上就乱码和异常了

**Comment by josStorer** [comment]
试过更新显卡驱动了吗

**Comment by chenzanyu** [comment]
更新驱动后正常

**Comment by David7725111** [comment]
周末系统更新了驱动程序，RWKV升级了。然后就可以正常使用模型了。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年7月2日 11:50
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [josStorer/RWKV-Runner] 乱码、卡死 (Issue #91)


更新驱动后正常

―
