### ISSUE TITLE
内存占满，速度慢。

### ISSUE THREAD

**Issue by rj11304** [josStorer/RWKV-Runner#93]
我的配置是16G+1060 6G显存/8G共享内存内置显卡，加载的是8G-7B的模型。每次加载都需要半小时，内存在加载时总是占满了，把除自己外的其他应用都逼关了。加载完内存占用降低。加载完后，回复大约1个字每秒。我后台查看了cpu和gpu占用。cpu占用一直比较高，使用20-30%（关掉后只占用4%左右）。gpu只在提问时使用12-20%（约3s左右）。但是，回答出字依然很慢。想问一下，者是否正常？为什么，gpu都不使用了，出字还那么慢。为什么cpu占用会那么高。

**Comment by josStorer** [comment]
模型必须载入专用显存，共享显存是内存，无法使用
7B模型无法完整载入6G显存，默认配置在启动时会先转换为低精度，然后载入部分层数到显存
这个步骤由CPU完成，因此会出现启动时CPU占满，很卡的情况，如果一个配置你确定了，那么可以在配置页面，点击转换按钮，会直接生成转换好的模型，转换后选择新生成的模型，下次读取就不用重复转换步骤，不会再导致CPU吃满，转换花费很长时间的情况了

另外你可以检查一下专用显存占用是否吃满，如果还有空余，可以在配置页面增加载入显存层数，显存尽量吃满，会得到比较好的速度

此外如果你用的是raven模型，可以尝试换成world，中文生成速度会更快，记得使用int8，开启CUDA算子加速

这一系列操作完成，你应该能获得三到四倍的提速

**Comment by rj11304** [comment]
专用显存是吃满了的，就是有个问题，为啥载入模型运行后，单纯是沾满了显存，显卡并没有用到多少，然而，出字却很慢。

**Comment by josStorer** [comment]
尝试更新驱动，此外windows的占用率显示可能并不完全准确，可以检查显卡功耗
最终以生成速度为准，1060跑7b每秒两三个字是正常的

**Comment by rj11304** [comment]
关键是，目前只有1个子/秒的速度。我运行时，显卡风扇都不开，可见，真的没占什么显卡。我平时玩游戏，显卡风扇转的飞起。

**Comment by josStorer** [comment]
运行时的配置页面截图看一下

**Comment by rj11304** [comment]
不在这台电脑，没法截图。配置除了修改模型，其他都没改，都是默认的。

**Comment by rj11304** [comment]
如果有多张显卡的情况下，应用能够准确识别到哪张显卡吗？我怀疑是应用用了我的集显，并没用到我的独显。

**Comment by josStorer** [comment]
占用显存了，肯定用了独显
