### ISSUE TITLE
求助，如何让RWKV-Runner模型支持AMD显卡呢，有大佬知道吗，我有Ubuntu虚拟机

### ISSUE THREAD

**Issue by mcpanl** [josStorer/RWKV-Runner#95]
如题所示，如何让RWKV-Runner模型支持AMD显卡呢，有大佬知道吗，我有Ubuntu虚拟机

**Comment by josStorer** [comment]
不确定WSL能否调用AMD显卡，你可以尝试安装torch，参考pytorch官网
`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm5.4.2`

**Comment by PJ-568** [comment]
> 如题所示，如何让RWKV-Runner模型支持AMD显卡呢，有大佬知道吗，我有Ubuntu虚拟机

现在支持调用 WebGPU 了应该可行。

**Comment by josStorer** [comment]
#99
