### ISSUE TITLE
 DefaultCPUAllocator: not enough memory: you tried to allocate 268435456 bytes.

### ISSUE THREAD

**Issue by RayenDhifi** [josStorer/RWKV-Runner#97]
I am trying to run RWKV-4-Raven-7-v12 on the GPU-4G-7B-EN config, i tired with CUDA at 8, 4 and 1 layer, i also tried with cpu and tried with other configs i keep getting the same error over and over: 

```
[enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 268435456 bytes.
←[32mINFO←[0m:     127.0.0.1:26549 - "←[1mPOST /switch-model HTTP/1.1←[0m" ←[91m500 Internal Server Error←[0m
```

My specs: 

GPU: Rtx 3060
CPU: i5 11400F
Ram: 16gb

**Comment by BlinkDL** [comment]
use more CUDA layers and increase virtual memory to 32G

**Comment by josStorer** [comment]
increase your virtual memory
