### ISSUE TITLE
Auto-detect existed models to avoid duplicate download (manually refresh is terrible)

### ISSUE THREAD

**Issue by ZhUyU1997** [josStorer/RWKV-Runner#98]
I copy the models to another directory due to some issue, then reinstall Runner. 
When restoring the models directory, the runner can't detect the change.

**Comment by josStorer** [comment]
👌

**Comment by josStorer** [comment]
fixed in [v1.3.5](https://github.com/josStorer/RWKV-Runner/releases/tag/v1.3.5)
