### ISSUE TITLE
feature request: add torch-directml execute engine to support acceleration on other gpu vendors

### ISSUE THREAD

**Issue by ytfh44** [josStorer/RWKV-Runner#99]
譬如说a卡和Intel核显

**Comment by josStorer** [comment]
最新版本已支持DML, 配置页面Strategy选择自定义, 然后输入 dml fp16

你也可以将Strategy切换为WebGPU, 同样支持Nvidia以外的GPU设备

The latest version now supports DML. In the `Configs` page, select `Custom` for `Strategy`, and then enter `dml fp16`.

You can also switch Strategy to `WebGPU`, which also supports GPU devices of Intel, AMD, etc.

![image](https://github.com/josStorer/RWKV-Runner/assets/13366013/ebc2c6a1-5d97-4ba2-bb6a-cf15ee073cde)

![image](https://github.com/josStorer/RWKV-Runner/assets/13366013/44d7f44c-3b9b-491d-939e-3e7eb10be2a7)
